call %~dp0\runexample1 examples\ospfv2\areas  omnetpp.ini General
call %~dp0\runexample1 examples\ospfv2\backbone  omnetpp.ini General
call %~dp0\runexample1 examples\ospfv2\fulltest  omnetpp.ini General
call %~dp0\runexample1 examples\ospfv2\simpletest  omnetpp.ini General
call %~dp0\runexample1 examples\wireless\handover  omnetpp.ini General
call %~dp0\runexample1 examples\wireless\throughput  omnetpp.ini  Throughput1
call %~dp0\runexample1 examples\wireless\throughput  omnetpp.ini  Throughput2
call %~dp0\runexample1 examples\wireless\hosttohost  omnetpp.ini  Throughput1
call %~dp0\runexample1 examples\wireless\lan80211  omnetpp-ftp.ini  TwoHosts
call %~dp0\runexample1 examples\wireless\lan80211  omnetpp-ftp.ini  NHosts
call %~dp0\runexample1 examples\wireless\lan80211  omnetpp.ini  Ping1
:: skipping interactive config: call %~dp0\runexample1 examples\wireless\lan80211  omnetpp.ini  Ping2
call %~dp0\runexample1 examples\wireless\lan80211  omnetpp-streaming.ini  Streaming1
call %~dp0\runexample1 examples\wireless\lan80211  omnetpp-streaming.ini  Streaming2
call %~dp0\runexample1 examples\inet\flatnet  omnetpp.ini General
call %~dp0\runexample1 examples\inet\multicast  omnetpp.ini General
call %~dp0\runexample1 examples\inet\kidsnw1  omnetpp.ini General
call %~dp0\runexample1 examples\inet\bulktransfer  omnetpp.ini General
call %~dp0\runexample1 examples\inet\routerperf  omnetpp.ini General
call %~dp0\runexample1 examples\inet\nclients  omnetpp.ini General
call %~dp0\runexample1 examples\inet\nclients  basicHTTP.ini General
call %~dp0\runexample1 examples\inet\nclients  nclients2.ini General
call %~dp0\runexample1 examples\inet\nclients  omnetpp-ping.ini General
call %~dp0\runexample1 examples\inet\nclients  video.ini General
call %~dp0\runexample1 examples\inet\nclients  filetransfer.ini General
call %~dp0\runexample1 examples\inet\redtest  omnetpp.ini  DropTailQueue
call %~dp0\runexample1 examples\inet\redtest  omnetpp.ini  REDQueue1
call %~dp0\runexample1 examples\inet\redtest  omnetpp.ini  REDQueue2
call %~dp0\runexample1 examples\ethernet\arptest2  omnetpp.ini  ARPTest
call %~dp0\runexample1 examples\ethernet\lans  omnetpp.ini  MixedLAN1
call %~dp0\runexample1 examples\ethernet\lans  bus.ini  BusLAN
call %~dp0\runexample1 examples\ethernet\lans  switch.ini  SwitchedLAN1
call %~dp0\runexample1 examples\ethernet\lans  hub.ini  Hub1
call %~dp0\runexample1 examples\ethernet\lans  hub.ini  Hub2
call %~dp0\runexample1 examples\ethernet\lans  hub.ini  Hub3
call %~dp0\runexample1 examples\ethernet\lans  hub.ini  Hub4
call %~dp0\runexample1 examples\ethernet\lans  duplexswitch.ini  SwitchedDuplexLAN
call %~dp0\runexample1 examples\ethernet\lans  mixed.ini  MixedLAN
call %~dp0\runexample1 examples\ethernet\lans  largeNet.ini  LargeNet
call %~dp0\runexample1 examples\ethernet\lans  twoHosts.ini  TwoHosts1
call %~dp0\runexample1 examples\ethernet\arptest  omnetpp.ini  ARPTest
call %~dp0\runexample1 examples\adhoc\mf80211  omnetpp.ini  Ping1
:: skipping interactive config: call %~dp0\runexample1 examples\adhoc\mf80211  omnetpp.ini  Ping2
call %~dp0\runexample1 examples\adhoc\mobility  omnetpp.ini  LinearMobility
call %~dp0\runexample1 examples\adhoc\mobility  omnetpp.ini  MassMobility
call %~dp0\runexample1 examples\adhoc\mobility  omnetpp.ini  RandomWPMobility
call %~dp0\runexample1 examples\adhoc\mobility  omnetpp.ini  CircleMobility
call %~dp0\runexample1 examples\adhoc\mobility  omnetpp.ini  RectangleMobility
call %~dp0\runexample1 examples\adhoc\mobility  omnetpp.ini  TurtleMobility1
call %~dp0\runexample1 examples\adhoc\mobility  omnetpp.ini  TurtleMobility2
call %~dp0\runexample1 examples\adhoc\mobility  omnetpp.ini  TurtleMobility3
call %~dp0\runexample1 examples\adhoc\mobility  omnetpp.ini  TurtleMobility4
call %~dp0\runexample1 examples\adhoc\mobility  omnetpp.ini  TurtleMobility5
call %~dp0\runexample1 examples\adhoc\mobility  omnetpp.ini  TurtleMobility6
call %~dp0\runexample1 examples\adhoc\mobility  omnetpp.ini  ANSimMobility
call %~dp0\runexample1 examples\adhoc\mobility  omnetpp.ini  BonnMotionMobility1
call %~dp0\runexample1 examples\adhoc\mobility  omnetpp.ini  BonnMotionMobility2
call %~dp0\runexample1 examples\adhoc\ieee80211  omnetpp.ini  Ping1
:: skipping interactive config: call %~dp0\runexample1 examples\adhoc\ieee80211  omnetpp.ini  Ping2
call %~dp0\runexample1 examples\mpls\testte_tunnel  omnetpp.ini General
call %~dp0\runexample1 examples\mpls\net37  omnetpp.ini General
call %~dp0\runexample1 examples\mpls\testte_routing  omnetpp.ini General
call %~dp0\runexample1 examples\mpls\testte_failure  omnetpp.ini General
call %~dp0\runexample1 examples\mpls\ldp  omnetpp.ini General
call %~dp0\runexample1 examples\mpls\testte_failure2  omnetpp.ini General
call %~dp0\runexample1 examples\mpls\testte_reroute  omnetpp.ini General
call %~dp0\runexample1 examples\ipv6\nclients  omnetpp.ini General
call %~dp0\runexample1 examples\ipv6\demonetworketh  omnetpp.ini General
