#undef stat
#undef sigaction
#undef open
#undef crypt
#undef getrusage
#undef time
#undef getpid
#undef gettimeofday
#undef sigfillset
#undef random
#undef socket
#undef getpwnam
#undef getgrnam
#undef setregid
#undef setreuid
#undef seteuid
#undef umask
#undef daemon
#undef srand
#undef sync
#undef setsockopt
#undef getuid
#undef geteuid
#undef exit
#undef mkstemp
#undef getcwd
#undef openlog
#undef closelog
#undef vsyslog
#undef connect
#undef listen
#undef bind
#undef fcntl
#undef getsockname
#undef sendto
#undef recvfrom
#undef recvmsg
#undef fopen
#undef getpagesize
#undef write
#undef select
#undef accept
#undef sendmsg
#undef close
#undef read
#undef writev
#undef perror
#undef _exit
#undef abort
#undef getpeername
#undef getsockopt
#undef chmod
#undef unlink
#undef link
#undef chdir
#undef uname
#undef ioctl
#undef setgroups
#undef getenv
#undef zmalloc
#undef zcalloc
#undef zrealloc
#undef getservbyname
#undef htonl
#undef htons
#undef inet_ntoa
#undef ntohl
#undef ntohs
#undef inet_addr
#undef inet_aton
#undef inet_pton
#undef inet_ntop

