#! /bin/bash
git log --format="%an" | sort | uniq
echo -----------------------------------------------------------------------------------------------------------
git log --format="%cn" | sort | uniq
echo -----------------------------------------------------------------------------------------------------------
find src -type f | egrep -v "(tcp_lwip/lwip|aodv-uu/aodv-uu|dsr/dsr-uu|dymo/dymoum|batman/batmand|olsr)" > filelist.tmp
cat filelist.tmp | xargs grep -iR '(c)'  | sed 's/.*20[01][0-9] *//' | sed 's/.*(C) *//' | sort | uniq
echo -----------------------------------------------------------------------------------------------------------
cat filelist.tmp | xargs grep -iRE '\bAuthors?\b' |  grep -v 'THE AUTHOR ' | sed 's/.*authors\?:\? *//i' | sort | uniq
echo -----------------------------------------------------------------------------------------------------------
find src -name ChangeLog | xargs grep -iE 'patch|report'

