FROM ubuntu:16.04

WORKDIR /opt/

RUN apt-get update -y && apt-get install -y git autoconf libiberty-dev build-essential python3-minimal python3-dev

RUN git clone https://github.com/distcc/distcc.git

WORKDIR distcc

RUN ./autogen.sh
RUN ./configure
RUN make -j $(nproc)
RUN make install

WORKDIR /opt/

# we use a lot of potential addresses, the offline/unavailable ones will be skipped automatically
# and we set 10 slots for each of them, the local servers will limit the actual number of concurrently running jobs
ENV DISTCC_HOSTS="13.37.42.1/10,lzo 13.37.42.2/10,lzo 13.37.42.3/10,lzo 13.37.42.4/10,lzo 13.37.42.5/10,lzo 13.37.42.6/10,lzo 13.37.42.7/10,lzo 13.37.42.8/10,lzo"

RUN useradd -ms /bin/bash distcc

# need to launch from a shell to expand $(nproc)
ENTRYPOINT ["/bin/bash", "-c", "distccd --allow 0.0.0.0/0 --listen 0.0.0.0 -j $(nproc) --no-detach --log-level debug --log-stderr --verbose"]
