(cd cutthroughswitching ; ./run.sh)
(cd framepreemption ; ./run.sh)
(cd framereplication ; ./run.sh)
(cd gatescheduling ; ./run.sh)
(cd streamfiltering ; ./run.sh)
(cd timesynchronization ; ./run.sh)
(cd trafficshaping ; ./run.sh)
