#!/bin/bash

cd `dirname $0`/../..
INETROOT=`pwd`
OMNETPPROOT=$INETROOT/../omnetpp-4.2

# Check root directory of OMNeT++ 4
if [ -d $OMNETPPROOT ]
then
	echo "Cheking root directories for INET and OMNeT++ ..."
	echo "- INETROOT=$INETROOT"
	echo "- OMNETPPROOT=$OMNETPPROOT"
	echo ""
else
	echo "Oops! I cannot find OMNeT++ 4 root directory."
	echo "Check this shell script to fix it."
	exit 1
fi

# Get a list of relative paths for updated files
updatedFiles=`cd $INETROOT/etc/omnetpp-extension/root; find . \( -name "*.cc" -o -name "*.h" \) -print`

cd $OMNETPPROOT
echo "Updating OMNeT++ in `pwd` ..."

echo "- Copying files from $INETROOT/etc/omnetpp-extension/root ..."
for file in $updatedFiles
do
	if [ -e $file ]; then
		mv $file $file.org
	fi
	cp $INETROOT/etc/omnetpp-extension/root/$file $file
done

echo "- Making ..."
make

echo ""
echo "Finished updating OMNeT++."
echo "Now you can go back to working at your INET directory!"
