#ifndef	__GLOBALVARS_LIB_H__
#define	__GLOBALVARS_LIB_H__

#include "allheaders.h"

#undef errno
#define errno  errno__VAR

extern struct GlobalVars_lib * __activeVars_lib;

#ifdef __cplusplus
extern "C" {
#endif    

void GlobalVars_initializeActiveSet_lib();
struct GlobalVars_lib * GlobalVars_createActiveSet_lib();
    
#ifdef __cplusplus
}
#endif

struct GlobalVars_lib
{
    struct cmd_element show_memory_ripng_cmd__X;
    struct cmd_element show_memory_rip_cmd__X;
    struct cmd_element show_memory_bgp_cmd__X;
    struct cmd_element show_memory_ospf_cmd__X;
    struct cmd_element show_memory_ospf6_cmd__X;
    
    struct cmd_element ip_prefix_list_description_cmd__X;
    struct cmd_element no_ip_prefix_list_description_arg_cmd__X;
    struct cmd_element no_ip_prefix_list_description_cmd__X;
    struct cmd_element no_neighbor_description_cmd__X;
    struct cmd_element neighbor_description_cmd__X;
    struct cmd_element no_neighbor_description_val_cmd__X;
    
    struct cmd_node zebra_node__X;
    struct cmd_element router_zebra_cmd__X;
    struct cmd_element no_router_zebra_cmd__X;
    struct in_addr router_id_zebra__X;
        
    struct cmd_element show_ip_community_list_arg_cmd__X;
    struct cmd_element no_neighbor_distribute_list_cmd__X;
    struct cmd_element no_neighbor_maximum_prefix_cmd__X;
    struct cmd_element accept_lifetime_day_month_day_month_cmd__X;
    struct cmd_element no_neighbor_attr_unchanged9_cmd__X;
    struct cmd_element no_set_community_val_cmd__X;
    struct cmd_element config_help_cmd__X;
    struct cmd_element no_capability_opaque_cmd__X;
    struct cmd_element send_lifetime_day_month_month_day_cmd__X;
    struct cmd_element no_ip_route_distance_cmd__X;
    struct cmd_element no_match_origin_val_cmd__X;
    struct hash * cpu_record__X;
    struct cmd_element show_ip_route_cmd__X;
    struct cmd_element no_service_password_encrypt_cmd__X;
    struct cmd_element no_neighbor_default_originate_rmap_cmd__X;
    struct peer_flag_action peer_flag_action_list__X[9];
    struct cmd_element set_metric_type_cmd__X;
    struct cmd_element no_mpls_te_cmd__X;
    struct cmd_element no_neighbor_timers_connect_val_cmd__X;
    struct cmd_element no_access_list_extended_any_mask_cmd__X;
    int dump_notify__X;
    int vty_config__X;
    struct cmd_element rmap_onmatch_goto_cmd__X;
    struct route_map_rule_cmd route_set_metric_cmd__X;
    struct cmd_element no_neighbor_capability_route_refresh_cmd__X;
    struct cmd_element config_log_syslog_level_cmd__X;
    struct cmd_element no_config_log_facility_cmd__X;
    struct cmd_node as_list_node__X;
    struct cmd_element aggregate_address_summary_only_cmd__X;
    struct cmd_element no_set_origin_val_cmd__X;
    struct route_map_rule_cmd route_set_atomic_aggregate_cmd__X;
    struct route_map_rule_cmd route_match_tag_cmd__X;
    struct route_map_rule_cmd route_set_community_cmd__X;
    int opterr__X;
    struct cmd_element no_ip_extcommunity_list_name_all_cmd__X;
    struct cmd_element no_ip_route_flags_distance_cmd__X;
    struct cmd_element no_neighbor_remote_as_cmd__X;
    struct cmd_element set_vpnv4_nexthop_cmd__X;
    int Debug_Radix__X;
    struct cmd_element show_ip_prefix_list_prefix_first_match_cmd__X;
    struct cmd_element neighbor_send_community_cmd__X;
    struct cmd_element accept_lifetime_infinite_day_month_cmd__X;
    struct cmd_element mpls_te_cmd__X;
    struct cmd_element show_address_cmd__X;
    int syslog_fd__X;
    struct cmd_element no_route_map_all_cmd__X;
    struct cmd_element config_log_syslog_facility_cmd__X;
    struct cmd_element no_ip_prefix_list_sequence_number_cmd__X;
    struct cmd_element no_neighbor_nexthop_local_unchanged_cmd__X;
    struct cmd_node access_node__X;
    struct cmd_element neighbor_maximum_prefix_threshold_cmd__X;
    struct cmd_element neighbor_maximum_prefix_cmd__X;
    struct cmd_element terminal_monitor_cmd__X;
    struct cmd_element access_list_extended_host_any_cmd__X;
    struct cmd_element config_quit_cmd__X;
    struct cmd_element no_ip_route_flags_cmd__X;
    struct cmd_element neighbor_update_source_cmd__X;
    struct cmd_element show_memory_all_cmd__X;
    struct thread_master * master__X;
    struct cmd_element no_distribute_list_prefix_cmd__X;
    struct cmd_element no_neighbor_interface_cmd__X;
    struct cmd_element no_set_tag_cmd__X;
    int errno__X;
    struct cmd_element no_neighbor_shutdown_cmd__X;
    struct cmd_element set_community_none_cmd__X;
    struct cmd_element interface_cmd__X;
    struct cmd_element distribute_list_prefix_all_cmd__X;
    struct cmd_element neighbor_attr_unchanged6_cmd__X;
    struct cmd_node interface_node__X;
    struct cmd_element no_aggregate_address_as_set_cmd__X;
    struct cmd_element no_linkdetect_cmd__X;
    struct cmd_element no_access_list_all_cmd__X;
    struct cmd_element if_ipv6_rmap_cmd__X;
    struct cmd_element neighbor_attr_unchanged10_cmd__X;
    struct cmd_element aggregate_address_mask_summary_only_cmd__X;
    struct cmd_element no_neighbor_attr_unchanged8_cmd__X;
    struct cmd_element no_aggregate_address_cmd__X;
    struct cmd_element no_neighbor_allowas_in_cmd__X;
    struct cmd_element aggregate_address_mask_as_set_cmd__X;
    struct cmd_element ip_route_mask_flags_distance2_cmd__X;
    struct cmd_element ip_prefix_list_seq_cmd__X;
    struct cmd_element config_log_monitor_cmd__X;
    struct cmd_element no_ip_prefix_list_prefix_cmd__X;
    struct cmd_element no_ipv6_distribute_list_all_cmd__X;
    struct cmd_element set_community_delete_cmd__X;
    struct fifo message_queue__X;
    if_rmap_hook_func if_rmap_delete_hook__X;
    struct cmd_element rmap_continue_seq_cmd__X;
    struct cmd_node enable_node__X;
    struct cmd_element no_neighbor_capability_orf_prefix_cmd__X;
    int re_max_failures__X;
    struct cmd_element ipv6_distribute_list_prefix_all_cmd__X;
    struct cmd_element send_lifetime_day_month_day_month_cmd__X;
    struct cmd_element route_map_cmd__X;
    struct cmd_element aggregate_address_mask_as_set_summary_cmd__X;
    struct cmd_element no_set_local_pref_cmd__X;
    struct cmd_element match_tag_cmd__X;
    struct cmd_element neighbor_remote_as_cmd__X;
    struct cmd_element no_match_ip_address_cmd__X;
    struct cmd_node prefix_node__X;
    struct cmd_element neighbor_filter_list_cmd__X;
    struct cmd_element neighbor_strict_capability_cmd__X;
    struct cmd_element no_neighbor_maximum_prefix_val2_cmd__X;
    struct route_map_rule_cmd route_match_ip_next_hop_prefix_list_cmd__X;
    struct cmd_element show_ip_prefix_list_name_cmd__X;
    struct cmd_element send_lifetime_month_day_day_month_cmd__X;
    struct cmd_element no_aggregate_address_mask_as_set_summary_cmd__X;
    struct cmd_node ip_node__X;
    struct cmd_element accept_lifetime_day_month_month_day_cmd__X;
    struct prefix_master prefix_master_ipv4__X;
    struct cmd_element no_neighbor_advertise_interval_cmd__X;
    struct cmd_element neighbor_soft_reconfiguration_cmd__X;
    struct cmd_element aggregate_address_mask_cmd__X;
    struct cmd_element ip_community_list_expanded_cmd__X;
    int dump_open__X;
    struct cmd_element config_table_cmd__X;
    struct cmd_element match_ip_next_hop_prefix_list_cmd__X;
    struct cmd_element neighbor_attr_unchanged4_cmd__X;
    struct cmd_element neighbor_default_originate_rmap_cmd__X;
    struct cmd_element show_ip_prefix_list_summary_cmd__X;
    struct cmd_element match_ip_address_prefix_list_cmd__X;
    struct cmd_element no_set_ip_nexthop_peer_cmd__X;
    struct cmd_element show_ip_access_list_cmd__X;
    struct cmd_element exit_address_family_cmd__X;
    struct cmd_element no_neighbor_attr_unchanged2_cmd__X;
    struct cmd_element no_match_metric_cmd__X;
    struct cmd_element rmap_continue_cmd__X;
    struct cmd_element set_ip_nexthop_cmd__X;
    struct cmd_element config_log_file_level_cmd__X;
    struct cmd_element linkdetect_cmd__X;
    struct cmd_element no_match_ip_next_hop_val_cmd__X;
    struct cmd_element send_lifetime_month_day_month_day_cmd__X;
    int first_nonopt__X;
    struct route_map_rule_cmd route_match_aspath_cmd__X;
    struct cmd_element access_list_extended_any_any_cmd__X;
    struct cmd_node rmap_node__X;
    struct cmd_element no_neighbor_maximum_prefix_val_cmd__X;
    struct cmd_node community_list_node__X;
    struct cmd_element show_startup_config_cmd__X;
    struct cmd_element no_neighbor_send_community_type_cmd__X;
    struct cmd_element no_ipv6_distribute_list_prefix_all_cmd__X;
    struct cmd_element no_ip_extcommunity_list_name_expanded_cmd__X;
    struct route_map_rule_cmd route_match_ip_nexthop_cmd__X;
    struct cmd_element show_ip_route_prefix_cmd__X;
    struct_zclient * zlookup__X;
    struct cmd_element mpls_te_on_cmd__X;
    int vty_port__X;
    struct cmd_element no_set_vpnv4_nexthop_val_cmd__X;
    struct cmd_element no_service_terminal_length_cmd__X;
    struct cmd_element show_ip_community_list_cmd__X;
    struct cmd_element set_weight_cmd__X;
    struct cmd_element neighbor_version_cmd__X;
    struct cmd_element no_match_tag_val_cmd__X;
    struct cmd_element neighbor_transparent_nexthop_cmd__X;
    struct cmd_element accept_lifetime_duration_month_day_cmd__X;
    struct cmd_element banner_motd_default_cmd__X;
    struct cmd_element no_access_list_exact_cmd__X;
    struct cmd_element neighbor_unsuppress_map_cmd__X;
    struct cmd_element show_version_cmd__X;
    struct cmd_element neighbor_advertise_interval_cmd__X;
    struct cmd_element access_list_cmd__X;
    struct hash * transit_hash__X;
    struct cmd_element neighbor_dont_capability_negotiate_cmd__X;
    struct cmd_element no_match_tag_cmd__X;
    struct cmd_element no_ip_prefix_list_cmd__X;
    struct cmd_element match_peer_local_cmd__X;
    struct cmd_element accept_lifetime_month_day_month_day_cmd__X;
    struct cmd_element no_ip_extcommunity_list_expanded_cmd__X;
    struct cmd_element no_neighbor_activate_cmd__X;
    struct cmd_element access_list_standard_nomask_cmd__X;
    struct cmd_element no_set_community_cmd__X;
    struct cmd_element no_neighbor_passive_cmd__X;
    struct list rid_lo_sorted_list__X;
    struct cmd_element access_list_remark_cmd__X;
    struct hash * cluster_hash__X;
    struct cmd_element address_family_ipv6_cmd__X;
    struct cmd_element no_set_metric_type_cmd__X;
    struct cmd_element no_match_peer_local_cmd__X;
    struct cmd_element ip_route_flags2_cmd__X;
    struct cmd_element ipv6_distribute_list_prefix_cmd__X;
    struct cmd_element no_set_ip_nexthop_val_cmd__X;
    struct cmd_element config_logmsg_cmd__X;
    struct cmd_element no_ip_community_list_standard_cmd__X;
    struct cmd_element send_lifetime_duration_month_day_cmd__X;
    struct cmd_element rmap_call_cmd__X;
    struct cmd_element show_ip_prefix_list_prefix_longer_cmd__X;
    struct cmd_element show_ip_prefix_list_detail_name_cmd__X;
    struct cmd_element match_ip_nexthop_cmd__X;
    int Debug_Event__X;
    struct cmd_element no_match_ecommunity_val_cmd__X;
    struct cmd_element no_set_weight_cmd__X;
    struct cmd_element neighbor_distribute_list_cmd__X;
    struct cmd_element no_match_community_cmd__X;
    struct cmd_element no_set_aggregator_as_cmd__X;
    struct cmd_element enable_password_cmd__X;
    const char * pid_file__X;
    char * vty_accesslist_name__X;
    dist_hook_func distribute_delete_hook__X;
    struct cmd_element ip_prefix_list_seq_ge_cmd__X;
    struct cmd_element no_match_ip_address_prefix_list_val_cmd__X;
    struct cmd_element set_metric_cmd__X;
    struct cmd_element no_ip_as_path_all_cmd__X;
    struct cmd_element no_access_list_extended_cmd__X;
    struct cmd_element match_origin_cmd__X;
    struct cmd_element no_neighbor_timers_connect_cmd__X;
    struct cmd_element set_aspath_prepend_cmd__X;
    struct cmd_element show_memory_lib_cmd__X;
    struct cmd_element no_neighbor_weight_cmd__X;
    pid_t pid__X;
    struct cmd_element accept_lifetime_duration_day_month_cmd__X;
    struct cmd_element distribute_list_all_cmd__X;
    pid_t old_pid__X;
    struct cmd_element no_ip_community_list_cmd__X;
    struct cmd_element no_neighbor_nexthop_self_cmd__X;
    char * config_file__X;
    struct peer_flag_action peer_af_flag_action_list__X[15];
    struct cmd_element ip_prefix_list_seq_le_cmd__X;
    struct cmd_element no_set_ecommunity_rt_val_cmd__X;
    struct cmd_element echo_cmd__X;
    struct route_map_rule_cmd route_match_peer_cmd__X;
    struct cmd_element ip_prefix_list_ge_le_cmd__X;
    struct cmd_element router_id_cmd__X;
    struct cmd_element no_match_interface_val_cmd__X;
    struct cmd_element no_access_list_extended_any_host_cmd__X;
    struct cmd_element no_ip_extcommunity_list_all_cmd__X;
    struct FOO1__S mstat__X[MTYPE_MAX];
    struct cmd_element no_config_log_syslog_cmd__X;
    char * posixly_correct__X;
    struct cmd_element set_community_cmd__X;
    struct cmd_element no_key_chain_cmd__X;
    struct cmd_element no_set_metric_cmd__X;
    struct cmd_element rmap_show_cmd__X;
    char * optarg__X;
    struct cmd_element if_rmap_cmd__X;
    struct cmd_node forwarding_node__X;
    struct cmd_element no_access_list_cmd__X;
    struct_zclient * zclient__X;
    struct cmd_element ip_forwarding_cmd__X;
    struct cmd_element no_neighbor_remove_private_as_cmd__X;
    struct cmd_element neighbor_local_as_no_prepend_cmd__X;
    struct cmd_element aggregate_address_summary_as_set_cmd__X;
    struct cmd_element neighbor_port_cmd__X;
    struct cmd_element mpls_te_link_rsc_clsclr_cmd__X;
    struct cmd_element ip_prefix_list_sequence_number_cmd__X;
    struct cmd_element neighbor_maximum_prefix_warning_cmd__X;
    struct cmd_element no_ip_community_list_name_all_cmd__X;
    struct cmd_element no_match_ip_next_hop_prefix_list_val_cmd__X;
    struct cmd_element config_log_stdout_level_cmd__X;
    struct cmd_element ip_extcommunity_list_standard2_cmd__X;
    struct cmd_element hostname_cmd__X;
    struct cmd_element no_distribute_list_prefix_all_cmd__X;
    struct cmd_element no_match_ip_nexthop_val_cmd__X;
    struct cmd_element password_cmd__X;
    struct cmd_element no_access_list_any_cmd__X;
    struct cmd_element neighbor_remove_private_as_cmd__X;
    struct cmd_element no_set_community_delete_val_cmd__X;
    struct cmd_element neighbor_nexthop_local_unchanged_cmd__X;
    struct cmd_element no_ip_community_list_expanded_cmd__X;
    int no_password_check__X;
    struct cmd_element no_ip_extcommunity_list_standard_cmd__X;
    struct cmd_element config_terminal_no_length_cmd__X;
    struct cmd_element ip_prefix_list_seq_le_ge_cmd__X;
    struct cmd_element match_metric_cmd__X;
    struct cmd_element access_list_extended_mask_any_cmd__X;
    struct cmd_element no_ip_prefix_list_ge_cmd__X;
    struct cmd_element no_neighbor_maximum_prefix_val3_cmd__X;
    struct route_map_rule_cmd route_set_aspath_prepend_cmd__X;
    int keep_kernel_mode__X;
    struct cmd_element neighbor_attr_unchanged8_cmd__X;
    struct cmd_element no_set_origin_cmd__X;
    struct cmd_element ip_route_distance_cmd__X;
    vector vtyvec__X;
    struct cmd_element match_ip_address_cmd__X;
    int dump_keepalive__X;
    struct cmd_element no_aggregate_address_summary_as_set_cmd__X;
    struct cmd_element no_ip_route_mask_flags2_cmd__X;
    struct cmd_element ip_route_mask_flags_distance_cmd__X;
    struct cmd_element terminal_no_monitor_cmd__X;
    struct cmd_element set_aggregator_as_cmd__X;
    struct cmd_element no_ip_route_mask_flags_distance2_cmd__X;
    struct cmd_element no_neighbor_attr_unchanged7_cmd__X;
    struct cmd_element neighbor_attr_unchanged3_cmd__X;
    struct cmd_element no_access_list_standard_nomask_cmd__X;
    struct cmd_element config_log_stdout_cmd__X;
    struct cmd_element access_list_standard_host_cmd__X;
    struct cmd_element no_aggregate_address_mask_summary_only_cmd__X;
    struct cmd_element show_ip_prefix_list_detail_cmd__X;
    struct cmd_element no_neighbor_unsuppress_map_cmd__X;
    struct cmd_element no_ip_prefix_list_seq_le_cmd__X;
    struct cmd_element no_hostname_cmd__X;
    struct cmd_element no_neighbor_route_map_cmd__X;
    struct route_map_rule_cmd route_set_community_delete_cmd__X;
    struct cmd_element config_write_cmd__X;
    struct cmd_element no_shutdown_if_cmd__X;
    struct cmd_node keychain_node__X;
    struct cmd_element set_originator_id_cmd__X;
    struct route_map_rule_cmd route_match_ip_address_cmd__X;
    struct cmd_element no_match_peer_val_cmd__X;
    struct quagga_sigevent_master_t sigmaster__X;
    struct route_map_rule_cmd route_set_origin_cmd__X;
    struct cmd_element rmap_continue_index_cmd__X;
    struct cmd_element ip_prefix_list_le_ge_cmd__X;
    struct cmd_element ip_prefix_list_cmd__X;
    int passive_default__X;
    struct cmd_element neighbor_attr_unchanged9_cmd__X;
    struct cmd_element no_access_list_remark_cmd__X;
    struct cmd_element no_set_ecommunity_soo_val_cmd__X;
    struct cmd_element no_interface_cmd__X;
    struct nlsock netlink__X;
    struct cmd_element no_neighbor_version_cmd__X;
    struct cmd_element no_set_tag_val_cmd__X;
    struct cmd_element neighbor_local_as_cmd__X;
    struct route_map_rule_cmd route_match_origin_cmd__X;
    struct cmd_element set_ecommunity_rt_cmd__X;
    struct cmd_element no_access_list_standard_host_cmd__X;
    struct cmd_element neighbor_transparent_as_cmd__X;
    struct cmd_element exec_timeout_sec_cmd__X;
    struct cmd_element ip_extcommunity_list_expanded_cmd__X;
    struct cmd_element no_ip_prefix_list_le_cmd__X;
    struct cmd_element vty_access_class_cmd__X;
    struct cmd_element ip_prefix_list_seq_ge_le_cmd__X;
    struct cmd_element config_log_file_cmd__X;
    struct cmd_element no_aggregate_address_summary_only_cmd__X;
    struct cmd_element neighbor_capability_orf_prefix_cmd__X;
    struct cmd_element no_neighbor_set_peer_group_cmd__X;
    struct cmd_element aggregate_address_as_set_cmd__X;
    struct cmd_element no_neighbor_peer_group_remote_as_cmd__X;
    struct cmd_element no_ip_prefix_list_seq_ge_cmd__X;
    struct cmd_element ip_route_mask_cmd__X;
    struct cmd_element no_match_metric_val_cmd__X;
    struct cmd_element no_exec_timeout_cmd__X;
    struct cmd_element no_ip_forwarding_cmd__X;
    struct cmd_element no_neighbor_attr_unchanged4_cmd__X;
    int Debug_Keepalive__X;
    struct cmd_element no_set_aspath_prepend_val_cmd__X;
    struct cmd_element config_log_monitor_level_cmd__X;
    struct cmd_element ip_prefix_list_le_cmd__X;
    struct cmd_element match_interface_cmd__X;
    struct hash * ashash__X;
    struct cmd_element show_ip_route_prefix_longer_cmd__X;
    struct cmd_element service_advanced_vty_cmd__X;
    struct cmd_element config_terminal_cmd__X;
    struct cmd_element no_vty_access_class_cmd__X;
    struct cmd_element match_ip_next_hop_cmd__X;
    struct cmd_element config_log_record_priority_cmd__X;
    struct cmd_element show_ip_prefix_list_prefix_cmd__X;
    struct cmd_element key_string_cmd__X;
    struct cmd_element no_aggregate_address_mask_cmd__X;
    struct cmd_element access_list_any_cmd__X;
    struct cmd_element no_match_ip_address_prefix_list_cmd__X;
    struct cmd_element no_access_list_extended_host_mask_cmd__X;
    struct cmd_element no_set_aspath_prepend_cmd__X;
    struct cmd_element ip_extcommunity_list_name_standard2_cmd__X;
    struct cmd_element ip_community_list_standard_cmd__X;
    char telnet_backward_char__X;
    struct cmd_element no_neighbor_advertise_interval_val_cmd__X;
    struct cmd_element no_match_aspath_cmd__X;
    struct cmd_element ip_route_mask_flags2_cmd__X;
    struct cmd_element neighbor_capability_route_refresh_cmd__X;
    struct cmd_element no_rmap_continue_cmd__X;
    struct list * iflist__X;
    struct cmd_element no_neighbor_prefix_list_cmd__X;
    struct cmd_element rmap_show_name_cmd__X;
    struct cmd_element no_neighbor_attr_unchanged1_cmd__X;
    struct cmd_element no_rmap_onmatch_next_cmd__X;
    struct cmd_element ip_route_flags_distance2_cmd__X;
    struct cmd_element show_history_cmd__X;
    struct cmd_element config_terminal_length_cmd__X;
    struct cmd_element mpls_te_link_max_rsv_bw_cmd__X;
    struct cmd_element vty_login_cmd__X;
    struct cmd_element neighbor_prefix_list_cmd__X;
    struct cmd_element no_match_peer_cmd__X;
    vector Vvty_serv_thread__X;
    struct cmd_element ip_address_cmd__X;
    char * vty_addr__X;
    struct cmd_element address_family_ipv4_safi_cmd__X;
    struct cmd_element line_vty_cmd__X;
    struct cmd_element no_interface_desc_cmd__X;
    struct cmd_element no_enable_password_cmd__X;
    struct cmd_element capability_opaque_cmd__X;
    struct prefix rid_user_assigned__X;
    struct nlsock netlink_addr__X;
    struct cmd_node view_node__X;
    struct cmd_element no_neighbor_attr_unchanged3_cmd__X;
    struct cmd_element no_access_list_extended_host_any_cmd__X;
    struct cmd_element neighbor_allowas_in_arg_cmd__X;
    int __getopt_initialized__X;
    int optind__X;
    struct cmd_element no_bandwidth_if_val_cmd__X;
    struct cmd_element send_lifetime_infinite_month_day_cmd__X;
    struct cmd_element no_vpnv4_network_cmd__X;
    struct cmd_element send_lifetime_duration_day_month_cmd__X;
    struct cmd_element no_neighbor_attr_unchanged5_cmd__X;
    struct cmd_element exec_timeout_min_cmd__X;
    struct cmd_element no_key_string_cmd__X;
    struct cmd_element no_ip_community_list_all_cmd__X;
    struct cmd_element show_interface_cmd__X;
    struct cmd_element match_community_exact_cmd__X;
    char * nextchar__X;
    struct hash * attrhash__X;
    struct cmd_element neighbor_route_reflector_client_cmd__X;
    struct route_map_rule_cmd route_set_vpnv4_nexthop_cmd__X;
    struct cmd_element access_list_extended_host_mask_cmd__X;
    struct cmd_element ip_extcommunity_list_standard_cmd__X;
    struct cmd_element no_neighbor_filter_list_cmd__X;
    struct_host host__X;
    struct route_map_rule_cmd route_set_ip_nexthop_cmd__X;
    struct cmd_element no_neighbor_port_val_cmd__X;
    struct cmd_element no_key_cmd__X;
    struct cmd_element show_mpls_te_router_cmd__X;
    struct cmd_element config_who_cmd__X;
    struct cmd_element ip_community_list_name_standard2_cmd__X;
    int optopt__X;
    struct cmd_element ip_extcommunity_list_name_expanded_cmd__X;
    struct route_map_rule_cmd route_set_ecommunity_rt_cmd__X;
    struct cmd_element no_set_ecommunity_rt_cmd__X;
    struct cmd_element no_config_log_file_level_cmd__X;
    struct cmd_element no_match_interface_cmd__X;
    struct cmd_element bandwidth_if_cmd__X;
    struct cmd_element no_neighbor_route_server_client_cmd__X;
    struct cmd_element no_ip_address_label_cmd__X;
    struct cmd_node auth_node__X;
    struct cmd_element no_set_ecommunity_soo_cmd__X;
    struct cmd_element neighbor_maximum_prefix_threshold_warning_cmd__X;
    struct cmd_node debug_node__X;
    struct cmd_element no_ip_route_mask_flags_distance_cmd__X;
    struct route_map_rule_cmd route_set_metric_type_cmd__X;
    struct cmd_element neighbor_peer_group_cmd__X;
    struct cmd_element mpls_te_link_maxbw_cmd__X;
    struct cmd_element address_family_vpnv4_cmd__X;
    struct cmd_element set_metric_addsub_cmd__X;
    u_int vlink_count__X;
    struct cmd_element address_family_vpnv4_unicast_cmd__X;
    struct cmd_element config_write_memory_cmd__X;
    struct cmd_element show_ip_as_path_access_list_all_cmd__X;
    struct cmd_element config_list_cmd__X;
    struct cmd_element no_neighbor_attr_unchanged_cmd__X;
    struct cmd_element ip_route_flags_cmd__X;
    struct cmd_node config_node__X;
    struct cmd_element rmap_onmatch_next_cmd__X;
    struct cmd_element access_list_standard_any_cmd__X;
    struct cmd_element neighbor_override_capability_cmd__X;
    struct cmd_element no_ip_as_path_cmd__X;
    struct cmd_element neighbor_default_originate_cmd__X;
    struct cmd_node vty_node__X;
    struct route_map_rule_cmd route_match_metric_cmd__X;
    int retain_mode__X;
    struct cmd_element no_ip_route_mask_distance_cmd__X;
    struct cmd_element no_set_metric_val_cmd__X;
    struct cmd_element neighbor_activate_cmd__X;
    struct list * keychain_list__X;
    struct cmd_element no_neighbor_enforce_multihop_cmd__X;
    struct cmd_element distribute_list_cmd__X;
    struct cmd_element clear_ip_prefix_list_cmd__X;
    struct cmd_element no_neighbor_route_reflector_client_cmd__X;
    struct cmd_element no_neighbor_port_cmd__X;
    struct cmd_element no_set_community_delete_cmd__X;
    struct zlog * zlog_default__X;
    struct cmd_element neighbor_route_server_client_cmd__X;
    struct cmd_element show_memory_cmd__X;
    struct route_map_rule_cmd route_set_local_pref_cmd__X;
    struct cmd_element mpls_te_router_addr_cmd__X;
    struct cmd_element config_end_cmd__X;
    struct cmd_element no_set_vpnv4_nexthop_cmd__X;
    struct cmd_element no_match_community_exact_cmd__X;
    int dump_update__X;
    struct route_map_list route_map_master__X;
    struct cmd_element ip_community_list_standard2_cmd__X;
    struct cmd_element no_banner_motd_cmd__X;
    struct cmd_element no_distribute_list_cmd__X;
    struct cmd_element no_match_origin_cmd__X;
    struct cmd_element show_ip_route_summary_cmd__X;
    struct cmd_element aggregate_address_cmd__X;
    struct cmd_element no_access_list_extended_mask_any_cmd__X;
    struct cmd_element ipv6_distribute_list_all_cmd__X;
    struct cmd_element no_if_rmap_cmd__X;
    struct list rid_all_sorted_list__X;
    struct cmd_element ip_route_mask_distance_cmd__X;
    struct cmd_element access_list_exact_cmd__X;
    struct cmd_element ip_route_mask_flags_cmd__X;
    struct cmd_element set_atomic_aggregate_cmd__X;
    struct cmd_element config_write_terminal_cmd__X;
    struct cmd_element no_neighbor_soft_reconfiguration_cmd__X;
    struct cmd_element password_text_cmd__X;
    struct cmd_element match_community_cmd__X;
    struct cmd_element no_bandwidth_if_cmd__X;
    struct cmd_element no_set_originator_id_cmd__X;
    struct cmd_element access_list_extended_host_host_cmd__X;
    struct cmd_node table_node__X;
    struct route_map_rule_cmd route_set_originator_id_cmd__X;
    struct cmd_element accept_lifetime_month_day_day_month_cmd__X;
    struct cmd_element aggregate_address_as_set_summary_cmd__X;
    struct cmd_element show_ip_route_supernets_cmd__X;
    struct cmd_element no_ip_prefix_list_ge_le_cmd__X;
    dist_hook_func distribute_add_hook__X;
    vector vrf_vector__X;
    struct cmd_element no_ipv6_distribute_list_prefix_cmd__X;
    struct cmd_element no_config_log_file_cmd__X;
    struct cmd_element no_ip_community_list_name_expanded_cmd__X;
    struct cmd_element multicast_cmd__X;
    if_rmap_hook_func if_rmap_add_hook__X;
    struct cmd_element no_vty_login_cmd__X;
    struct cmd_element config_log_facility_cmd__X;
    struct cmd_element no_neighbor_attr_unchanged6_cmd__X;
    struct cmd_element show_running_config_cmd__X;
    struct cmd_element no_match_ip_next_hop_cmd__X;
    struct route_map_rule_cmd route_set_weight_cmd__X;
    struct cmd_element show_ip_prefix_list_cmd__X;
    struct_as_list_master as_list_master__X;
    struct cmd_element no_neighbor_local_as_val2_cmd__X;
    struct cmd_element enable_password_text_cmd__X;
    struct cmd_element no_match_ip_next_hop_prefix_list_cmd__X;
    struct cmd_element access_list_extended_any_mask_cmd__X;
    struct cmd_element no_set_local_pref_val_cmd__X;
    struct cmd_element access_list_standard_cmd__X;
    struct cmd_element access_list_extended_mask_host_cmd__X;
    struct cmd_element show_ip_access_list_name_cmd__X;
    struct cmd_element neighbor_attr_unchanged1_cmd__X;
    struct cmd_element vpnv4_network_cmd__X;
    struct cmd_element no_access_list_extended_host_host_cmd__X;
    struct cmd_element no_neighbor_peer_group_cmd__X;
    struct cmd_element no_rmap_onmatch_goto_cmd__X;
    struct cmd_element config_log_syslog_cmd__X;
    struct cmd_element no_ip_prefix_list_seq_le_ge_cmd__X;
    struct cmd_element set_ip_nexthop_peer_cmd__X;
    struct cmd_element ip_as_path_cmd__X;
    struct cmd_element neighbor_timers_cmd__X;
    struct route_map_rule_cmd route_match_ip_next_hop_cmd__X;
    struct cmd_element show_ip_prefix_list_summary_name_cmd__X;
    reg_syntax_t re_syntax_options__X;
    struct cmd_element service_terminal_length_cmd__X;
    struct route_map_rule_cmd route_set_aggregator_as_cmd__X;
    struct cmd_element no_multicast_cmd__X;
    struct cmd_element no_neighbor_weight_val_cmd__X;
    struct cmd_element neighbor_set_peer_group_cmd__X;
    struct cmd_element no_service_advanced_vty_cmd__X;
    struct cmd_element match_ecommunity_cmd__X;
    struct thread * t_write__X;
    struct cmd_element no_ip_community_list_name_standard_cmd__X;
    struct cmd_element key_cmd__X;
    struct cmd_element copy_runningconfig_startupconfig_cmd__X;
    struct hash * ecomhash__X;
    struct route_table * ifaddr_ipv4_table__X;
    struct cmd_element no_route_map_cmd__X;
    struct cmd_element no_ip_address_cmd__X;
    struct cmd_element neighbor_send_community_type_cmd__X;
    struct cmd_element neighbor_interface_cmd__X;
    struct cmd_element no_neighbor_send_community_cmd__X;
    struct cmd_element no_neighbor_strict_capability_cmd__X;
    struct cmd_element no_neighbor_update_source_cmd__X;
    struct cmd_element no_config_log_record_priority_cmd__X;
    struct cmd_element ip_community_list_name_standard_cmd__X;
    struct cmd_element no_aggregate_address_as_set_summary_cmd__X;
    struct route_map_rule_cmd route_match_interface_cmd__X;
    struct cmd_element ip_community_list_cmd__X;
    struct cmd_element no_router_id_cmd__X;
    struct cmd_element no_match_ip_address_val_cmd__X;
    struct cmd_element no_neighbor_attr_unchanged10_cmd__X;
    char telnet_space_char__X;
    struct cmd_element neighbor_attr_unchanged_cmd__X;
    struct cmd_element send_lifetime_infinite_day_month_cmd__X;
    struct cmd_element access_list_extended_cmd__X;
    struct cmd_element show_ip_prefix_list_name_seq_cmd__X;
    struct cmd_element no_distribute_list_all_cmd__X;
    struct cmd_element show_ip_extcommunity_list_cmd__X;
    struct route_map_rule_cmd route_match_ip_address_prefix_list_cmd__X;
    struct cmd_element neighbor_passive_cmd__X;
    struct cmd_element neighbor_timers_connect_cmd__X;
    struct cmd_element config_enable_cmd__X;
    struct cmd_element access_list_extended_any_host_cmd__X;
    struct cmd_element clear_ip_prefix_list_name_prefix_cmd__X;
    struct cmd_element no_set_metric_type_val_cmd__X;
    struct prefix_master prefix_master_orf__X;
    struct cmd_element neighbor_shutdown_cmd__X;
    struct cmd_element no_ipv6_distribute_list_cmd__X;
    vector cmdvec__X;
    struct cmd_element mpls_te_link_unrsv_bw_cmd__X;
    struct cmd_element ip_route_flags_distance_cmd__X;
    struct cmd_element no_neighbor_override_capability_cmd__X;
    int zclient_debug__X;
    struct cmd_element neighbor_enforce_multihop_cmd__X;
    struct cmd_element no_neighbor_dont_capability_negotiate_cmd__X;
    struct route_map_rule_cmd route_set_tag_cmd__X;
    struct cmd_element shutdown_if_cmd__X;
    struct cmd_element config_exit_cmd__X;
    struct cmd_element no_set_atomic_aggregate_cmd__X;
    struct cmd_element no_neighbor_default_originate_cmd__X;
    struct cmd_element no_set_ip_nexthop_cmd__X;
    struct cmd_element config_log_trap_cmd__X;
    struct cmd_element ip_route_cmd__X;
    struct route_map_rule_cmd route_set_ecommunity_soo_cmd__X;
    struct hash * disthash__X;
    struct cmd_element no_access_list_extended_any_any_cmd__X;
    struct cmd_element address_family_ipv6_unicast_cmd__X;
    struct cmd_element no_match_community_val_cmd__X;
    struct cmd_element no_ip_prefix_list_seq_ge_le_cmd__X;
    struct cmd_element mpls_te_link_metric_cmd__X;
    struct cmd_element no_neighbor_cmd__X;
    struct cmd_element no_match_ecommunity_cmd__X;
    struct route_map_rule_cmd route_match_community_cmd__X;
    struct cmd_element no_match_aspath_val_cmd__X;
    struct access_master access_master_ipv4__X;
    struct cmd_element no_synchronization_cmd__X;
    struct cmd_element neighbor_capability_dynamic_cmd__X;
    struct cmd_element interface_desc_cmd__X;
    struct cmd_element key_chain_cmd__X;
    struct cmd_element no_aggregate_address_mask_summary_as_set_cmd__X;
    struct cmd_element no_set_originator_id_val_cmd__X;
    struct cmd_element ip_prefix_list_ge_cmd__X;
    struct cmd_node auth_enable_node__X;
    struct cmd_element no_config_log_trap_cmd__X;
    struct cmd_element set_local_pref_cmd__X;
    struct list * apiserver_list__X;
    struct cmd_element no_neighbor_local_as_cmd__X;
    struct cmd_element service_password_encrypt_cmd__X;
    struct cmd_element neighbor_attr_unchanged7_cmd__X;
    struct cmd_element no_access_list_extended_mask_host_cmd__X;
    struct cmd_element no_if_ipv6_rmap_cmd__X;
    vector route_set_vec__X;
    struct_if_master if_master__X;
    char * vty_ipv6_accesslist_name__X;
    struct cmd_element no_auto_summary_cmd__X;
    struct cmd_element neighbor_allowas_in_cmd__X;
    struct cmd_element no_neighbor_capability_dynamic_cmd__X;
    struct cmd_element show_ip_extcommunity_list_arg_cmd__X;
    struct cmd_element no_match_ip_nexthop_cmd__X;
    struct cmd_element ip_community_list_name_expanded_cmd__X;
    struct cmd_element no_access_list_remark_arg_cmd__X;
    struct cmd_element no_config_log_monitor_cmd__X;
    struct cmd_element set_tag_cmd__X;
    struct cmd_element no_ip_prefix_list_le_ge_cmd__X;
    struct cmd_element no_set_community_none_cmd__X;
    struct cmd_element no_set_aggregator_as_val_cmd__X;
    struct list * peer_list__X;
    struct cmd_element set_origin_cmd__X;
    struct cmd_element no_ip_route_mask_cmd__X;
    int last_nonopt__X;
    u_int32_t nl_rcvbufsize__X;
    struct cmd_element show_mpls_te_link_cmd__X;
    struct cmd_element show_ip_as_path_access_list_cmd__X;
    char reg_unset_dummy__X;
    struct cmd_element neighbor_route_map_cmd__X;
    struct cmd_element config_disable_cmd__X;
    struct cmd_element clear_ip_prefix_list_name_cmd__X;
    struct cmd_element no_ip_route_flags2_cmd__X;
    struct cmd_element ip_address_label_cmd__X;
    struct cmd_element no_access_list_standard_cmd__X;
    struct cmd_element no_ip_route_flags_distance2_cmd__X;
    struct hash * comhash__X;
    struct cmd_node keychain_key_node__X;
    struct cmd_element no_aggregate_address_mask_as_set_cmd__X;
    struct cmd_element no_rmap_continue_seq__X;
    struct cmd_element config_write_file_cmd__X;
    struct cmd_element no_config_log_syslog_facility_cmd__X;
    unsigned long vty_timeout_val__X;
    struct cmd_element no_set_weight_val_cmd__X;
    struct cmd_element show_thread_cpu_cmd__X;
    struct hash * ifrmaphash__X;
    struct cmd_element accept_lifetime_infinite_month_day_cmd__X;
    struct cmd_element neighbor_attr_unchanged5_cmd__X;
    struct _zprivs_t zprivs_state__X;
    struct cmd_element show_memory_isis_cmd__X;
    struct cmd_element set_ecommunity_soo_cmd__X;
    struct cmd_element no_access_list_standard_any_cmd__X;
    struct cmd_element no_ip_route_mask_flags_cmd__X;
    struct cmd_element no_neighbor_timers_cmd__X;
    struct cmd_element no_rmap_call_cmd__X;
    struct cmd_element aggregate_address_mask_summary_as_set_cmd__X;
    struct cmd_element no_ip_route_cmd__X;
    struct cmd_element neighbor_attr_unchanged2_cmd__X;
    struct nlsock netlink_cmd__X;
    struct cmd_element show_logging_cmd__X;
    struct cmd_element no_config_log_stdout_cmd__X;
    struct cmd_element address_family_ipv4_cmd__X;
    struct cmd_element show_table_cmd__X;
    struct cmd_element show_ip_forwarding_cmd__X;
    struct cmd_element show_ip_route_protocol_cmd__X;
    struct cmd_element ip_extcommunity_list_name_standard_cmd__X;
    struct cmd_element match_aspath_cmd__X;
    vector route_match_vec__X;
    struct cmd_element show_ip_route_addr_cmd__X;
    struct cmd_element ipv6_distribute_list_cmd__X;
    struct cmd_element match_peer_cmd__X;
    struct cmd_element no_ip_prefix_list_seq_cmd__X;
    struct route_map_rule_cmd route_match_ecommunity_cmd__X;
    struct cmd_element neighbor_weight_cmd__X;
    int Debug_Update__X;
    char * vty_cwd__X;
    struct cmd_element no_neighbor_local_as_val_cmd__X;
    struct cmd_element no_ip_extcommunity_list_name_standard_cmd__X;
    struct cmd_element distribute_list_prefix_cmd__X;
    struct cmd_element neighbor_nexthop_self_cmd__X;
};

#define show_memory_ripng_cmd__VAR  (__activeVars_lib->show_memory_ripng_cmd__X)
#define show_memory_rip_cmd__VAR  (__activeVars_lib->show_memory_rip_cmd__X)
#define show_memory_bgp_cmd__VAR  (__activeVars_lib->show_memory_bgp_cmd__X)
#define show_memory_ospf_cmd__VAR  (__activeVars_lib->show_memory_ospf_cmd__X)
#define show_memory_ospf6_cmd__VAR  (__activeVars_lib->show_memory_ospf6_cmd__X)

#define ip_prefix_list_description_cmd__VAR  (__activeVars_lib->ip_prefix_list_description_cmd__X)
#define no_ip_prefix_list_description_arg_cmd__VAR  (__activeVars_lib->no_ip_prefix_list_description_arg_cmd__X)
#define no_ip_prefix_list_description_cmd__VAR  (__activeVars_lib->no_ip_prefix_list_description_cmd__X)
#define no_neighbor_description_cmd__VAR  (__activeVars_lib->no_neighbor_description_cmd__X)
#define neighbor_description_cmd__VAR  (__activeVars_lib->neighbor_description_cmd__X)
#define no_neighbor_description_val_cmd__VAR  (__activeVars_lib->no_neighbor_description_val_cmd__X)

#define zebra_node__VAR  (__activeVars_lib->zebra_node__X)
#define no_router_zebra_cmd__VAR  (__activeVars_lib->no_router_zebra_cmd__X)
#define router_zebra_cmd__VAR  (__activeVars_lib->router_zebra_cmd__X)
#define router_id_zebra__VAR  (__activeVars_lib->router_id_zebra__X)

#define show_ip_community_list_arg_cmd__VAR  (__activeVars_lib->show_ip_community_list_arg_cmd__X)
#define no_neighbor_distribute_list_cmd__VAR  (__activeVars_lib->no_neighbor_distribute_list_cmd__X)
#define no_neighbor_maximum_prefix_cmd__VAR  (__activeVars_lib->no_neighbor_maximum_prefix_cmd__X)
#define accept_lifetime_day_month_day_month_cmd__VAR  (__activeVars_lib->accept_lifetime_day_month_day_month_cmd__X)
#define no_neighbor_attr_unchanged9_cmd__VAR  (__activeVars_lib->no_neighbor_attr_unchanged9_cmd__X)
#define no_set_community_val_cmd__VAR  (__activeVars_lib->no_set_community_val_cmd__X)
#define config_help_cmd__VAR  (__activeVars_lib->config_help_cmd__X)
#define no_capability_opaque_cmd__VAR  (__activeVars_lib->no_capability_opaque_cmd__X)
#define send_lifetime_day_month_month_day_cmd__VAR  (__activeVars_lib->send_lifetime_day_month_month_day_cmd__X)
#define no_ip_route_distance_cmd__VAR  (__activeVars_lib->no_ip_route_distance_cmd__X)
#define no_match_origin_val_cmd__VAR  (__activeVars_lib->no_match_origin_val_cmd__X)
#define cpu_record__VAR  (__activeVars_lib->cpu_record__X)
#define show_ip_route_cmd__VAR  (__activeVars_lib->show_ip_route_cmd__X)
#define no_service_password_encrypt_cmd__VAR  (__activeVars_lib->no_service_password_encrypt_cmd__X)
#define no_neighbor_default_originate_rmap_cmd__VAR  (__activeVars_lib->no_neighbor_default_originate_rmap_cmd__X)
#define peer_flag_action_list__VAR  (__activeVars_lib->peer_flag_action_list__X)
#define set_metric_type_cmd__VAR  (__activeVars_lib->set_metric_type_cmd__X)
#define no_mpls_te_cmd__VAR  (__activeVars_lib->no_mpls_te_cmd__X)
#define no_neighbor_timers_connect_val_cmd__VAR  (__activeVars_lib->no_neighbor_timers_connect_val_cmd__X)
#define no_access_list_extended_any_mask_cmd__VAR  (__activeVars_lib->no_access_list_extended_any_mask_cmd__X)
#define dump_notify__VAR  (__activeVars_lib->dump_notify__X)
#define vty_config__VAR  (__activeVars_lib->vty_config__X)
#define rmap_onmatch_goto_cmd__VAR  (__activeVars_lib->rmap_onmatch_goto_cmd__X)
#define route_set_metric_cmd__VAR  (__activeVars_lib->route_set_metric_cmd__X)
#define no_neighbor_capability_route_refresh_cmd__VAR  (__activeVars_lib->no_neighbor_capability_route_refresh_cmd__X)
#define config_log_syslog_level_cmd__VAR  (__activeVars_lib->config_log_syslog_level_cmd__X)
#define no_config_log_facility_cmd__VAR  (__activeVars_lib->no_config_log_facility_cmd__X)
#define as_list_node__VAR  (__activeVars_lib->as_list_node__X)
#define aggregate_address_summary_only_cmd__VAR  (__activeVars_lib->aggregate_address_summary_only_cmd__X)
#define no_set_origin_val_cmd__VAR  (__activeVars_lib->no_set_origin_val_cmd__X)
#define route_set_atomic_aggregate_cmd__VAR  (__activeVars_lib->route_set_atomic_aggregate_cmd__X)
#define route_match_tag_cmd__VAR  (__activeVars_lib->route_match_tag_cmd__X)
#define route_set_community_cmd__VAR  (__activeVars_lib->route_set_community_cmd__X)
#define opterr__VAR  (__activeVars_lib->opterr__X)
#define no_ip_extcommunity_list_name_all_cmd__VAR  (__activeVars_lib->no_ip_extcommunity_list_name_all_cmd__X)
#define no_ip_route_flags_distance_cmd__VAR  (__activeVars_lib->no_ip_route_flags_distance_cmd__X)
#define no_neighbor_remote_as_cmd__VAR  (__activeVars_lib->no_neighbor_remote_as_cmd__X)
#define set_vpnv4_nexthop_cmd__VAR  (__activeVars_lib->set_vpnv4_nexthop_cmd__X)
#define Debug_Radix__VAR  (__activeVars_lib->Debug_Radix__X)
#define show_ip_prefix_list_prefix_first_match_cmd__VAR  (__activeVars_lib->show_ip_prefix_list_prefix_first_match_cmd__X)
#define neighbor_send_community_cmd__VAR  (__activeVars_lib->neighbor_send_community_cmd__X)
#define accept_lifetime_infinite_day_month_cmd__VAR  (__activeVars_lib->accept_lifetime_infinite_day_month_cmd__X)
#define mpls_te_cmd__VAR  (__activeVars_lib->mpls_te_cmd__X)
#define show_address_cmd__VAR  (__activeVars_lib->show_address_cmd__X)
#define syslog_fd__VAR  (__activeVars_lib->syslog_fd__X)
#define no_route_map_all_cmd__VAR  (__activeVars_lib->no_route_map_all_cmd__X)
#define config_log_syslog_facility_cmd__VAR  (__activeVars_lib->config_log_syslog_facility_cmd__X)
#define no_ip_prefix_list_sequence_number_cmd__VAR  (__activeVars_lib->no_ip_prefix_list_sequence_number_cmd__X)
#define no_neighbor_nexthop_local_unchanged_cmd__VAR  (__activeVars_lib->no_neighbor_nexthop_local_unchanged_cmd__X)
#define access_node__VAR  (__activeVars_lib->access_node__X)
#define neighbor_maximum_prefix_threshold_cmd__VAR  (__activeVars_lib->neighbor_maximum_prefix_threshold_cmd__X)
#define neighbor_maximum_prefix_cmd__VAR  (__activeVars_lib->neighbor_maximum_prefix_cmd__X)
#define terminal_monitor_cmd__VAR  (__activeVars_lib->terminal_monitor_cmd__X)
#define access_list_extended_host_any_cmd__VAR  (__activeVars_lib->access_list_extended_host_any_cmd__X)
#define config_quit_cmd__VAR  (__activeVars_lib->config_quit_cmd__X)
#define no_ip_route_flags_cmd__VAR  (__activeVars_lib->no_ip_route_flags_cmd__X)
#define neighbor_update_source_cmd__VAR  (__activeVars_lib->neighbor_update_source_cmd__X)
#define show_memory_all_cmd__VAR  (__activeVars_lib->show_memory_all_cmd__X)
#define master__VAR  (__activeVars_lib->master__X)
#define no_distribute_list_prefix_cmd__VAR  (__activeVars_lib->no_distribute_list_prefix_cmd__X)
#define no_neighbor_interface_cmd__VAR  (__activeVars_lib->no_neighbor_interface_cmd__X)
#define no_set_tag_cmd__VAR  (__activeVars_lib->no_set_tag_cmd__X)
#define errno__VAR  (__activeVars_lib->errno__X)
#define no_neighbor_shutdown_cmd__VAR  (__activeVars_lib->no_neighbor_shutdown_cmd__X)
#define set_community_none_cmd__VAR  (__activeVars_lib->set_community_none_cmd__X)
#define interface_cmd__VAR  (__activeVars_lib->interface_cmd__X)
#define distribute_list_prefix_all_cmd__VAR  (__activeVars_lib->distribute_list_prefix_all_cmd__X)
#define neighbor_attr_unchanged6_cmd__VAR  (__activeVars_lib->neighbor_attr_unchanged6_cmd__X)
#define interface_node__VAR  (__activeVars_lib->interface_node__X)
#define no_aggregate_address_as_set_cmd__VAR  (__activeVars_lib->no_aggregate_address_as_set_cmd__X)
#define no_linkdetect_cmd__VAR  (__activeVars_lib->no_linkdetect_cmd__X)
#define no_access_list_all_cmd__VAR  (__activeVars_lib->no_access_list_all_cmd__X)
#define if_ipv6_rmap_cmd__VAR  (__activeVars_lib->if_ipv6_rmap_cmd__X)
#define neighbor_attr_unchanged10_cmd__VAR  (__activeVars_lib->neighbor_attr_unchanged10_cmd__X)
#define aggregate_address_mask_summary_only_cmd__VAR  (__activeVars_lib->aggregate_address_mask_summary_only_cmd__X)
#define no_neighbor_attr_unchanged8_cmd__VAR  (__activeVars_lib->no_neighbor_attr_unchanged8_cmd__X)
#define no_aggregate_address_cmd__VAR  (__activeVars_lib->no_aggregate_address_cmd__X)
#define no_neighbor_allowas_in_cmd__VAR  (__activeVars_lib->no_neighbor_allowas_in_cmd__X)
#define aggregate_address_mask_as_set_cmd__VAR  (__activeVars_lib->aggregate_address_mask_as_set_cmd__X)
#define ip_route_mask_flags_distance2_cmd__VAR  (__activeVars_lib->ip_route_mask_flags_distance2_cmd__X)
#define ip_prefix_list_seq_cmd__VAR  (__activeVars_lib->ip_prefix_list_seq_cmd__X)
#define config_log_monitor_cmd__VAR  (__activeVars_lib->config_log_monitor_cmd__X)
#define no_ip_prefix_list_prefix_cmd__VAR  (__activeVars_lib->no_ip_prefix_list_prefix_cmd__X)
#define no_ipv6_distribute_list_all_cmd__VAR  (__activeVars_lib->no_ipv6_distribute_list_all_cmd__X)
#define set_community_delete_cmd__VAR  (__activeVars_lib->set_community_delete_cmd__X)
#define message_queue__VAR  (__activeVars_lib->message_queue__X)
#define if_rmap_delete_hook__VAR  (__activeVars_lib->if_rmap_delete_hook__X)
#define rmap_continue_seq_cmd__VAR  (__activeVars_lib->rmap_continue_seq_cmd__X)
#define enable_node__VAR  (__activeVars_lib->enable_node__X)
#define no_neighbor_capability_orf_prefix_cmd__VAR  (__activeVars_lib->no_neighbor_capability_orf_prefix_cmd__X)
#define re_max_failures__VAR  (__activeVars_lib->re_max_failures__X)
#define ipv6_distribute_list_prefix_all_cmd__VAR  (__activeVars_lib->ipv6_distribute_list_prefix_all_cmd__X)
#define send_lifetime_day_month_day_month_cmd__VAR  (__activeVars_lib->send_lifetime_day_month_day_month_cmd__X)
#define route_map_cmd__VAR  (__activeVars_lib->route_map_cmd__X)
#define aggregate_address_mask_as_set_summary_cmd__VAR  (__activeVars_lib->aggregate_address_mask_as_set_summary_cmd__X)
#define no_set_local_pref_cmd__VAR  (__activeVars_lib->no_set_local_pref_cmd__X)
#define match_tag_cmd__VAR  (__activeVars_lib->match_tag_cmd__X)
#define neighbor_remote_as_cmd__VAR  (__activeVars_lib->neighbor_remote_as_cmd__X)
#define no_match_ip_address_cmd__VAR  (__activeVars_lib->no_match_ip_address_cmd__X)
#define prefix_node__VAR  (__activeVars_lib->prefix_node__X)
#define neighbor_filter_list_cmd__VAR  (__activeVars_lib->neighbor_filter_list_cmd__X)
#define neighbor_strict_capability_cmd__VAR  (__activeVars_lib->neighbor_strict_capability_cmd__X)
#define no_neighbor_maximum_prefix_val2_cmd__VAR  (__activeVars_lib->no_neighbor_maximum_prefix_val2_cmd__X)
#define route_match_ip_next_hop_prefix_list_cmd__VAR  (__activeVars_lib->route_match_ip_next_hop_prefix_list_cmd__X)
#define show_ip_prefix_list_name_cmd__VAR  (__activeVars_lib->show_ip_prefix_list_name_cmd__X)
#define send_lifetime_month_day_day_month_cmd__VAR  (__activeVars_lib->send_lifetime_month_day_day_month_cmd__X)
#define no_aggregate_address_mask_as_set_summary_cmd__VAR  (__activeVars_lib->no_aggregate_address_mask_as_set_summary_cmd__X)
#define ip_node__VAR  (__activeVars_lib->ip_node__X)
#define accept_lifetime_day_month_month_day_cmd__VAR  (__activeVars_lib->accept_lifetime_day_month_month_day_cmd__X)
#define prefix_master_ipv4__VAR  (__activeVars_lib->prefix_master_ipv4__X)
#define no_neighbor_advertise_interval_cmd__VAR  (__activeVars_lib->no_neighbor_advertise_interval_cmd__X)
#define neighbor_soft_reconfiguration_cmd__VAR  (__activeVars_lib->neighbor_soft_reconfiguration_cmd__X)
#define aggregate_address_mask_cmd__VAR  (__activeVars_lib->aggregate_address_mask_cmd__X)
#define ip_community_list_expanded_cmd__VAR  (__activeVars_lib->ip_community_list_expanded_cmd__X)
#define dump_open__VAR  (__activeVars_lib->dump_open__X)
#define config_table_cmd__VAR  (__activeVars_lib->config_table_cmd__X)
#define match_ip_next_hop_prefix_list_cmd__VAR  (__activeVars_lib->match_ip_next_hop_prefix_list_cmd__X)
#define neighbor_attr_unchanged4_cmd__VAR  (__activeVars_lib->neighbor_attr_unchanged4_cmd__X)
#define neighbor_default_originate_rmap_cmd__VAR  (__activeVars_lib->neighbor_default_originate_rmap_cmd__X)
#define show_ip_prefix_list_summary_cmd__VAR  (__activeVars_lib->show_ip_prefix_list_summary_cmd__X)
#define match_ip_address_prefix_list_cmd__VAR  (__activeVars_lib->match_ip_address_prefix_list_cmd__X)
#define no_set_ip_nexthop_peer_cmd__VAR  (__activeVars_lib->no_set_ip_nexthop_peer_cmd__X)
#define show_ip_access_list_cmd__VAR  (__activeVars_lib->show_ip_access_list_cmd__X)
#define exit_address_family_cmd__VAR  (__activeVars_lib->exit_address_family_cmd__X)
#define no_neighbor_attr_unchanged2_cmd__VAR  (__activeVars_lib->no_neighbor_attr_unchanged2_cmd__X)
#define no_match_metric_cmd__VAR  (__activeVars_lib->no_match_metric_cmd__X)
#define rmap_continue_cmd__VAR  (__activeVars_lib->rmap_continue_cmd__X)
#define set_ip_nexthop_cmd__VAR  (__activeVars_lib->set_ip_nexthop_cmd__X)
#define config_log_file_level_cmd__VAR  (__activeVars_lib->config_log_file_level_cmd__X)
#define linkdetect_cmd__VAR  (__activeVars_lib->linkdetect_cmd__X)
#define no_match_ip_next_hop_val_cmd__VAR  (__activeVars_lib->no_match_ip_next_hop_val_cmd__X)
#define send_lifetime_month_day_month_day_cmd__VAR  (__activeVars_lib->send_lifetime_month_day_month_day_cmd__X)
#define first_nonopt__VAR  (__activeVars_lib->first_nonopt__X)
#define route_match_aspath_cmd__VAR  (__activeVars_lib->route_match_aspath_cmd__X)
#define access_list_extended_any_any_cmd__VAR  (__activeVars_lib->access_list_extended_any_any_cmd__X)
#define rmap_node__VAR  (__activeVars_lib->rmap_node__X)
#define no_neighbor_maximum_prefix_val_cmd__VAR  (__activeVars_lib->no_neighbor_maximum_prefix_val_cmd__X)
#define community_list_node__VAR  (__activeVars_lib->community_list_node__X)
#define show_startup_config_cmd__VAR  (__activeVars_lib->show_startup_config_cmd__X)
#define no_neighbor_send_community_type_cmd__VAR  (__activeVars_lib->no_neighbor_send_community_type_cmd__X)
#define no_ipv6_distribute_list_prefix_all_cmd__VAR  (__activeVars_lib->no_ipv6_distribute_list_prefix_all_cmd__X)
#define no_ip_extcommunity_list_name_expanded_cmd__VAR  (__activeVars_lib->no_ip_extcommunity_list_name_expanded_cmd__X)
#define route_match_ip_nexthop_cmd__VAR  (__activeVars_lib->route_match_ip_nexthop_cmd__X)
#define show_ip_route_prefix_cmd__VAR  (__activeVars_lib->show_ip_route_prefix_cmd__X)
#define zlookup__VAR  (__activeVars_lib->zlookup__X)
#define mpls_te_on_cmd__VAR  (__activeVars_lib->mpls_te_on_cmd__X)
#define vty_port__VAR  (__activeVars_lib->vty_port__X)
#define no_set_vpnv4_nexthop_val_cmd__VAR  (__activeVars_lib->no_set_vpnv4_nexthop_val_cmd__X)
#define no_service_terminal_length_cmd__VAR  (__activeVars_lib->no_service_terminal_length_cmd__X)
#define show_ip_community_list_cmd__VAR  (__activeVars_lib->show_ip_community_list_cmd__X)
#define set_weight_cmd__VAR  (__activeVars_lib->set_weight_cmd__X)
#define neighbor_version_cmd__VAR  (__activeVars_lib->neighbor_version_cmd__X)
#define no_match_tag_val_cmd__VAR  (__activeVars_lib->no_match_tag_val_cmd__X)
#define neighbor_transparent_nexthop_cmd__VAR  (__activeVars_lib->neighbor_transparent_nexthop_cmd__X)
#define accept_lifetime_duration_month_day_cmd__VAR  (__activeVars_lib->accept_lifetime_duration_month_day_cmd__X)
#define banner_motd_default_cmd__VAR  (__activeVars_lib->banner_motd_default_cmd__X)
#define no_access_list_exact_cmd__VAR  (__activeVars_lib->no_access_list_exact_cmd__X)
#define neighbor_unsuppress_map_cmd__VAR  (__activeVars_lib->neighbor_unsuppress_map_cmd__X)
#define show_version_cmd__VAR  (__activeVars_lib->show_version_cmd__X)
#define neighbor_advertise_interval_cmd__VAR  (__activeVars_lib->neighbor_advertise_interval_cmd__X)
#define access_list_cmd__VAR  (__activeVars_lib->access_list_cmd__X)
#define transit_hash__VAR  (__activeVars_lib->transit_hash__X)
#define neighbor_dont_capability_negotiate_cmd__VAR  (__activeVars_lib->neighbor_dont_capability_negotiate_cmd__X)
#define no_match_tag_cmd__VAR  (__activeVars_lib->no_match_tag_cmd__X)
#define no_ip_prefix_list_cmd__VAR  (__activeVars_lib->no_ip_prefix_list_cmd__X)
#define match_peer_local_cmd__VAR  (__activeVars_lib->match_peer_local_cmd__X)
#define accept_lifetime_month_day_month_day_cmd__VAR  (__activeVars_lib->accept_lifetime_month_day_month_day_cmd__X)
#define no_ip_extcommunity_list_expanded_cmd__VAR  (__activeVars_lib->no_ip_extcommunity_list_expanded_cmd__X)
#define no_neighbor_activate_cmd__VAR  (__activeVars_lib->no_neighbor_activate_cmd__X)
#define access_list_standard_nomask_cmd__VAR  (__activeVars_lib->access_list_standard_nomask_cmd__X)
#define no_set_community_cmd__VAR  (__activeVars_lib->no_set_community_cmd__X)
#define no_neighbor_passive_cmd__VAR  (__activeVars_lib->no_neighbor_passive_cmd__X)
#define rid_lo_sorted_list__VAR  (__activeVars_lib->rid_lo_sorted_list__X)
#define access_list_remark_cmd__VAR  (__activeVars_lib->access_list_remark_cmd__X)
#define cluster_hash__VAR  (__activeVars_lib->cluster_hash__X)
#define address_family_ipv6_cmd__VAR  (__activeVars_lib->address_family_ipv6_cmd__X)
#define no_set_metric_type_cmd__VAR  (__activeVars_lib->no_set_metric_type_cmd__X)
#define no_match_peer_local_cmd__VAR  (__activeVars_lib->no_match_peer_local_cmd__X)
#define ip_route_flags2_cmd__VAR  (__activeVars_lib->ip_route_flags2_cmd__X)
#define ipv6_distribute_list_prefix_cmd__VAR  (__activeVars_lib->ipv6_distribute_list_prefix_cmd__X)
#define no_set_ip_nexthop_val_cmd__VAR  (__activeVars_lib->no_set_ip_nexthop_val_cmd__X)
#define config_logmsg_cmd__VAR  (__activeVars_lib->config_logmsg_cmd__X)
#define no_ip_community_list_standard_cmd__VAR  (__activeVars_lib->no_ip_community_list_standard_cmd__X)
#define send_lifetime_duration_month_day_cmd__VAR  (__activeVars_lib->send_lifetime_duration_month_day_cmd__X)
#define rmap_call_cmd__VAR  (__activeVars_lib->rmap_call_cmd__X)
#define show_ip_prefix_list_prefix_longer_cmd__VAR  (__activeVars_lib->show_ip_prefix_list_prefix_longer_cmd__X)
#define show_ip_prefix_list_detail_name_cmd__VAR  (__activeVars_lib->show_ip_prefix_list_detail_name_cmd__X)
#define match_ip_nexthop_cmd__VAR  (__activeVars_lib->match_ip_nexthop_cmd__X)
#define Debug_Event__VAR  (__activeVars_lib->Debug_Event__X)
#define no_match_ecommunity_val_cmd__VAR  (__activeVars_lib->no_match_ecommunity_val_cmd__X)
#define no_set_weight_cmd__VAR  (__activeVars_lib->no_set_weight_cmd__X)
#define neighbor_distribute_list_cmd__VAR  (__activeVars_lib->neighbor_distribute_list_cmd__X)
#define no_match_community_cmd__VAR  (__activeVars_lib->no_match_community_cmd__X)
#define no_set_aggregator_as_cmd__VAR  (__activeVars_lib->no_set_aggregator_as_cmd__X)
#define enable_password_cmd__VAR  (__activeVars_lib->enable_password_cmd__X)
#define pid_file__VAR  (__activeVars_lib->pid_file__X)
#define vty_accesslist_name__VAR  (__activeVars_lib->vty_accesslist_name__X)
#define distribute_delete_hook__VAR  (__activeVars_lib->distribute_delete_hook__X)
#define ip_prefix_list_seq_ge_cmd__VAR  (__activeVars_lib->ip_prefix_list_seq_ge_cmd__X)
#define no_match_ip_address_prefix_list_val_cmd__VAR  (__activeVars_lib->no_match_ip_address_prefix_list_val_cmd__X)
#define set_metric_cmd__VAR  (__activeVars_lib->set_metric_cmd__X)
#define no_ip_as_path_all_cmd__VAR  (__activeVars_lib->no_ip_as_path_all_cmd__X)
#define no_access_list_extended_cmd__VAR  (__activeVars_lib->no_access_list_extended_cmd__X)
#define match_origin_cmd__VAR  (__activeVars_lib->match_origin_cmd__X)
#define no_neighbor_timers_connect_cmd__VAR  (__activeVars_lib->no_neighbor_timers_connect_cmd__X)
#define set_aspath_prepend_cmd__VAR  (__activeVars_lib->set_aspath_prepend_cmd__X)
#define show_memory_lib_cmd__VAR  (__activeVars_lib->show_memory_lib_cmd__X)
#define no_neighbor_weight_cmd__VAR  (__activeVars_lib->no_neighbor_weight_cmd__X)
#define pid__VAR  (__activeVars_lib->pid__X)
#define accept_lifetime_duration_day_month_cmd__VAR  (__activeVars_lib->accept_lifetime_duration_day_month_cmd__X)
#define distribute_list_all_cmd__VAR  (__activeVars_lib->distribute_list_all_cmd__X)
#define old_pid__VAR  (__activeVars_lib->old_pid__X)
#define no_ip_community_list_cmd__VAR  (__activeVars_lib->no_ip_community_list_cmd__X)
#define no_neighbor_nexthop_self_cmd__VAR  (__activeVars_lib->no_neighbor_nexthop_self_cmd__X)
#define config_file__VAR  (__activeVars_lib->config_file__X)
#define peer_af_flag_action_list__VAR  (__activeVars_lib->peer_af_flag_action_list__X)
#define ip_prefix_list_seq_le_cmd__VAR  (__activeVars_lib->ip_prefix_list_seq_le_cmd__X)
#define no_set_ecommunity_rt_val_cmd__VAR  (__activeVars_lib->no_set_ecommunity_rt_val_cmd__X)
#define echo_cmd__VAR  (__activeVars_lib->echo_cmd__X)
#define route_match_peer_cmd__VAR  (__activeVars_lib->route_match_peer_cmd__X)
#define ip_prefix_list_ge_le_cmd__VAR  (__activeVars_lib->ip_prefix_list_ge_le_cmd__X)
#define router_id_cmd__VAR  (__activeVars_lib->router_id_cmd__X)
#define no_match_interface_val_cmd__VAR  (__activeVars_lib->no_match_interface_val_cmd__X)
#define no_access_list_extended_any_host_cmd__VAR  (__activeVars_lib->no_access_list_extended_any_host_cmd__X)
#define no_ip_extcommunity_list_all_cmd__VAR  (__activeVars_lib->no_ip_extcommunity_list_all_cmd__X)
#define mstat__VAR  (__activeVars_lib->mstat__X)
#define no_config_log_syslog_cmd__VAR  (__activeVars_lib->no_config_log_syslog_cmd__X)
#define posixly_correct__VAR  (__activeVars_lib->posixly_correct__X)
#define set_community_cmd__VAR  (__activeVars_lib->set_community_cmd__X)
#define no_key_chain_cmd__VAR  (__activeVars_lib->no_key_chain_cmd__X)
#define no_set_metric_cmd__VAR  (__activeVars_lib->no_set_metric_cmd__X)
#define rmap_show_cmd__VAR  (__activeVars_lib->rmap_show_cmd__X)
#define optarg__VAR  (__activeVars_lib->optarg__X)
#define if_rmap_cmd__VAR  (__activeVars_lib->if_rmap_cmd__X)
#define forwarding_node__VAR  (__activeVars_lib->forwarding_node__X)
#define no_access_list_cmd__VAR  (__activeVars_lib->no_access_list_cmd__X)
#define zclient__VAR  (__activeVars_lib->zclient__X)
#define ip_forwarding_cmd__VAR  (__activeVars_lib->ip_forwarding_cmd__X)
#define no_neighbor_remove_private_as_cmd__VAR  (__activeVars_lib->no_neighbor_remove_private_as_cmd__X)
#define neighbor_local_as_no_prepend_cmd__VAR  (__activeVars_lib->neighbor_local_as_no_prepend_cmd__X)
#define aggregate_address_summary_as_set_cmd__VAR  (__activeVars_lib->aggregate_address_summary_as_set_cmd__X)
#define neighbor_port_cmd__VAR  (__activeVars_lib->neighbor_port_cmd__X)
#define mpls_te_link_rsc_clsclr_cmd__VAR  (__activeVars_lib->mpls_te_link_rsc_clsclr_cmd__X)
#define ip_prefix_list_sequence_number_cmd__VAR  (__activeVars_lib->ip_prefix_list_sequence_number_cmd__X)
#define neighbor_maximum_prefix_warning_cmd__VAR  (__activeVars_lib->neighbor_maximum_prefix_warning_cmd__X)
#define no_ip_community_list_name_all_cmd__VAR  (__activeVars_lib->no_ip_community_list_name_all_cmd__X)
#define no_match_ip_next_hop_prefix_list_val_cmd__VAR  (__activeVars_lib->no_match_ip_next_hop_prefix_list_val_cmd__X)
#define config_log_stdout_level_cmd__VAR  (__activeVars_lib->config_log_stdout_level_cmd__X)
#define ip_extcommunity_list_standard2_cmd__VAR  (__activeVars_lib->ip_extcommunity_list_standard2_cmd__X)
#define hostname_cmd__VAR  (__activeVars_lib->hostname_cmd__X)
#define no_distribute_list_prefix_all_cmd__VAR  (__activeVars_lib->no_distribute_list_prefix_all_cmd__X)
#define no_match_ip_nexthop_val_cmd__VAR  (__activeVars_lib->no_match_ip_nexthop_val_cmd__X)
#define password_cmd__VAR  (__activeVars_lib->password_cmd__X)
#define no_access_list_any_cmd__VAR  (__activeVars_lib->no_access_list_any_cmd__X)
#define neighbor_remove_private_as_cmd__VAR  (__activeVars_lib->neighbor_remove_private_as_cmd__X)
#define no_set_community_delete_val_cmd__VAR  (__activeVars_lib->no_set_community_delete_val_cmd__X)
#define neighbor_nexthop_local_unchanged_cmd__VAR  (__activeVars_lib->neighbor_nexthop_local_unchanged_cmd__X)
#define no_ip_community_list_expanded_cmd__VAR  (__activeVars_lib->no_ip_community_list_expanded_cmd__X)
#define no_password_check__VAR  (__activeVars_lib->no_password_check__X)
#define no_ip_extcommunity_list_standard_cmd__VAR  (__activeVars_lib->no_ip_extcommunity_list_standard_cmd__X)
#define config_terminal_no_length_cmd__VAR  (__activeVars_lib->config_terminal_no_length_cmd__X)
#define ip_prefix_list_seq_le_ge_cmd__VAR  (__activeVars_lib->ip_prefix_list_seq_le_ge_cmd__X)
#define match_metric_cmd__VAR  (__activeVars_lib->match_metric_cmd__X)
#define access_list_extended_mask_any_cmd__VAR  (__activeVars_lib->access_list_extended_mask_any_cmd__X)
#define no_ip_prefix_list_ge_cmd__VAR  (__activeVars_lib->no_ip_prefix_list_ge_cmd__X)
#define no_neighbor_maximum_prefix_val3_cmd__VAR  (__activeVars_lib->no_neighbor_maximum_prefix_val3_cmd__X)
#define route_set_aspath_prepend_cmd__VAR  (__activeVars_lib->route_set_aspath_prepend_cmd__X)
#define keep_kernel_mode__VAR  (__activeVars_lib->keep_kernel_mode__X)
#define neighbor_attr_unchanged8_cmd__VAR  (__activeVars_lib->neighbor_attr_unchanged8_cmd__X)
#define no_set_origin_cmd__VAR  (__activeVars_lib->no_set_origin_cmd__X)
#define ip_route_distance_cmd__VAR  (__activeVars_lib->ip_route_distance_cmd__X)
#define vtyvec__VAR  (__activeVars_lib->vtyvec__X)
#define match_ip_address_cmd__VAR  (__activeVars_lib->match_ip_address_cmd__X)
#define dump_keepalive__VAR  (__activeVars_lib->dump_keepalive__X)
#define no_aggregate_address_summary_as_set_cmd__VAR  (__activeVars_lib->no_aggregate_address_summary_as_set_cmd__X)
#define no_ip_route_mask_flags2_cmd__VAR  (__activeVars_lib->no_ip_route_mask_flags2_cmd__X)
#define ip_route_mask_flags_distance_cmd__VAR  (__activeVars_lib->ip_route_mask_flags_distance_cmd__X)
#define terminal_no_monitor_cmd__VAR  (__activeVars_lib->terminal_no_monitor_cmd__X)
#define set_aggregator_as_cmd__VAR  (__activeVars_lib->set_aggregator_as_cmd__X)
#define no_ip_route_mask_flags_distance2_cmd__VAR  (__activeVars_lib->no_ip_route_mask_flags_distance2_cmd__X)
#define no_neighbor_attr_unchanged7_cmd__VAR  (__activeVars_lib->no_neighbor_attr_unchanged7_cmd__X)
#define neighbor_attr_unchanged3_cmd__VAR  (__activeVars_lib->neighbor_attr_unchanged3_cmd__X)
#define no_access_list_standard_nomask_cmd__VAR  (__activeVars_lib->no_access_list_standard_nomask_cmd__X)
#define config_log_stdout_cmd__VAR  (__activeVars_lib->config_log_stdout_cmd__X)
#define access_list_standard_host_cmd__VAR  (__activeVars_lib->access_list_standard_host_cmd__X)
#define no_aggregate_address_mask_summary_only_cmd__VAR  (__activeVars_lib->no_aggregate_address_mask_summary_only_cmd__X)
#define show_ip_prefix_list_detail_cmd__VAR  (__activeVars_lib->show_ip_prefix_list_detail_cmd__X)
#define no_neighbor_unsuppress_map_cmd__VAR  (__activeVars_lib->no_neighbor_unsuppress_map_cmd__X)
#define no_ip_prefix_list_seq_le_cmd__VAR  (__activeVars_lib->no_ip_prefix_list_seq_le_cmd__X)
#define no_hostname_cmd__VAR  (__activeVars_lib->no_hostname_cmd__X)
#define no_neighbor_route_map_cmd__VAR  (__activeVars_lib->no_neighbor_route_map_cmd__X)
#define route_set_community_delete_cmd__VAR  (__activeVars_lib->route_set_community_delete_cmd__X)
#define config_write_cmd__VAR  (__activeVars_lib->config_write_cmd__X)
#define no_shutdown_if_cmd__VAR  (__activeVars_lib->no_shutdown_if_cmd__X)
#define keychain_node__VAR  (__activeVars_lib->keychain_node__X)
#define set_originator_id_cmd__VAR  (__activeVars_lib->set_originator_id_cmd__X)
#define route_match_ip_address_cmd__VAR  (__activeVars_lib->route_match_ip_address_cmd__X)
#define no_match_peer_val_cmd__VAR  (__activeVars_lib->no_match_peer_val_cmd__X)
#define sigmaster__VAR  (__activeVars_lib->sigmaster__X)
#define route_set_origin_cmd__VAR  (__activeVars_lib->route_set_origin_cmd__X)
#define rmap_continue_index_cmd__VAR  (__activeVars_lib->rmap_continue_index_cmd__X)
#define ip_prefix_list_le_ge_cmd__VAR  (__activeVars_lib->ip_prefix_list_le_ge_cmd__X)
#define ip_prefix_list_cmd__VAR  (__activeVars_lib->ip_prefix_list_cmd__X)
#define passive_default__VAR  (__activeVars_lib->passive_default__X)
#define neighbor_attr_unchanged9_cmd__VAR  (__activeVars_lib->neighbor_attr_unchanged9_cmd__X)
#define no_access_list_remark_cmd__VAR  (__activeVars_lib->no_access_list_remark_cmd__X)
#define no_set_ecommunity_soo_val_cmd__VAR  (__activeVars_lib->no_set_ecommunity_soo_val_cmd__X)
#define no_interface_cmd__VAR  (__activeVars_lib->no_interface_cmd__X)
#define netlink__VAR  (__activeVars_lib->netlink__X)
#define no_neighbor_version_cmd__VAR  (__activeVars_lib->no_neighbor_version_cmd__X)
#define no_set_tag_val_cmd__VAR  (__activeVars_lib->no_set_tag_val_cmd__X)
#define neighbor_local_as_cmd__VAR  (__activeVars_lib->neighbor_local_as_cmd__X)
#define route_match_origin_cmd__VAR  (__activeVars_lib->route_match_origin_cmd__X)
#define set_ecommunity_rt_cmd__VAR  (__activeVars_lib->set_ecommunity_rt_cmd__X)
#define no_access_list_standard_host_cmd__VAR  (__activeVars_lib->no_access_list_standard_host_cmd__X)
#define neighbor_transparent_as_cmd__VAR  (__activeVars_lib->neighbor_transparent_as_cmd__X)
#define exec_timeout_sec_cmd__VAR  (__activeVars_lib->exec_timeout_sec_cmd__X)
#define ip_extcommunity_list_expanded_cmd__VAR  (__activeVars_lib->ip_extcommunity_list_expanded_cmd__X)
#define no_ip_prefix_list_le_cmd__VAR  (__activeVars_lib->no_ip_prefix_list_le_cmd__X)
#define vty_access_class_cmd__VAR  (__activeVars_lib->vty_access_class_cmd__X)
#define ip_prefix_list_seq_ge_le_cmd__VAR  (__activeVars_lib->ip_prefix_list_seq_ge_le_cmd__X)
#define config_log_file_cmd__VAR  (__activeVars_lib->config_log_file_cmd__X)
#define no_aggregate_address_summary_only_cmd__VAR  (__activeVars_lib->no_aggregate_address_summary_only_cmd__X)
#define neighbor_capability_orf_prefix_cmd__VAR  (__activeVars_lib->neighbor_capability_orf_prefix_cmd__X)
#define no_neighbor_set_peer_group_cmd__VAR  (__activeVars_lib->no_neighbor_set_peer_group_cmd__X)
#define aggregate_address_as_set_cmd__VAR  (__activeVars_lib->aggregate_address_as_set_cmd__X)
#define no_neighbor_peer_group_remote_as_cmd__VAR  (__activeVars_lib->no_neighbor_peer_group_remote_as_cmd__X)
#define no_ip_prefix_list_seq_ge_cmd__VAR  (__activeVars_lib->no_ip_prefix_list_seq_ge_cmd__X)
#define ip_route_mask_cmd__VAR  (__activeVars_lib->ip_route_mask_cmd__X)
#define no_match_metric_val_cmd__VAR  (__activeVars_lib->no_match_metric_val_cmd__X)
#define no_exec_timeout_cmd__VAR  (__activeVars_lib->no_exec_timeout_cmd__X)
#define no_ip_forwarding_cmd__VAR  (__activeVars_lib->no_ip_forwarding_cmd__X)
#define no_neighbor_attr_unchanged4_cmd__VAR  (__activeVars_lib->no_neighbor_attr_unchanged4_cmd__X)
#define Debug_Keepalive__VAR  (__activeVars_lib->Debug_Keepalive__X)
#define no_set_aspath_prepend_val_cmd__VAR  (__activeVars_lib->no_set_aspath_prepend_val_cmd__X)
#define config_log_monitor_level_cmd__VAR  (__activeVars_lib->config_log_monitor_level_cmd__X)
#define ip_prefix_list_le_cmd__VAR  (__activeVars_lib->ip_prefix_list_le_cmd__X)
#define match_interface_cmd__VAR  (__activeVars_lib->match_interface_cmd__X)
#define ashash__VAR  (__activeVars_lib->ashash__X)
#define show_ip_route_prefix_longer_cmd__VAR  (__activeVars_lib->show_ip_route_prefix_longer_cmd__X)
#define service_advanced_vty_cmd__VAR  (__activeVars_lib->service_advanced_vty_cmd__X)
#define config_terminal_cmd__VAR  (__activeVars_lib->config_terminal_cmd__X)
#define no_vty_access_class_cmd__VAR  (__activeVars_lib->no_vty_access_class_cmd__X)
#define match_ip_next_hop_cmd__VAR  (__activeVars_lib->match_ip_next_hop_cmd__X)
#define config_log_record_priority_cmd__VAR  (__activeVars_lib->config_log_record_priority_cmd__X)
#define show_ip_prefix_list_prefix_cmd__VAR  (__activeVars_lib->show_ip_prefix_list_prefix_cmd__X)
#define key_string_cmd__VAR  (__activeVars_lib->key_string_cmd__X)
#define no_aggregate_address_mask_cmd__VAR  (__activeVars_lib->no_aggregate_address_mask_cmd__X)
#define access_list_any_cmd__VAR  (__activeVars_lib->access_list_any_cmd__X)
#define no_match_ip_address_prefix_list_cmd__VAR  (__activeVars_lib->no_match_ip_address_prefix_list_cmd__X)
#define no_access_list_extended_host_mask_cmd__VAR  (__activeVars_lib->no_access_list_extended_host_mask_cmd__X)
#define no_set_aspath_prepend_cmd__VAR  (__activeVars_lib->no_set_aspath_prepend_cmd__X)
#define ip_extcommunity_list_name_standard2_cmd__VAR  (__activeVars_lib->ip_extcommunity_list_name_standard2_cmd__X)
#define ip_community_list_standard_cmd__VAR  (__activeVars_lib->ip_community_list_standard_cmd__X)
#define telnet_backward_char__VAR  (__activeVars_lib->telnet_backward_char__X)
#define no_neighbor_advertise_interval_val_cmd__VAR  (__activeVars_lib->no_neighbor_advertise_interval_val_cmd__X)
#define no_match_aspath_cmd__VAR  (__activeVars_lib->no_match_aspath_cmd__X)
#define ip_route_mask_flags2_cmd__VAR  (__activeVars_lib->ip_route_mask_flags2_cmd__X)
#define neighbor_capability_route_refresh_cmd__VAR  (__activeVars_lib->neighbor_capability_route_refresh_cmd__X)
#define no_rmap_continue_cmd__VAR  (__activeVars_lib->no_rmap_continue_cmd__X)
#define iflist__VAR  (__activeVars_lib->iflist__X)
#define no_neighbor_prefix_list_cmd__VAR  (__activeVars_lib->no_neighbor_prefix_list_cmd__X)
#define rmap_show_name_cmd__VAR  (__activeVars_lib->rmap_show_name_cmd__X)
#define no_neighbor_attr_unchanged1_cmd__VAR  (__activeVars_lib->no_neighbor_attr_unchanged1_cmd__X)
#define no_rmap_onmatch_next_cmd__VAR  (__activeVars_lib->no_rmap_onmatch_next_cmd__X)
#define ip_route_flags_distance2_cmd__VAR  (__activeVars_lib->ip_route_flags_distance2_cmd__X)
#define show_history_cmd__VAR  (__activeVars_lib->show_history_cmd__X)
#define config_terminal_length_cmd__VAR  (__activeVars_lib->config_terminal_length_cmd__X)
#define mpls_te_link_max_rsv_bw_cmd__VAR  (__activeVars_lib->mpls_te_link_max_rsv_bw_cmd__X)
#define vty_login_cmd__VAR  (__activeVars_lib->vty_login_cmd__X)
#define neighbor_prefix_list_cmd__VAR  (__activeVars_lib->neighbor_prefix_list_cmd__X)
#define no_match_peer_cmd__VAR  (__activeVars_lib->no_match_peer_cmd__X)
#define Vvty_serv_thread__VAR  (__activeVars_lib->Vvty_serv_thread__X)
#define ip_address_cmd__VAR  (__activeVars_lib->ip_address_cmd__X)
#define vty_addr__VAR  (__activeVars_lib->vty_addr__X)
#define address_family_ipv4_safi_cmd__VAR  (__activeVars_lib->address_family_ipv4_safi_cmd__X)
#define line_vty_cmd__VAR  (__activeVars_lib->line_vty_cmd__X)
#define no_interface_desc_cmd__VAR  (__activeVars_lib->no_interface_desc_cmd__X)
#define no_enable_password_cmd__VAR  (__activeVars_lib->no_enable_password_cmd__X)
#define capability_opaque_cmd__VAR  (__activeVars_lib->capability_opaque_cmd__X)
#define rid_user_assigned__VAR  (__activeVars_lib->rid_user_assigned__X)
#define netlink_addr__VAR  (__activeVars_lib->netlink_addr__X)
#define view_node__VAR  (__activeVars_lib->view_node__X)
#define no_neighbor_attr_unchanged3_cmd__VAR  (__activeVars_lib->no_neighbor_attr_unchanged3_cmd__X)
#define no_access_list_extended_host_any_cmd__VAR  (__activeVars_lib->no_access_list_extended_host_any_cmd__X)
#define neighbor_allowas_in_arg_cmd__VAR  (__activeVars_lib->neighbor_allowas_in_arg_cmd__X)
#define __getopt_initialized__VAR  (__activeVars_lib->__getopt_initialized__X)
#define optind__VAR  (__activeVars_lib->optind__X)
#define no_bandwidth_if_val_cmd__VAR  (__activeVars_lib->no_bandwidth_if_val_cmd__X)
#define send_lifetime_infinite_month_day_cmd__VAR  (__activeVars_lib->send_lifetime_infinite_month_day_cmd__X)
#define no_vpnv4_network_cmd__VAR  (__activeVars_lib->no_vpnv4_network_cmd__X)
#define send_lifetime_duration_day_month_cmd__VAR  (__activeVars_lib->send_lifetime_duration_day_month_cmd__X)
#define no_neighbor_attr_unchanged5_cmd__VAR  (__activeVars_lib->no_neighbor_attr_unchanged5_cmd__X)
#define exec_timeout_min_cmd__VAR  (__activeVars_lib->exec_timeout_min_cmd__X)
#define no_key_string_cmd__VAR  (__activeVars_lib->no_key_string_cmd__X)
#define no_ip_community_list_all_cmd__VAR  (__activeVars_lib->no_ip_community_list_all_cmd__X)
#define show_interface_cmd__VAR  (__activeVars_lib->show_interface_cmd__X)
#define match_community_exact_cmd__VAR  (__activeVars_lib->match_community_exact_cmd__X)
#define nextchar__VAR  (__activeVars_lib->nextchar__X)
#define attrhash__VAR  (__activeVars_lib->attrhash__X)
#define neighbor_route_reflector_client_cmd__VAR  (__activeVars_lib->neighbor_route_reflector_client_cmd__X)
#define route_set_vpnv4_nexthop_cmd__VAR  (__activeVars_lib->route_set_vpnv4_nexthop_cmd__X)
#define access_list_extended_host_mask_cmd__VAR  (__activeVars_lib->access_list_extended_host_mask_cmd__X)
#define ip_extcommunity_list_standard_cmd__VAR  (__activeVars_lib->ip_extcommunity_list_standard_cmd__X)
#define no_neighbor_filter_list_cmd__VAR  (__activeVars_lib->no_neighbor_filter_list_cmd__X)
#define host__VAR  (__activeVars_lib->host__X)
#define route_set_ip_nexthop_cmd__VAR  (__activeVars_lib->route_set_ip_nexthop_cmd__X)
#define no_neighbor_port_val_cmd__VAR  (__activeVars_lib->no_neighbor_port_val_cmd__X)
#define no_key_cmd__VAR  (__activeVars_lib->no_key_cmd__X)
#define show_mpls_te_router_cmd__VAR  (__activeVars_lib->show_mpls_te_router_cmd__X)
#define config_who_cmd__VAR  (__activeVars_lib->config_who_cmd__X)
#define ip_community_list_name_standard2_cmd__VAR  (__activeVars_lib->ip_community_list_name_standard2_cmd__X)
#define optopt__VAR  (__activeVars_lib->optopt__X)
#define ip_extcommunity_list_name_expanded_cmd__VAR  (__activeVars_lib->ip_extcommunity_list_name_expanded_cmd__X)
#define route_set_ecommunity_rt_cmd__VAR  (__activeVars_lib->route_set_ecommunity_rt_cmd__X)
#define no_set_ecommunity_rt_cmd__VAR  (__activeVars_lib->no_set_ecommunity_rt_cmd__X)
#define no_config_log_file_level_cmd__VAR  (__activeVars_lib->no_config_log_file_level_cmd__X)
#define no_match_interface_cmd__VAR  (__activeVars_lib->no_match_interface_cmd__X)
#define bandwidth_if_cmd__VAR  (__activeVars_lib->bandwidth_if_cmd__X)
#define no_neighbor_route_server_client_cmd__VAR  (__activeVars_lib->no_neighbor_route_server_client_cmd__X)
#define no_ip_address_label_cmd__VAR  (__activeVars_lib->no_ip_address_label_cmd__X)
#define auth_node__VAR  (__activeVars_lib->auth_node__X)
#define no_set_ecommunity_soo_cmd__VAR  (__activeVars_lib->no_set_ecommunity_soo_cmd__X)
#define neighbor_maximum_prefix_threshold_warning_cmd__VAR  (__activeVars_lib->neighbor_maximum_prefix_threshold_warning_cmd__X)
#define debug_node__VAR  (__activeVars_lib->debug_node__X)
#define no_ip_route_mask_flags_distance_cmd__VAR  (__activeVars_lib->no_ip_route_mask_flags_distance_cmd__X)
#define route_set_metric_type_cmd__VAR  (__activeVars_lib->route_set_metric_type_cmd__X)
#define neighbor_peer_group_cmd__VAR  (__activeVars_lib->neighbor_peer_group_cmd__X)
#define mpls_te_link_maxbw_cmd__VAR  (__activeVars_lib->mpls_te_link_maxbw_cmd__X)
#define address_family_vpnv4_cmd__VAR  (__activeVars_lib->address_family_vpnv4_cmd__X)
#define set_metric_addsub_cmd__VAR  (__activeVars_lib->set_metric_addsub_cmd__X)
#define vlink_count__VAR  (__activeVars_lib->vlink_count__X)
#define address_family_vpnv4_unicast_cmd__VAR  (__activeVars_lib->address_family_vpnv4_unicast_cmd__X)
#define config_write_memory_cmd__VAR  (__activeVars_lib->config_write_memory_cmd__X)
#define show_ip_as_path_access_list_all_cmd__VAR  (__activeVars_lib->show_ip_as_path_access_list_all_cmd__X)
#define config_list_cmd__VAR  (__activeVars_lib->config_list_cmd__X)
#define no_neighbor_attr_unchanged_cmd__VAR  (__activeVars_lib->no_neighbor_attr_unchanged_cmd__X)
#define ip_route_flags_cmd__VAR  (__activeVars_lib->ip_route_flags_cmd__X)
#define config_node__VAR  (__activeVars_lib->config_node__X)
#define rmap_onmatch_next_cmd__VAR  (__activeVars_lib->rmap_onmatch_next_cmd__X)
#define access_list_standard_any_cmd__VAR  (__activeVars_lib->access_list_standard_any_cmd__X)
#define neighbor_override_capability_cmd__VAR  (__activeVars_lib->neighbor_override_capability_cmd__X)
#define no_ip_as_path_cmd__VAR  (__activeVars_lib->no_ip_as_path_cmd__X)
#define neighbor_default_originate_cmd__VAR  (__activeVars_lib->neighbor_default_originate_cmd__X)
#define vty_node__VAR  (__activeVars_lib->vty_node__X)
#define route_match_metric_cmd__VAR  (__activeVars_lib->route_match_metric_cmd__X)
#define retain_mode__VAR  (__activeVars_lib->retain_mode__X)
#define no_ip_route_mask_distance_cmd__VAR  (__activeVars_lib->no_ip_route_mask_distance_cmd__X)
#define no_set_metric_val_cmd__VAR  (__activeVars_lib->no_set_metric_val_cmd__X)
#define neighbor_activate_cmd__VAR  (__activeVars_lib->neighbor_activate_cmd__X)
#define keychain_list__VAR  (__activeVars_lib->keychain_list__X)
#define no_neighbor_enforce_multihop_cmd__VAR  (__activeVars_lib->no_neighbor_enforce_multihop_cmd__X)
#define distribute_list_cmd__VAR  (__activeVars_lib->distribute_list_cmd__X)
#define clear_ip_prefix_list_cmd__VAR  (__activeVars_lib->clear_ip_prefix_list_cmd__X)
#define no_neighbor_route_reflector_client_cmd__VAR  (__activeVars_lib->no_neighbor_route_reflector_client_cmd__X)
#define no_neighbor_port_cmd__VAR  (__activeVars_lib->no_neighbor_port_cmd__X)
#define no_set_community_delete_cmd__VAR  (__activeVars_lib->no_set_community_delete_cmd__X)
#define zlog_default__VAR  (__activeVars_lib->zlog_default__X)
#define neighbor_route_server_client_cmd__VAR  (__activeVars_lib->neighbor_route_server_client_cmd__X)
#define show_memory_cmd__VAR  (__activeVars_lib->show_memory_cmd__X)
#define route_set_local_pref_cmd__VAR  (__activeVars_lib->route_set_local_pref_cmd__X)
#define mpls_te_router_addr_cmd__VAR  (__activeVars_lib->mpls_te_router_addr_cmd__X)
#define config_end_cmd__VAR  (__activeVars_lib->config_end_cmd__X)
#define no_set_vpnv4_nexthop_cmd__VAR  (__activeVars_lib->no_set_vpnv4_nexthop_cmd__X)
#define no_match_community_exact_cmd__VAR  (__activeVars_lib->no_match_community_exact_cmd__X)
#define dump_update__VAR  (__activeVars_lib->dump_update__X)
#define route_map_master__VAR  (__activeVars_lib->route_map_master__X)
#define ip_community_list_standard2_cmd__VAR  (__activeVars_lib->ip_community_list_standard2_cmd__X)
#define no_banner_motd_cmd__VAR  (__activeVars_lib->no_banner_motd_cmd__X)
#define no_distribute_list_cmd__VAR  (__activeVars_lib->no_distribute_list_cmd__X)
#define no_match_origin_cmd__VAR  (__activeVars_lib->no_match_origin_cmd__X)
#define show_ip_route_summary_cmd__VAR  (__activeVars_lib->show_ip_route_summary_cmd__X)
#define aggregate_address_cmd__VAR  (__activeVars_lib->aggregate_address_cmd__X)
#define no_access_list_extended_mask_any_cmd__VAR  (__activeVars_lib->no_access_list_extended_mask_any_cmd__X)
#define ipv6_distribute_list_all_cmd__VAR  (__activeVars_lib->ipv6_distribute_list_all_cmd__X)
#define no_if_rmap_cmd__VAR  (__activeVars_lib->no_if_rmap_cmd__X)
#define rid_all_sorted_list__VAR  (__activeVars_lib->rid_all_sorted_list__X)
#define ip_route_mask_distance_cmd__VAR  (__activeVars_lib->ip_route_mask_distance_cmd__X)
#define access_list_exact_cmd__VAR  (__activeVars_lib->access_list_exact_cmd__X)
#define ip_route_mask_flags_cmd__VAR  (__activeVars_lib->ip_route_mask_flags_cmd__X)
#define set_atomic_aggregate_cmd__VAR  (__activeVars_lib->set_atomic_aggregate_cmd__X)
#define config_write_terminal_cmd__VAR  (__activeVars_lib->config_write_terminal_cmd__X)
#define no_neighbor_soft_reconfiguration_cmd__VAR  (__activeVars_lib->no_neighbor_soft_reconfiguration_cmd__X)
#define password_text_cmd__VAR  (__activeVars_lib->password_text_cmd__X)
#define match_community_cmd__VAR  (__activeVars_lib->match_community_cmd__X)
#define no_bandwidth_if_cmd__VAR  (__activeVars_lib->no_bandwidth_if_cmd__X)
#define no_set_originator_id_cmd__VAR  (__activeVars_lib->no_set_originator_id_cmd__X)
#define access_list_extended_host_host_cmd__VAR  (__activeVars_lib->access_list_extended_host_host_cmd__X)
#define table_node__VAR  (__activeVars_lib->table_node__X)
#define route_set_originator_id_cmd__VAR  (__activeVars_lib->route_set_originator_id_cmd__X)
#define accept_lifetime_month_day_day_month_cmd__VAR  (__activeVars_lib->accept_lifetime_month_day_day_month_cmd__X)
#define aggregate_address_as_set_summary_cmd__VAR  (__activeVars_lib->aggregate_address_as_set_summary_cmd__X)
#define show_ip_route_supernets_cmd__VAR  (__activeVars_lib->show_ip_route_supernets_cmd__X)
#define no_ip_prefix_list_ge_le_cmd__VAR  (__activeVars_lib->no_ip_prefix_list_ge_le_cmd__X)
#define distribute_add_hook__VAR  (__activeVars_lib->distribute_add_hook__X)
#define vrf_vector__VAR  (__activeVars_lib->vrf_vector__X)
#define no_ipv6_distribute_list_prefix_cmd__VAR  (__activeVars_lib->no_ipv6_distribute_list_prefix_cmd__X)
#define no_config_log_file_cmd__VAR  (__activeVars_lib->no_config_log_file_cmd__X)
#define no_ip_community_list_name_expanded_cmd__VAR  (__activeVars_lib->no_ip_community_list_name_expanded_cmd__X)
#define multicast_cmd__VAR  (__activeVars_lib->multicast_cmd__X)
#define if_rmap_add_hook__VAR  (__activeVars_lib->if_rmap_add_hook__X)
#define no_vty_login_cmd__VAR  (__activeVars_lib->no_vty_login_cmd__X)
#define config_log_facility_cmd__VAR  (__activeVars_lib->config_log_facility_cmd__X)
#define no_neighbor_attr_unchanged6_cmd__VAR  (__activeVars_lib->no_neighbor_attr_unchanged6_cmd__X)
#define show_running_config_cmd__VAR  (__activeVars_lib->show_running_config_cmd__X)
#define no_match_ip_next_hop_cmd__VAR  (__activeVars_lib->no_match_ip_next_hop_cmd__X)
#define route_set_weight_cmd__VAR  (__activeVars_lib->route_set_weight_cmd__X)
#define show_ip_prefix_list_cmd__VAR  (__activeVars_lib->show_ip_prefix_list_cmd__X)
#define as_list_master__VAR  (__activeVars_lib->as_list_master__X)
#define no_neighbor_local_as_val2_cmd__VAR  (__activeVars_lib->no_neighbor_local_as_val2_cmd__X)
#define enable_password_text_cmd__VAR  (__activeVars_lib->enable_password_text_cmd__X)
#define no_match_ip_next_hop_prefix_list_cmd__VAR  (__activeVars_lib->no_match_ip_next_hop_prefix_list_cmd__X)
#define access_list_extended_any_mask_cmd__VAR  (__activeVars_lib->access_list_extended_any_mask_cmd__X)
#define no_set_local_pref_val_cmd__VAR  (__activeVars_lib->no_set_local_pref_val_cmd__X)
#define access_list_standard_cmd__VAR  (__activeVars_lib->access_list_standard_cmd__X)
#define access_list_extended_mask_host_cmd__VAR  (__activeVars_lib->access_list_extended_mask_host_cmd__X)
#define show_ip_access_list_name_cmd__VAR  (__activeVars_lib->show_ip_access_list_name_cmd__X)
#define neighbor_attr_unchanged1_cmd__VAR  (__activeVars_lib->neighbor_attr_unchanged1_cmd__X)
#define vpnv4_network_cmd__VAR  (__activeVars_lib->vpnv4_network_cmd__X)
#define no_access_list_extended_host_host_cmd__VAR  (__activeVars_lib->no_access_list_extended_host_host_cmd__X)
#define no_neighbor_peer_group_cmd__VAR  (__activeVars_lib->no_neighbor_peer_group_cmd__X)
#define no_rmap_onmatch_goto_cmd__VAR  (__activeVars_lib->no_rmap_onmatch_goto_cmd__X)
#define config_log_syslog_cmd__VAR  (__activeVars_lib->config_log_syslog_cmd__X)
#define no_ip_prefix_list_seq_le_ge_cmd__VAR  (__activeVars_lib->no_ip_prefix_list_seq_le_ge_cmd__X)
#define set_ip_nexthop_peer_cmd__VAR  (__activeVars_lib->set_ip_nexthop_peer_cmd__X)
#define ip_as_path_cmd__VAR  (__activeVars_lib->ip_as_path_cmd__X)
#define neighbor_timers_cmd__VAR  (__activeVars_lib->neighbor_timers_cmd__X)
#define route_match_ip_next_hop_cmd__VAR  (__activeVars_lib->route_match_ip_next_hop_cmd__X)
#define show_ip_prefix_list_summary_name_cmd__VAR  (__activeVars_lib->show_ip_prefix_list_summary_name_cmd__X)
#define re_syntax_options__VAR  (__activeVars_lib->re_syntax_options__X)
#define service_terminal_length_cmd__VAR  (__activeVars_lib->service_terminal_length_cmd__X)
#define route_set_aggregator_as_cmd__VAR  (__activeVars_lib->route_set_aggregator_as_cmd__X)
#define no_multicast_cmd__VAR  (__activeVars_lib->no_multicast_cmd__X)
#define no_neighbor_weight_val_cmd__VAR  (__activeVars_lib->no_neighbor_weight_val_cmd__X)
#define neighbor_set_peer_group_cmd__VAR  (__activeVars_lib->neighbor_set_peer_group_cmd__X)
#define no_service_advanced_vty_cmd__VAR  (__activeVars_lib->no_service_advanced_vty_cmd__X)
#define match_ecommunity_cmd__VAR  (__activeVars_lib->match_ecommunity_cmd__X)
#define t_write__VAR  (__activeVars_lib->t_write__X)
#define no_ip_community_list_name_standard_cmd__VAR  (__activeVars_lib->no_ip_community_list_name_standard_cmd__X)
#define key_cmd__VAR  (__activeVars_lib->key_cmd__X)
#define copy_runningconfig_startupconfig_cmd__VAR  (__activeVars_lib->copy_runningconfig_startupconfig_cmd__X)
#define ecomhash__VAR  (__activeVars_lib->ecomhash__X)
#define ifaddr_ipv4_table__VAR  (__activeVars_lib->ifaddr_ipv4_table__X)
#define no_route_map_cmd__VAR  (__activeVars_lib->no_route_map_cmd__X)
#define no_ip_address_cmd__VAR  (__activeVars_lib->no_ip_address_cmd__X)
#define neighbor_send_community_type_cmd__VAR  (__activeVars_lib->neighbor_send_community_type_cmd__X)
#define neighbor_interface_cmd__VAR  (__activeVars_lib->neighbor_interface_cmd__X)
#define no_neighbor_send_community_cmd__VAR  (__activeVars_lib->no_neighbor_send_community_cmd__X)
#define no_neighbor_strict_capability_cmd__VAR  (__activeVars_lib->no_neighbor_strict_capability_cmd__X)
#define no_neighbor_update_source_cmd__VAR  (__activeVars_lib->no_neighbor_update_source_cmd__X)
#define no_config_log_record_priority_cmd__VAR  (__activeVars_lib->no_config_log_record_priority_cmd__X)
#define ip_community_list_name_standard_cmd__VAR  (__activeVars_lib->ip_community_list_name_standard_cmd__X)
#define no_aggregate_address_as_set_summary_cmd__VAR  (__activeVars_lib->no_aggregate_address_as_set_summary_cmd__X)
#define route_match_interface_cmd__VAR  (__activeVars_lib->route_match_interface_cmd__X)
#define ip_community_list_cmd__VAR  (__activeVars_lib->ip_community_list_cmd__X)
#define no_router_id_cmd__VAR  (__activeVars_lib->no_router_id_cmd__X)
#define no_match_ip_address_val_cmd__VAR  (__activeVars_lib->no_match_ip_address_val_cmd__X)
#define no_neighbor_attr_unchanged10_cmd__VAR  (__activeVars_lib->no_neighbor_attr_unchanged10_cmd__X)
#define telnet_space_char__VAR  (__activeVars_lib->telnet_space_char__X)
#define neighbor_attr_unchanged_cmd__VAR  (__activeVars_lib->neighbor_attr_unchanged_cmd__X)
#define send_lifetime_infinite_day_month_cmd__VAR  (__activeVars_lib->send_lifetime_infinite_day_month_cmd__X)
#define access_list_extended_cmd__VAR  (__activeVars_lib->access_list_extended_cmd__X)
#define show_ip_prefix_list_name_seq_cmd__VAR  (__activeVars_lib->show_ip_prefix_list_name_seq_cmd__X)
#define no_distribute_list_all_cmd__VAR  (__activeVars_lib->no_distribute_list_all_cmd__X)
#define show_ip_extcommunity_list_cmd__VAR  (__activeVars_lib->show_ip_extcommunity_list_cmd__X)
#define route_match_ip_address_prefix_list_cmd__VAR  (__activeVars_lib->route_match_ip_address_prefix_list_cmd__X)
#define neighbor_passive_cmd__VAR  (__activeVars_lib->neighbor_passive_cmd__X)
#define neighbor_timers_connect_cmd__VAR  (__activeVars_lib->neighbor_timers_connect_cmd__X)
#define config_enable_cmd__VAR  (__activeVars_lib->config_enable_cmd__X)
#define access_list_extended_any_host_cmd__VAR  (__activeVars_lib->access_list_extended_any_host_cmd__X)
#define clear_ip_prefix_list_name_prefix_cmd__VAR  (__activeVars_lib->clear_ip_prefix_list_name_prefix_cmd__X)
#define no_set_metric_type_val_cmd__VAR  (__activeVars_lib->no_set_metric_type_val_cmd__X)
#define prefix_master_orf__VAR  (__activeVars_lib->prefix_master_orf__X)
#define neighbor_shutdown_cmd__VAR  (__activeVars_lib->neighbor_shutdown_cmd__X)
#define no_ipv6_distribute_list_cmd__VAR  (__activeVars_lib->no_ipv6_distribute_list_cmd__X)
#define cmdvec__VAR  (__activeVars_lib->cmdvec__X)
#define mpls_te_link_unrsv_bw_cmd__VAR  (__activeVars_lib->mpls_te_link_unrsv_bw_cmd__X)
#define ip_route_flags_distance_cmd__VAR  (__activeVars_lib->ip_route_flags_distance_cmd__X)
#define no_neighbor_override_capability_cmd__VAR  (__activeVars_lib->no_neighbor_override_capability_cmd__X)
#define zclient_debug__VAR  (__activeVars_lib->zclient_debug__X)
#define neighbor_enforce_multihop_cmd__VAR  (__activeVars_lib->neighbor_enforce_multihop_cmd__X)
#define no_neighbor_dont_capability_negotiate_cmd__VAR  (__activeVars_lib->no_neighbor_dont_capability_negotiate_cmd__X)
#define route_set_tag_cmd__VAR  (__activeVars_lib->route_set_tag_cmd__X)
#define shutdown_if_cmd__VAR  (__activeVars_lib->shutdown_if_cmd__X)
#define config_exit_cmd__VAR  (__activeVars_lib->config_exit_cmd__X)
#define no_set_atomic_aggregate_cmd__VAR  (__activeVars_lib->no_set_atomic_aggregate_cmd__X)
#define no_neighbor_default_originate_cmd__VAR  (__activeVars_lib->no_neighbor_default_originate_cmd__X)
#define no_set_ip_nexthop_cmd__VAR  (__activeVars_lib->no_set_ip_nexthop_cmd__X)
#define config_log_trap_cmd__VAR  (__activeVars_lib->config_log_trap_cmd__X)
#define ip_route_cmd__VAR  (__activeVars_lib->ip_route_cmd__X)
#define route_set_ecommunity_soo_cmd__VAR  (__activeVars_lib->route_set_ecommunity_soo_cmd__X)
#define disthash__VAR  (__activeVars_lib->disthash__X)
#define no_access_list_extended_any_any_cmd__VAR  (__activeVars_lib->no_access_list_extended_any_any_cmd__X)
#define address_family_ipv6_unicast_cmd__VAR  (__activeVars_lib->address_family_ipv6_unicast_cmd__X)
#define no_match_community_val_cmd__VAR  (__activeVars_lib->no_match_community_val_cmd__X)
#define no_ip_prefix_list_seq_ge_le_cmd__VAR  (__activeVars_lib->no_ip_prefix_list_seq_ge_le_cmd__X)
#define mpls_te_link_metric_cmd__VAR  (__activeVars_lib->mpls_te_link_metric_cmd__X)
#define no_neighbor_cmd__VAR  (__activeVars_lib->no_neighbor_cmd__X)
#define no_match_ecommunity_cmd__VAR  (__activeVars_lib->no_match_ecommunity_cmd__X)
#define route_match_community_cmd__VAR  (__activeVars_lib->route_match_community_cmd__X)
#define no_match_aspath_val_cmd__VAR  (__activeVars_lib->no_match_aspath_val_cmd__X)
#define access_master_ipv4__VAR  (__activeVars_lib->access_master_ipv4__X)
#define no_synchronization_cmd__VAR  (__activeVars_lib->no_synchronization_cmd__X)
#define neighbor_capability_dynamic_cmd__VAR  (__activeVars_lib->neighbor_capability_dynamic_cmd__X)
#define interface_desc_cmd__VAR  (__activeVars_lib->interface_desc_cmd__X)
#define key_chain_cmd__VAR  (__activeVars_lib->key_chain_cmd__X)
#define no_aggregate_address_mask_summary_as_set_cmd__VAR  (__activeVars_lib->no_aggregate_address_mask_summary_as_set_cmd__X)
#define no_set_originator_id_val_cmd__VAR  (__activeVars_lib->no_set_originator_id_val_cmd__X)
#define ip_prefix_list_ge_cmd__VAR  (__activeVars_lib->ip_prefix_list_ge_cmd__X)
#define auth_enable_node__VAR  (__activeVars_lib->auth_enable_node__X)
#define no_config_log_trap_cmd__VAR  (__activeVars_lib->no_config_log_trap_cmd__X)
#define set_local_pref_cmd__VAR  (__activeVars_lib->set_local_pref_cmd__X)
#define apiserver_list__VAR  (__activeVars_lib->apiserver_list__X)
#define no_neighbor_local_as_cmd__VAR  (__activeVars_lib->no_neighbor_local_as_cmd__X)
#define service_password_encrypt_cmd__VAR  (__activeVars_lib->service_password_encrypt_cmd__X)
#define neighbor_attr_unchanged7_cmd__VAR  (__activeVars_lib->neighbor_attr_unchanged7_cmd__X)
#define no_access_list_extended_mask_host_cmd__VAR  (__activeVars_lib->no_access_list_extended_mask_host_cmd__X)
#define no_if_ipv6_rmap_cmd__VAR  (__activeVars_lib->no_if_ipv6_rmap_cmd__X)
#define route_set_vec__VAR  (__activeVars_lib->route_set_vec__X)
#define if_master__VAR  (__activeVars_lib->if_master__X)
#define vty_ipv6_accesslist_name__VAR  (__activeVars_lib->vty_ipv6_accesslist_name__X)
#define no_auto_summary_cmd__VAR  (__activeVars_lib->no_auto_summary_cmd__X)
#define neighbor_allowas_in_cmd__VAR  (__activeVars_lib->neighbor_allowas_in_cmd__X)
#define no_neighbor_capability_dynamic_cmd__VAR  (__activeVars_lib->no_neighbor_capability_dynamic_cmd__X)
#define show_ip_extcommunity_list_arg_cmd__VAR  (__activeVars_lib->show_ip_extcommunity_list_arg_cmd__X)
#define no_match_ip_nexthop_cmd__VAR  (__activeVars_lib->no_match_ip_nexthop_cmd__X)
#define ip_community_list_name_expanded_cmd__VAR  (__activeVars_lib->ip_community_list_name_expanded_cmd__X)
#define no_access_list_remark_arg_cmd__VAR  (__activeVars_lib->no_access_list_remark_arg_cmd__X)
#define no_config_log_monitor_cmd__VAR  (__activeVars_lib->no_config_log_monitor_cmd__X)
#define set_tag_cmd__VAR  (__activeVars_lib->set_tag_cmd__X)
#define no_ip_prefix_list_le_ge_cmd__VAR  (__activeVars_lib->no_ip_prefix_list_le_ge_cmd__X)
#define no_set_community_none_cmd__VAR  (__activeVars_lib->no_set_community_none_cmd__X)
#define no_set_aggregator_as_val_cmd__VAR  (__activeVars_lib->no_set_aggregator_as_val_cmd__X)
#define peer_list__VAR  (__activeVars_lib->peer_list__X)
#define set_origin_cmd__VAR  (__activeVars_lib->set_origin_cmd__X)
#define no_ip_route_mask_cmd__VAR  (__activeVars_lib->no_ip_route_mask_cmd__X)
#define last_nonopt__VAR  (__activeVars_lib->last_nonopt__X)
#define nl_rcvbufsize__VAR  (__activeVars_lib->nl_rcvbufsize__X)
#define show_mpls_te_link_cmd__VAR  (__activeVars_lib->show_mpls_te_link_cmd__X)
#define show_ip_as_path_access_list_cmd__VAR  (__activeVars_lib->show_ip_as_path_access_list_cmd__X)
#define reg_unset_dummy__VAR  (__activeVars_lib->reg_unset_dummy__X)
#define neighbor_route_map_cmd__VAR  (__activeVars_lib->neighbor_route_map_cmd__X)
#define config_disable_cmd__VAR  (__activeVars_lib->config_disable_cmd__X)
#define clear_ip_prefix_list_name_cmd__VAR  (__activeVars_lib->clear_ip_prefix_list_name_cmd__X)
#define no_ip_route_flags2_cmd__VAR  (__activeVars_lib->no_ip_route_flags2_cmd__X)
#define ip_address_label_cmd__VAR  (__activeVars_lib->ip_address_label_cmd__X)
#define no_access_list_standard_cmd__VAR  (__activeVars_lib->no_access_list_standard_cmd__X)
#define no_ip_route_flags_distance2_cmd__VAR  (__activeVars_lib->no_ip_route_flags_distance2_cmd__X)
#define comhash__VAR  (__activeVars_lib->comhash__X)
#define keychain_key_node__VAR  (__activeVars_lib->keychain_key_node__X)
#define no_aggregate_address_mask_as_set_cmd__VAR  (__activeVars_lib->no_aggregate_address_mask_as_set_cmd__X)
#define no_rmap_continue_seq__VAR  (__activeVars_lib->no_rmap_continue_seq__X)
#define config_write_file_cmd__VAR  (__activeVars_lib->config_write_file_cmd__X)
#define no_config_log_syslog_facility_cmd__VAR  (__activeVars_lib->no_config_log_syslog_facility_cmd__X)
#define vty_timeout_val__VAR  (__activeVars_lib->vty_timeout_val__X)
#define no_set_weight_val_cmd__VAR  (__activeVars_lib->no_set_weight_val_cmd__X)
#define show_thread_cpu_cmd__VAR  (__activeVars_lib->show_thread_cpu_cmd__X)
#define ifrmaphash__VAR  (__activeVars_lib->ifrmaphash__X)
#define accept_lifetime_infinite_month_day_cmd__VAR  (__activeVars_lib->accept_lifetime_infinite_month_day_cmd__X)
#define neighbor_attr_unchanged5_cmd__VAR  (__activeVars_lib->neighbor_attr_unchanged5_cmd__X)
#define zprivs_state__VAR  (__activeVars_lib->zprivs_state__X)
#define show_memory_isis_cmd__VAR  (__activeVars_lib->show_memory_isis_cmd__X)
#define set_ecommunity_soo_cmd__VAR  (__activeVars_lib->set_ecommunity_soo_cmd__X)
#define no_access_list_standard_any_cmd__VAR  (__activeVars_lib->no_access_list_standard_any_cmd__X)
#define no_ip_route_mask_flags_cmd__VAR  (__activeVars_lib->no_ip_route_mask_flags_cmd__X)
#define no_neighbor_timers_cmd__VAR  (__activeVars_lib->no_neighbor_timers_cmd__X)
#define no_rmap_call_cmd__VAR  (__activeVars_lib->no_rmap_call_cmd__X)
#define aggregate_address_mask_summary_as_set_cmd__VAR  (__activeVars_lib->aggregate_address_mask_summary_as_set_cmd__X)
#define no_ip_route_cmd__VAR  (__activeVars_lib->no_ip_route_cmd__X)
#define neighbor_attr_unchanged2_cmd__VAR  (__activeVars_lib->neighbor_attr_unchanged2_cmd__X)
#define netlink_cmd__VAR  (__activeVars_lib->netlink_cmd__X)
#define show_logging_cmd__VAR  (__activeVars_lib->show_logging_cmd__X)
#define no_config_log_stdout_cmd__VAR  (__activeVars_lib->no_config_log_stdout_cmd__X)
#define address_family_ipv4_cmd__VAR  (__activeVars_lib->address_family_ipv4_cmd__X)
#define show_table_cmd__VAR  (__activeVars_lib->show_table_cmd__X)
#define show_ip_forwarding_cmd__VAR  (__activeVars_lib->show_ip_forwarding_cmd__X)
#define show_ip_route_protocol_cmd__VAR  (__activeVars_lib->show_ip_route_protocol_cmd__X)
#define ip_extcommunity_list_name_standard_cmd__VAR  (__activeVars_lib->ip_extcommunity_list_name_standard_cmd__X)
#define match_aspath_cmd__VAR  (__activeVars_lib->match_aspath_cmd__X)
#define route_match_vec__VAR  (__activeVars_lib->route_match_vec__X)
#define show_ip_route_addr_cmd__VAR  (__activeVars_lib->show_ip_route_addr_cmd__X)
#define ipv6_distribute_list_cmd__VAR  (__activeVars_lib->ipv6_distribute_list_cmd__X)
#define match_peer_cmd__VAR  (__activeVars_lib->match_peer_cmd__X)
#define no_ip_prefix_list_seq_cmd__VAR  (__activeVars_lib->no_ip_prefix_list_seq_cmd__X)
#define route_match_ecommunity_cmd__VAR  (__activeVars_lib->route_match_ecommunity_cmd__X)
#define neighbor_weight_cmd__VAR  (__activeVars_lib->neighbor_weight_cmd__X)
#define Debug_Update__VAR  (__activeVars_lib->Debug_Update__X)
#define vty_cwd__VAR  (__activeVars_lib->vty_cwd__X)
#define no_neighbor_local_as_val_cmd__VAR  (__activeVars_lib->no_neighbor_local_as_val_cmd__X)
#define no_ip_extcommunity_list_name_standard_cmd__VAR  (__activeVars_lib->no_ip_extcommunity_list_name_standard_cmd__X)
#define distribute_list_prefix_cmd__VAR  (__activeVars_lib->distribute_list_prefix_cmd__X)
#define neighbor_nexthop_self_cmd__VAR  (__activeVars_lib->neighbor_nexthop_self_cmd__X)

#endif
