#! /bin/bash

make MODE=debug > test.out

./inet_dbg -c UnitTest -u Cmdenv >> test.out

if [[ $? -eq 0 ]]; then
    echo "Packet unit test: PASS"
    exit 0
else
    echo "Packet unit test: FAIL"
    exit 1
fi
