QUAGGA_DIR=quagga-0.98.5

include ../../../inetconfig

all:
	cd $(QUAGGA_DIR) && make

clean:
	cd $(QUAGGA_DIR) && make clean

generateheaders: # target invoked by OMNeT++-generated uplevel Makefile.vc; does nothing for now

depend:	# target invoked by OMNeT++-generated uplevel Makefile.vc; does nothing for now

