#! /bin/sh
#
# usage: runtest [<testfile>...]
# without args, runs all *.test files in the current directory
#

echo "\nThese tests are disabled currently.\n"
exit 0

######################################################################

MAKE="make MODE=debug"
INET_ROOT=$(cd $(dirname $0)/../..; pwd)

# Test if we are running on OMNeT++ 5.1 as we did not have the _dbg suffix for debug binaries on 5.1
# (this can be removed if OMNeT++ 5.1 compatibility is no longer needed)
#
OMNETPP_51=$(grep "OMNETPP_VERSION = 5.1" $(opp_configfilepath))
if [ -z $OMNETPP_51 ]; then
DBG_SUFFIX="_dbg"
else
DBG_SUFFIX=""
fi

TESTFILES=$*
if [ "x$TESTFILES" = "x" ]; then TESTFILES='*.test'; fi
if [ ! -d work ];  then mkdir work; fi

opp_test gen $OPT -v $TESTFILES || exit 1

echo
export NEDPATH="$INET_ROOT/src"
opp_test run $OPT -vv $TESTFILES -a "-n $INET_ROOT/src/:. -u Cmdenv -l$INET_ROOT/src/INET$DBG_SUFFIX " || exit 1
echo
echo Results can be found in ./work
