//
// Generated file, do not edit! Created by nedtool 5.2 from inet/physicallayer/common/packetlevel/Signal.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __INET__PHYSICALLAYER_SIGNAL_M_H
#define __INET__PHYSICALLAYER_SIGNAL_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif

// cplusplus {{
#include "inet/physicallayer/common/packetlevel/Signal.h"
// }}


namespace inet {
namespace physicallayer {

// cplusplus {{
typedef const ITransmission * ITransmissionPtr;
typedef const IArrival * IArrivalPtr;
typedef const IListening * IListeningPtr;
typedef const IReception * IReceptionPtr;
// }}

} // namespace physicallayer
} // namespace inet

#endif // ifndef __INET__PHYSICALLAYER_SIGNAL_M_H

