#define stat(a,b)  oppsim_stat(a,b)
#define sigaction(a,b,c)  oppsim_sigaction(a,b,c)
#define open  oppsim_open
#define crypt  oppsim_crypt
#define getrusage  oppsim_getrusage
#define time  oppsim_time
#define getpid  oppsim_getpid
#define gettimeofday  oppsim_gettimeofday
#define sigfillset  oppsim_sigfillset
#define random  oppsim_random
#define socket  oppsim_socket
#define getpwnam  oppsim_getpwnam
#define getgrnam  oppsim_getgrnam
#define setregid  oppsim_setregid
#define setreuid  oppsim_setreuid
#define seteuid  oppsim_seteuid
#define umask  oppsim_umask
#define daemon  oppsim_daemon
#define srand  oppsim_srand
#define sync  oppsim_sync
#define setsockopt  oppsim_setsockopt
#define getuid  oppsim_getuid
#define geteuid  oppsim_geteuid
#define exit  oppsim_exit
#define mkstemp  oppsim_mkstemp
#define getcwd  oppsim_getcwd
#define openlog  oppsim_openlog
#define closelog  oppsim_closelog
#define vsyslog  oppsim_vsyslog
#define connect  oppsim_connect
#define listen  oppsim_listen
#define bind  oppsim_bind
#define fcntl  oppsim_fcntl
#define getsockname  oppsim_getsockname
#define sendto  oppsim_sendto
#define recvfrom  oppsim_recvfrom
#define recvmsg  oppsim_recvmsg
#define fopen  oppsim_fopen
#define getpagesize  oppsim_getpagesize
#define write  oppsim_write
#define select  oppsim_select
#define accept  oppsim_accept
#define sendmsg  oppsim_sendmsg
#define close  oppsim_close
#define read  oppsim_read
#define writev  oppsim_writev
#define perror  oppsim_perror
#define _exit  oppsim__exit
#define abort  oppsim_abort
#define getpeername  oppsim_getpeername
#define getsockopt  oppsim_getsockopt
#define chmod  oppsim_chmod
#define unlink  oppsim_unlink
#define link  oppsim_link
#define chdir  oppsim_chdir
#define uname  oppsim_uname
#define ioctl  oppsim_ioctl
#define setgroups  oppsim_setgroups
#define getenv  oppsim_getenv
#define zmalloc  oppsim_zmalloc
#define zcalloc  oppsim_zcalloc
#define zrealloc  oppsim_zrealloc
#define getservbyname oppsim_getservbyname
#define htonl  oppsim_htonl
#define htons  oppsim_htons
#define inet_ntoa  oppsim_inet_ntoa
#define ntohl  oppsim_ntohl
#define ntohs  oppsim_ntohs
#define inet_addr  oppsim_inet_addr
#define inet_aton  oppsim_inet_aton
#define inet_pton  oppsim_inet_pton
#define inet_ntop  oppsim_inet_ntop

