#!/bin/sh
if [ -n "$1" ] ; then
  echo Please change to the directory you want to convert and run the script there without any command line argument!
  exit 1
fi

echo
echo Press ENTER to convert all NED files under the current directory:
echo `pwd`
echo
read WAIT

find . -name "*.ned" >nedfiles.lst

echo The following files will be checked/modified:
cat nedfiles.lst | less

echo
echo Press ENTER to start the conversion, or CTRL-C to quit.
read WAIT

perl `dirname $0`/migratened.pl nedfiles.lst

