rm rng.ini
echo "[General]" >> rng.ini
echo "num-rngs = 9" >> rng.ini
echo "seed-1-mt=\${$RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM !  repetition}" >> rng.ini
echo "seed-2-mt=\${$RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM !  repetition}" >> rng.ini
echo "seed-3-mt=\${$RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM !  repetition}" >> rng.ini
echo "seed-4-mt=\${$RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM !  repetition}" >> rng.ini
echo "seed-5-mt=\${$RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM !  repetition}" >> rng.ini
echo "seed-6-mt=\${$RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM !  repetition}" >> rng.ini
echo "seed-7-mt=\${$RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM !  repetition}" >> rng.ini
echo "seed-8-mt=\${$RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM !  repetition}" >> rng.ini
echo "seed-0-mt=\${$RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM, $RANDOM !  repetition}" >> rng.ini

