from inet.test.all import *
from inet.test.analysis import *
from inet.test.feature import *
from inet.test.fingerprint import *
from inet.test.leak import *
from inet.test.opp import *
from inet.test.regression import *
from inet.test.run import *
from inet.test.simulation import *
from inet.test.smoke import *
from inet.test.speed import *
from inet.test.statistical import *
from inet.test.validation import *
