#ifndef __GLOBALVARS_OSPFD_H__
#define __GLOBALVARS_OSPFD_H__

#include "allheaders.h"

extern struct GlobalVars_ospfd * __activeVars_ospfd;

void GlobalVars_initializeActiveSet_ospfd();

struct GlobalVars_ospfd
{
    struct cmd_element ospf_area_vlink_param1_cmd__X;
    struct cmd_element no_ospf_area_vlink_param1_cmd__X;
    struct cmd_element no_debug_ospf_zebra_sub_cmd__X;
    struct cmd_element show_ip_ospf_neighbor_int_cmd__X;
    struct cmd_element router_ospf_cmd__X;
    struct cmd_element ospf_transmit_delay_cmd__X;
    struct cmd_element ospf_area_range_substitute_cmd__X;
    struct cmd_element ospf_distance_ospf_intra_inter_cmd__X;
    struct cmd_element ospf_area_filter_list_cmd__X;
    struct cmd_element no_ospf_network_area_cmd__X;
    struct cmd_element ospf_default_metric_cmd__X;
    struct cmd_element ospf_distance_ospf_intra_external_inter_cmd__X;
    unsigned long term_debug_ospf_ism__X;
    struct_ospf_master * om__X;
    unsigned long conf_debug_ospf_ism__X;
    struct cmd_element ospf_redistribute_source_type_routemap_cmd__X;
    struct cmd_element no_ospf_refresh_timer_val_cmd__X;
    struct cmd_element debug_ospf_zebra_cmd__X;
    struct cmd_element no_ip_ospf_message_digest_key_cmd__X;
    struct cmd_element ospf_default_information_originate_metric_type_routemap_cmd__X;
    struct cmd_element show_ip_ospf_database_cmd__X;
    struct cmd_element ospf_redistribute_source_metric_routemap_cmd__X;
    struct cmd_element ip_ospf_cost_cmd__X;
    struct cmd_element ospf_opaque_capable_cmd__X;
    struct cmd_element no_ospf_auto_cost_reference_bandwidth_cmd__X;
    struct cmd_element ospf_default_information_originate_routemap_cmd__X;
    struct list * ospf_opaque_type10_funclist__X;
    struct cmd_element ospf_area_vlink_authtype_args_authkey_cmd__X;
    struct cmd_element show_debugging_ospf_cmd__X;
    struct cmd_element ospf_area_nssa_cmd__X;
    struct cmd_element show_ip_ospf_neighbor_int_detail_cmd__X;
    struct cmd_element no_ospf_area_filter_list_cmd__X;
    struct cmd_node ospf_node__X;
    struct cmd_element ospf_neighbor_poll_interval_priority_cmd__X;
    struct cmd_element ospf_default_information_originate_always_metric_type_cmd__X;
    struct cmd_element no_ospf_area_range_cmd__X;
    struct cmd_element no_ospf_network_cmd__X;
    struct cmd_element no_ospf_area_stub_cmd__X;
    struct cmd_element ospf_distance_ospf_intra_inter_external_cmd__X;
    struct cmd_element no_ospf_area_export_list_cmd__X;
    struct cmd_element ospf_area_shortcut_cmd__X;
    struct cmd_element ospf_area_import_list_cmd__X;
    struct cmd_element debug_ospf_lsa_sub_cmd__X;
    struct cmd_element ip_ospf_hello_interval_cmd__X;
    struct cmd_element debug_ospf_ism_cmd__X;
    struct cmd_element no_ip_ospf_dead_interval_cmd__X;
    struct cmd_element show_ip_ospf_neighbor_all_cmd__X;
    struct cmd_element ospf_default_information_originate_always_type_metric_routemap_cmd__X;
    struct cmd_element no_ospf_distance_ospf_cmd__X;
    struct cmd_element ospf_default_information_originate_always_type_routemap_cmd__X;
    struct cmd_element no_ospf_area_range_cost_cmd__X;
    struct list * ospf_opaque_type11_funclist__X;
    struct cmd_element ospf_distance_ospf_external_intra_inter_cmd__X;
    struct cmd_element ospf_default_information_originate_always_cmd__X;
    unsigned long conf_debug_ospf_zebra__X;
    struct cmd_element ospf_auto_cost_reference_bandwidth_cmd__X;
    struct cmd_element no_ospf_area_vlink_md5_cmd__X;
    struct cmd_element no_ospf_area_range_substitute_cmd__X;
    struct cmd_element no_ospf_neighbor_cmd__X;
    struct cmd_element debug_ospf_zebra_sub_cmd__X;
    struct cmd_element no_ospf_area_range_advertise_cmd__X;
    unsigned long term_debug_ospf_zebra__X;
    struct cmd_element no_ospf_rfc1583_flag_cmd__X;
    struct cmd_element ospf_area_vlink_authtype_authkey_cmd__X;
    struct cmd_element ip_ospf_transmit_delay_addr_cmd__X;
    struct cmd_element ospf_default_information_originate_always_type_cmd__X;
    struct cmd_element no_ospf_passive_interface_addr_cmd__X;
    struct cmd_element no_debug_ospf_packet_send_recv_cmd__X;
    struct cmd_element no_ospf_refresh_timer_cmd__X;
    struct cmd_element no_ospf_router_id_cmd__X;
    struct cmd_element show_ip_ospf_cmd__X;
    struct cmd_element ospf_retransmit_interval_cmd__X;
    struct cmd_element show_ip_ospf_interface_cmd__X;
    struct ospf_mpls_te OspfMplsTE__X;
    struct list * ospf_opaque_type9_funclist__X;
    struct cmd_element no_ospf_default_information_originate_cmd__X;
    struct cmd_element show_ip_ospf_border_routers_cmd__X;
    struct cmd_element ospf_distance_cmd__X;
    int ospf_apiserver_enable__X;
    struct cmd_element no_router_ospf_id_cmd__X;
    struct cmd_element no_ip_ospf_cost_cmd__X;
    struct cmd_element show_ip_ospf_neighbor_detail_all_cmd__X;
    struct cmd_element debug_ospf_packet_send_recv_detail_cmd__X;
    struct cmd_element show_ip_ospf_route_cmd__X;
    struct cmd_element ospf_area_export_list_cmd__X;
    struct cmd_element ospf_area_authentication_cmd__X;
    struct cmd_element ospf_passive_interface_addr_cmd__X;
    struct cmd_element ospf_distance_ospf_external_inter_intra_cmd__X;
    struct cmd_element ip_ospf_hello_interval_addr_cmd__X;
    struct cmd_element debug_ospf_nsm_sub_cmd__X;
    struct cmd_element ospf_area_vlink_authtype_md5_cmd__X;
    struct cmd_element ospf_area_nssa_translate_no_summary_cmd__X;
    struct cmd_element no_ospf_area_authentication_cmd__X;
    struct cmd_element no_ospf_redistribute_source_cmd__X;
    struct cmd_element ospf_network_cmd__X;
    struct cmd_element no_ospf_passive_interface_cmd__X;
    struct cmd_element no_ospf_distance_cmd__X;
    struct cmd_element no_router_ospf_cmd__X;
    struct cmd_element ip_ospf_transmit_delay_cmd__X;
    struct cmd_element ospf_distance_source_access_list_cmd__X;
    struct cmd_element ospf_distance_ospf_inter_cmd__X;
    struct cmd_element show_ip_ospf_database_type_id_self_cmd__X;
    struct cmd_element ospf_redistribute_source_type_metric_cmd__X;
    struct cmd_element ospf_distance_ospf_external_cmd__X;
    struct cmd_element ospf_redistribute_source_metric_cmd__X;
    struct cmd_element no_ospf_neighbor_priority_pollinterval_cmd__X;
    struct cmd_element ospf_neighbor_priority_cmd__X;
    struct cmd_element no_ospf_default_metric_val_cmd__X;
    struct cmd_element ospf_default_information_originate_always_routemap_cmd__X;
    struct cmd_element ospf_area_vlink_authtype_cmd__X;
    struct cmd_element ospf_passive_interface_cmd__X;
    struct cmd_element ospf_area_vlink_authtype_args_md5_cmd__X;
    struct cmd_element ospf_cost_cmd__X;
    struct cmd_element ospf_distance_ospf_inter_intra_external_cmd__X;
    struct cmd_element ospf_distance_source_cmd__X;
    struct cmd_element no_ospf_authentication_key_cmd__X;
    struct cmd_element ospf_area_range_not_advertise_cmd__X;
    struct cmd_element ospf_redistribute_source_metric_type_cmd__X;
    struct cmd_element no_ip_ospf_priority_cmd__X;
    struct cmd_element ospf_abr_type_cmd__X;
    struct cmd_element ospf_redistribute_source_metric_type_routemap_cmd__X;
    struct cmd_element no_debug_ospf_nsm_cmd__X;
    struct cmd_element ospf_redistribute_source_type_cmd__X;
    struct cmd_element ospf_neighbor_poll_interval_cmd__X;
    struct cmd_element no_ospf_opaque_capable_cmd__X;
    struct cmd_element ospf_priority_cmd__X;
    struct cmd_element ospf_hello_interval_cmd__X;
    struct list * ospf_opaque_wildcard_funclist__X;
    struct cmd_element show_ip_ospf_neighbor_cmd__X;
    struct cmd_element show_ip_ospf_database_type_id_adv_router_cmd__X;
    struct cmd_element no_ip_ospf_authentication_cmd__X;
    struct cmd_element ospf_rfc1583_flag_cmd__X;
    unsigned long conf_debug_ospf_event__X;
    struct cmd_element ip_ospf_priority_cmd__X;
    struct cmd_element ospf_area_vlink_param4_cmd__X;
    unsigned long conf_debug_ospf_packet__X[5];
    struct cmd_element debug_ospf_lsa_cmd__X;
    unsigned long conf_debug_ospf_nssa__X;
    struct cmd_element ospf_distribute_list_out_cmd__X;
    struct cmd_element no_ospf_distance_source_access_list_cmd__X;
    struct cmd_element ospf_refresh_timer_cmd__X;
    struct cmd_element ospf_area_vlink_authtype_args_cmd__X;
    struct cmd_element show_ip_ospf_database_type_adv_router_cmd__X;
    struct cmd_element no_ip_ospf_authentication_addr_cmd__X;
    struct cmd_element no_ospf_area_shortcut_cmd__X;
    struct cmd_element no_ip_ospf_transmit_delay_addr_cmd__X;
    struct cmd_element ospf_area_range_advertise_cmd__X;
    struct cmd_element no_ip_ospf_transmit_delay_cmd__X;
    struct cmd_element ospf_default_information_originate_type_cmd__X;
    struct cmd_element ospf_distance_ospf_intra_external_cmd__X;
    struct cmd_element ip_ospf_dead_interval_addr_cmd__X;
    struct cmd_element ospf_default_information_originate_type_routemap_cmd__X;
    struct cmd_element no_ip_ospf_priority_addr_cmd__X;
    struct cmd_element no_debug_ospf_ism_cmd__X;
    struct cmd_element no_ospf_neighbor_poll_interval_cmd__X;
    struct cmd_element no_ospf_distance_source_cmd__X;
    struct cmd_element ospf_area_default_cost_cmd__X;
    struct cmd_element no_ospf_area_nssa_cmd__X;
    struct cmd_element no_ospf_hello_interval_cmd__X;
    struct cmd_element ospf_router_id_cmd__X;
    struct cmd_element ospf_area_authentication_message_digest_cmd__X;
    struct cmd_element ospf_distance_ospf_inter_external_intra_cmd__X;
    struct cmd_element no_ospf_transmit_delay_cmd__X;
    struct cmd_element no_ospf_message_digest_key_cmd__X;
    struct cmd_element ospf_message_digest_key_cmd__X;
    struct cmd_element ip_ospf_authentication_cmd__X;
    struct cmd_element no_ospf_abr_type_cmd__X;
    struct cmd_element show_ip_ospf_database_type_self_cmd__X;
    struct cmd_element show_ip_ospf_database_type_cmd__X;
    unsigned long conf_debug_ospf_nsm__X;
    struct cmd_element no_ospf_neighbor_priority_cmd__X;
    struct cmd_element no_ospf_area_vlink_authtype_cmd__X;
    struct cmd_element ip_ospf_cost_addr_cmd__X;
    struct cmd_element ospf_distance_ospf_intra_cmd__X;
    struct cmd_element ospf_network_area_cmd__X;
    struct cmd_element no_debug_ospf_lsa_sub_cmd__X;
    struct cmd_element ip_ospf_message_digest_key_cmd__X;
    struct cmd_element ospf_compatible_rfc1583_cmd__X;
    struct cmd_element ospf_area_vlink_authkey_cmd__X;
    struct cmd_element ip_ospf_authentication_key_addr_cmd__X;
    struct cmd_element ip_ospf_dead_interval_cmd__X;
    struct cmd_element ospf_area_vlink_cmd__X;
    struct cmd_element ospf_neighbor_priority_poll_interval_cmd__X;
    struct cmd_element ospf_distance_ospf_external_intra_cmd__X;
    struct cmd_element no_debug_ospf_lsa_cmd__X;
    struct cmd_element no_ospf_area_vlink_authkey_cmd__X;
    unsigned long term_debug_ospf_event__X;
    struct cmd_element no_ip_ospf_dead_interval_addr_cmd__X;
    struct cmd_element no_ip_ospf_hello_interval_cmd__X;
    struct cmd_element no_ospf_area_nssa_no_summary_cmd__X;
    struct cmd_element ospf_area_range_cost_cmd__X;
    unsigned long term_debug_ospf_nssa__X;
    struct cmd_element no_ospf_area_vlink_param2_cmd__X;
    struct cmd_element no_ospf_distribute_list_out_cmd__X;
    struct cmd_element no_ip_ospf_retransmit_interval_cmd__X;
    struct cmd_element debug_ospf_packet_all_cmd__X;
    struct cmd_element no_ospf_timers_spf_cmd__X;
    struct cmd_element ospf_default_information_originate_type_metric_routemap_cmd__X;
    struct cmd_element ospf_area_nssa_translate_cmd__X;
    struct cmd_element ospf_dead_interval_cmd__X;
    struct cmd_element ospf_area_stub_cmd__X;
    struct cmd_element ospf_area_range_advertise_cost_cmd__X;
    struct cmd_element ospf_area_vlink_param3_cmd__X;
    struct cmd_element ospf_default_information_originate_cmd__X;
    struct cmd_element ospf_area_vlink_md5_cmd__X;
    unsigned long term_debug_ospf_nsm__X;
    struct cmd_element ospf_redistribute_source_routemap_cmd__X;
    struct_ospf_master ospf_master__X;
    struct cmd_element ospf_redistribute_source_type_metric_routemap_cmd__X;
    struct cmd_element ip_ospf_authentication_args_addr_cmd__X;
    struct cmd_element no_ospf_area_stub_no_summary_cmd__X;
    struct cmd_element ospf_default_information_originate_always_metric_routemap_cmd__X;
    struct cmd_element show_ip_ospf_database_type_id_cmd__X;
    struct cmd_element no_ospf_area_vlink_authtype_authkey_cmd__X;
    unsigned long term_debug_ospf_lsa__X;
    struct cmd_element no_ip_ospf_retransmit_interval_addr_cmd__X;
    struct cmd_element router_ospf_id_cmd__X;
    struct cmd_element no_ospf_area_vlink_param4_cmd__X;
    struct cmd_element ospf_default_information_originate_metric_type_cmd__X;
    struct cmd_element ospf_default_information_originate_type_metric_cmd__X;
    struct cmd_element no_ospf_area_default_cost_cmd__X;
    unsigned long term_debug_ospf_packet__X[5];
    struct cmd_element ospf_authentication_key_cmd__X;
    struct cmd_element no_debug_ospf_packet_all_cmd__X;
    struct cmd_element ip_ospf_network_cmd__X;
    struct cmd_element no_ospf_area_vlink_cmd__X;
    struct cmd_element no_ospf_area_range_advertise_cost_cmd__X;
    int ospf_area_type_msg_max__X;
    struct cmd_element ip_ospf_retransmit_interval_addr_cmd__X;
    struct cmd_element show_ip_ospf_neighbor_detail_cmd__X;
    struct cmd_element no_ospf_area_vlink_authtype_md5_cmd__X;
    struct cmd_element no_ospf_cost_cmd__X;
    struct cmd_element debug_ospf_nssa_cmd__X;
    struct cmd_element debug_ospf_event_cmd__X;
    struct cmd_element no_ip_ospf_hello_interval_addr_cmd__X;
    struct cmd_element no_debug_ospf_packet_send_recv_detail_cmd__X;
    struct cmd_element debug_ospf_ism_sub_cmd__X;
    struct cmd_element ospf_area_range_cmd__X;
    struct cmd_element ip_ospf_retransmit_interval_cmd__X;
    struct cmd_element ospf_area_nssa_no_summary_cmd__X;
    struct cmd_element ip_ospf_authentication_key_cmd__X;
    struct cmd_element no_ospf_dead_interval_cmd__X;
    struct cmd_element ospf_default_information_originate_always_metric_type_routemap_cmd__X;
    struct cmd_element ospf_area_vlink_param2_cmd__X;
    struct cmd_element no_debug_ospf_ism_sub_cmd__X;
    struct cmd_element debug_ospf_nsm_cmd__X;
    struct cmd_element show_ip_ospf_neighbor_id_cmd__X;
    struct cmd_element ospf_distance_ospf_external_inter_cmd__X;
    unsigned long conf_debug_ospf_lsa__X;
    struct cmd_element no_ospf_compatible_rfc1583_cmd__X;
    struct cmd_element ospf_default_information_originate_always_metric_cmd__X;
    struct cmd_element ip_ospf_authentication_addr_cmd__X;
    struct cmd_element ip_ospf_authentication_args_cmd__X;
    struct cmd_element no_debug_ospf_nssa_cmd__X;
    struct cmd_element no_ip_ospf_network_cmd__X;
    struct cmd_element ospf_neighbor_cmd__X;
    struct cmd_element no_ospf_area_vlink_param3_cmd__X;
    struct cmd_element no_ospf_default_metric_cmd__X;
    struct cmd_element ospf_distance_ospf_inter_external_cmd__X;
    struct cmd_element no_ospf_priority_cmd__X;
    struct cmd_element no_debug_ospf_nsm_sub_cmd__X;
    struct cmd_element ospf_redistribute_source_cmd__X;
    struct cmd_element ospf_default_information_originate_always_type_metric_cmd__X;
    struct cmd_element ip_ospf_priority_addr_cmd__X;
    struct cmd_element no_debug_ospf_zebra_cmd__X;
    struct cmd_element ospf_distance_ospf_inter_intra_cmd__X;
    struct cmd_element ospf_timers_spf_cmd__X;
    struct cmd_element no_ip_ospf_authentication_key_addr_cmd__X;
    struct cmd_element no_ip_ospf_authentication_key_cmd__X;
    struct cmd_element no_ospf_retransmit_interval_cmd__X;
    struct cmd_element no_ip_ospf_message_digest_key_addr_cmd__X;
    struct cmd_element ospf_area_stub_no_summary_cmd__X;
    struct cmd_element debug_ospf_packet_send_recv_cmd__X;
    struct cmd_element no_ip_ospf_cost_addr_cmd__X;
    struct cmd_element no_debug_ospf_event_cmd__X;
    struct cmd_element ospf_default_information_originate_metric_cmd__X;
    struct cmd_element ospf_default_information_originate_metric_routemap_cmd__X;
    struct cmd_element no_ospf_area_import_list_cmd__X;
    struct cmd_element ip_ospf_message_digest_key_addr_cmd__X;
};

#define om__VAR  (__activeVars_ospfd->om__X)
#define OspfMplsTE__VAR  (__activeVars_ospfd->OspfMplsTE__X)

#define ospf_area_vlink_param1_cmd__VAR  (__activeVars_ospfd->ospf_area_vlink_param1_cmd__X)
#define no_ospf_area_vlink_param1_cmd__VAR  (__activeVars_ospfd->no_ospf_area_vlink_param1_cmd__X)
#define no_debug_ospf_zebra_sub_cmd__VAR  (__activeVars_ospfd->no_debug_ospf_zebra_sub_cmd__X)
#define show_ip_ospf_neighbor_int_cmd__VAR  (__activeVars_ospfd->show_ip_ospf_neighbor_int_cmd__X)
#define router_ospf_cmd__VAR  (__activeVars_ospfd->router_ospf_cmd__X)
#define ospf_transmit_delay_cmd__VAR  (__activeVars_ospfd->ospf_transmit_delay_cmd__X)
#define ospf_area_range_substitute_cmd__VAR  (__activeVars_ospfd->ospf_area_range_substitute_cmd__X)
#define ospf_distance_ospf_intra_inter_cmd__VAR  (__activeVars_ospfd->ospf_distance_ospf_intra_inter_cmd__X)
#define ospf_area_filter_list_cmd__VAR  (__activeVars_ospfd->ospf_area_filter_list_cmd__X)
#define no_ospf_network_area_cmd__VAR  (__activeVars_ospfd->no_ospf_network_area_cmd__X)
#define ospf_default_metric_cmd__VAR  (__activeVars_ospfd->ospf_default_metric_cmd__X)
#define ospf_distance_ospf_intra_external_inter_cmd__VAR  (__activeVars_ospfd->ospf_distance_ospf_intra_external_inter_cmd__X)
#define term_debug_ospf_ism__VAR  (__activeVars_ospfd->term_debug_ospf_ism__X)
#define conf_debug_ospf_ism__VAR  (__activeVars_ospfd->conf_debug_ospf_ism__X)
#define ospf_redistribute_source_type_routemap_cmd__VAR  (__activeVars_ospfd->ospf_redistribute_source_type_routemap_cmd__X)
#define no_ospf_refresh_timer_val_cmd__VAR  (__activeVars_ospfd->no_ospf_refresh_timer_val_cmd__X)
#define debug_ospf_zebra_cmd__VAR  (__activeVars_ospfd->debug_ospf_zebra_cmd__X)
#define no_ip_ospf_message_digest_key_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_message_digest_key_cmd__X)
#define ospf_default_information_originate_metric_type_routemap_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_metric_type_routemap_cmd__X)
#define show_ip_ospf_database_cmd__VAR  (__activeVars_ospfd->show_ip_ospf_database_cmd__X)
#define ospf_redistribute_source_metric_routemap_cmd__VAR  (__activeVars_ospfd->ospf_redistribute_source_metric_routemap_cmd__X)
#define ip_ospf_cost_cmd__VAR  (__activeVars_ospfd->ip_ospf_cost_cmd__X)
#define ospf_opaque_capable_cmd__VAR  (__activeVars_ospfd->ospf_opaque_capable_cmd__X)
#define no_ospf_auto_cost_reference_bandwidth_cmd__VAR  (__activeVars_ospfd->no_ospf_auto_cost_reference_bandwidth_cmd__X)
#define ospf_default_information_originate_routemap_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_routemap_cmd__X)
#define ospf_opaque_type10_funclist__VAR  (__activeVars_ospfd->ospf_opaque_type10_funclist__X)
#define ospf_area_vlink_authtype_args_authkey_cmd__VAR  (__activeVars_ospfd->ospf_area_vlink_authtype_args_authkey_cmd__X)
#define show_debugging_ospf_cmd__VAR  (__activeVars_ospfd->show_debugging_ospf_cmd__X)
#define ospf_area_nssa_cmd__VAR  (__activeVars_ospfd->ospf_area_nssa_cmd__X)
#define show_ip_ospf_neighbor_int_detail_cmd__VAR  (__activeVars_ospfd->show_ip_ospf_neighbor_int_detail_cmd__X)
#define no_ospf_area_filter_list_cmd__VAR  (__activeVars_ospfd->no_ospf_area_filter_list_cmd__X)
#define ospf_node__VAR  (__activeVars_ospfd->ospf_node__X)
#define ospf_neighbor_poll_interval_priority_cmd__VAR  (__activeVars_ospfd->ospf_neighbor_poll_interval_priority_cmd__X)
#define ospf_default_information_originate_always_metric_type_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_always_metric_type_cmd__X)
#define no_ospf_area_range_cmd__VAR  (__activeVars_ospfd->no_ospf_area_range_cmd__X)
#define no_ospf_network_cmd__VAR  (__activeVars_ospfd->no_ospf_network_cmd__X)
#define no_ospf_area_stub_cmd__VAR  (__activeVars_ospfd->no_ospf_area_stub_cmd__X)
#define ospf_distance_ospf_intra_inter_external_cmd__VAR  (__activeVars_ospfd->ospf_distance_ospf_intra_inter_external_cmd__X)
#define no_ospf_area_export_list_cmd__VAR  (__activeVars_ospfd->no_ospf_area_export_list_cmd__X)
#define ospf_area_shortcut_cmd__VAR  (__activeVars_ospfd->ospf_area_shortcut_cmd__X)
#define ospf_area_import_list_cmd__VAR  (__activeVars_ospfd->ospf_area_import_list_cmd__X)
#define debug_ospf_lsa_sub_cmd__VAR  (__activeVars_ospfd->debug_ospf_lsa_sub_cmd__X)
#define ip_ospf_hello_interval_cmd__VAR  (__activeVars_ospfd->ip_ospf_hello_interval_cmd__X)
#define debug_ospf_ism_cmd__VAR  (__activeVars_ospfd->debug_ospf_ism_cmd__X)
#define no_ip_ospf_dead_interval_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_dead_interval_cmd__X)
#define show_ip_ospf_neighbor_all_cmd__VAR  (__activeVars_ospfd->show_ip_ospf_neighbor_all_cmd__X)
#define ospf_default_information_originate_always_type_metric_routemap_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_always_type_metric_routemap_cmd__X)
#define no_ospf_distance_ospf_cmd__VAR  (__activeVars_ospfd->no_ospf_distance_ospf_cmd__X)
#define ospf_default_information_originate_always_type_routemap_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_always_type_routemap_cmd__X)
#define no_ospf_area_range_cost_cmd__VAR  (__activeVars_ospfd->no_ospf_area_range_cost_cmd__X)
#define ospf_opaque_type11_funclist__VAR  (__activeVars_ospfd->ospf_opaque_type11_funclist__X)
#define ospf_distance_ospf_external_intra_inter_cmd__VAR  (__activeVars_ospfd->ospf_distance_ospf_external_intra_inter_cmd__X)
#define ospf_default_information_originate_always_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_always_cmd__X)
#define conf_debug_ospf_zebra__VAR  (__activeVars_ospfd->conf_debug_ospf_zebra__X)
#define ospf_auto_cost_reference_bandwidth_cmd__VAR  (__activeVars_ospfd->ospf_auto_cost_reference_bandwidth_cmd__X)
#define no_ospf_area_vlink_md5_cmd__VAR  (__activeVars_ospfd->no_ospf_area_vlink_md5_cmd__X)
#define no_ospf_area_range_substitute_cmd__VAR  (__activeVars_ospfd->no_ospf_area_range_substitute_cmd__X)
#define no_ospf_neighbor_cmd__VAR  (__activeVars_ospfd->no_ospf_neighbor_cmd__X)
#define debug_ospf_zebra_sub_cmd__VAR  (__activeVars_ospfd->debug_ospf_zebra_sub_cmd__X)
#define no_ospf_area_range_advertise_cmd__VAR  (__activeVars_ospfd->no_ospf_area_range_advertise_cmd__X)
#define term_debug_ospf_zebra__VAR  (__activeVars_ospfd->term_debug_ospf_zebra__X)
#define no_ospf_rfc1583_flag_cmd__VAR  (__activeVars_ospfd->no_ospf_rfc1583_flag_cmd__X)
#define ospf_area_vlink_authtype_authkey_cmd__VAR  (__activeVars_ospfd->ospf_area_vlink_authtype_authkey_cmd__X)
#define ip_ospf_transmit_delay_addr_cmd__VAR  (__activeVars_ospfd->ip_ospf_transmit_delay_addr_cmd__X)
#define ospf_default_information_originate_always_type_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_always_type_cmd__X)
#define no_ospf_passive_interface_addr_cmd__VAR  (__activeVars_ospfd->no_ospf_passive_interface_addr_cmd__X)
#define no_debug_ospf_packet_send_recv_cmd__VAR  (__activeVars_ospfd->no_debug_ospf_packet_send_recv_cmd__X)
#define no_ospf_refresh_timer_cmd__VAR  (__activeVars_ospfd->no_ospf_refresh_timer_cmd__X)
#define no_ospf_router_id_cmd__VAR  (__activeVars_ospfd->no_ospf_router_id_cmd__X)
#define show_ip_ospf_cmd__VAR  (__activeVars_ospfd->show_ip_ospf_cmd__X)
#define ospf_retransmit_interval_cmd__VAR  (__activeVars_ospfd->ospf_retransmit_interval_cmd__X)
#define show_ip_ospf_interface_cmd__VAR  (__activeVars_ospfd->show_ip_ospf_interface_cmd__X)
#define ospf_opaque_type9_funclist__VAR  (__activeVars_ospfd->ospf_opaque_type9_funclist__X)
#define no_ospf_default_information_originate_cmd__VAR  (__activeVars_ospfd->no_ospf_default_information_originate_cmd__X)
#define show_ip_ospf_border_routers_cmd__VAR  (__activeVars_ospfd->show_ip_ospf_border_routers_cmd__X)
#define ospf_distance_cmd__VAR  (__activeVars_ospfd->ospf_distance_cmd__X)
#define ospf_apiserver_enable__VAR  (__activeVars_ospfd->ospf_apiserver_enable__X)
#define no_router_ospf_id_cmd__VAR  (__activeVars_ospfd->no_router_ospf_id_cmd__X)
#define no_ip_ospf_cost_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_cost_cmd__X)
#define show_ip_ospf_neighbor_detail_all_cmd__VAR  (__activeVars_ospfd->show_ip_ospf_neighbor_detail_all_cmd__X)
#define debug_ospf_packet_send_recv_detail_cmd__VAR  (__activeVars_ospfd->debug_ospf_packet_send_recv_detail_cmd__X)
#define show_ip_ospf_route_cmd__VAR  (__activeVars_ospfd->show_ip_ospf_route_cmd__X)
#define ospf_area_export_list_cmd__VAR  (__activeVars_ospfd->ospf_area_export_list_cmd__X)
#define ospf_area_authentication_cmd__VAR  (__activeVars_ospfd->ospf_area_authentication_cmd__X)
#define ospf_passive_interface_addr_cmd__VAR  (__activeVars_ospfd->ospf_passive_interface_addr_cmd__X)
#define ospf_distance_ospf_external_inter_intra_cmd__VAR  (__activeVars_ospfd->ospf_distance_ospf_external_inter_intra_cmd__X)
#define ip_ospf_hello_interval_addr_cmd__VAR  (__activeVars_ospfd->ip_ospf_hello_interval_addr_cmd__X)
#define debug_ospf_nsm_sub_cmd__VAR  (__activeVars_ospfd->debug_ospf_nsm_sub_cmd__X)
#define ospf_area_vlink_authtype_md5_cmd__VAR  (__activeVars_ospfd->ospf_area_vlink_authtype_md5_cmd__X)
#define ospf_area_nssa_translate_no_summary_cmd__VAR  (__activeVars_ospfd->ospf_area_nssa_translate_no_summary_cmd__X)
#define no_ospf_area_authentication_cmd__VAR  (__activeVars_ospfd->no_ospf_area_authentication_cmd__X)
#define no_ospf_redistribute_source_cmd__VAR  (__activeVars_ospfd->no_ospf_redistribute_source_cmd__X)
#define ospf_network_cmd__VAR  (__activeVars_ospfd->ospf_network_cmd__X)
#define no_ospf_passive_interface_cmd__VAR  (__activeVars_ospfd->no_ospf_passive_interface_cmd__X)
#define no_ospf_distance_cmd__VAR  (__activeVars_ospfd->no_ospf_distance_cmd__X)
#define no_router_ospf_cmd__VAR  (__activeVars_ospfd->no_router_ospf_cmd__X)
#define ip_ospf_transmit_delay_cmd__VAR  (__activeVars_ospfd->ip_ospf_transmit_delay_cmd__X)
#define ospf_distance_source_access_list_cmd__VAR  (__activeVars_ospfd->ospf_distance_source_access_list_cmd__X)
#define ospf_distance_ospf_inter_cmd__VAR  (__activeVars_ospfd->ospf_distance_ospf_inter_cmd__X)
#define show_ip_ospf_database_type_id_self_cmd__VAR  (__activeVars_ospfd->show_ip_ospf_database_type_id_self_cmd__X)
#define ospf_redistribute_source_type_metric_cmd__VAR  (__activeVars_ospfd->ospf_redistribute_source_type_metric_cmd__X)
#define ospf_distance_ospf_external_cmd__VAR  (__activeVars_ospfd->ospf_distance_ospf_external_cmd__X)
#define ospf_redistribute_source_metric_cmd__VAR  (__activeVars_ospfd->ospf_redistribute_source_metric_cmd__X)
#define no_ospf_neighbor_priority_pollinterval_cmd__VAR  (__activeVars_ospfd->no_ospf_neighbor_priority_pollinterval_cmd__X)
#define ospf_neighbor_priority_cmd__VAR  (__activeVars_ospfd->ospf_neighbor_priority_cmd__X)
#define no_ospf_default_metric_val_cmd__VAR  (__activeVars_ospfd->no_ospf_default_metric_val_cmd__X)
#define ospf_default_information_originate_always_routemap_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_always_routemap_cmd__X)
#define ospf_area_vlink_authtype_cmd__VAR  (__activeVars_ospfd->ospf_area_vlink_authtype_cmd__X)
#define ospf_passive_interface_cmd__VAR  (__activeVars_ospfd->ospf_passive_interface_cmd__X)
#define ospf_area_vlink_authtype_args_md5_cmd__VAR  (__activeVars_ospfd->ospf_area_vlink_authtype_args_md5_cmd__X)
#define ospf_cost_cmd__VAR  (__activeVars_ospfd->ospf_cost_cmd__X)
#define ospf_distance_ospf_inter_intra_external_cmd__VAR  (__activeVars_ospfd->ospf_distance_ospf_inter_intra_external_cmd__X)
#define ospf_distance_source_cmd__VAR  (__activeVars_ospfd->ospf_distance_source_cmd__X)
#define no_ospf_authentication_key_cmd__VAR  (__activeVars_ospfd->no_ospf_authentication_key_cmd__X)
#define ospf_area_range_not_advertise_cmd__VAR  (__activeVars_ospfd->ospf_area_range_not_advertise_cmd__X)
#define ospf_redistribute_source_metric_type_cmd__VAR  (__activeVars_ospfd->ospf_redistribute_source_metric_type_cmd__X)
#define no_ip_ospf_priority_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_priority_cmd__X)
#define ospf_abr_type_cmd__VAR  (__activeVars_ospfd->ospf_abr_type_cmd__X)
#define ospf_redistribute_source_metric_type_routemap_cmd__VAR  (__activeVars_ospfd->ospf_redistribute_source_metric_type_routemap_cmd__X)
#define no_debug_ospf_nsm_cmd__VAR  (__activeVars_ospfd->no_debug_ospf_nsm_cmd__X)
#define ospf_redistribute_source_type_cmd__VAR  (__activeVars_ospfd->ospf_redistribute_source_type_cmd__X)
#define ospf_neighbor_poll_interval_cmd__VAR  (__activeVars_ospfd->ospf_neighbor_poll_interval_cmd__X)
#define no_ospf_opaque_capable_cmd__VAR  (__activeVars_ospfd->no_ospf_opaque_capable_cmd__X)
#define ospf_priority_cmd__VAR  (__activeVars_ospfd->ospf_priority_cmd__X)
#define ospf_hello_interval_cmd__VAR  (__activeVars_ospfd->ospf_hello_interval_cmd__X)
#define ospf_opaque_wildcard_funclist__VAR  (__activeVars_ospfd->ospf_opaque_wildcard_funclist__X)
#define show_ip_ospf_neighbor_cmd__VAR  (__activeVars_ospfd->show_ip_ospf_neighbor_cmd__X)
#define show_ip_ospf_database_type_id_adv_router_cmd__VAR  (__activeVars_ospfd->show_ip_ospf_database_type_id_adv_router_cmd__X)
#define no_ip_ospf_authentication_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_authentication_cmd__X)
#define ospf_rfc1583_flag_cmd__VAR  (__activeVars_ospfd->ospf_rfc1583_flag_cmd__X)
#define conf_debug_ospf_event__VAR  (__activeVars_ospfd->conf_debug_ospf_event__X)
#define ip_ospf_priority_cmd__VAR  (__activeVars_ospfd->ip_ospf_priority_cmd__X)
#define ospf_area_vlink_param4_cmd__VAR  (__activeVars_ospfd->ospf_area_vlink_param4_cmd__X)
#define conf_debug_ospf_packet__VAR  (__activeVars_ospfd->conf_debug_ospf_packet__X)
#define debug_ospf_lsa_cmd__VAR  (__activeVars_ospfd->debug_ospf_lsa_cmd__X)
#define conf_debug_ospf_nssa__VAR  (__activeVars_ospfd->conf_debug_ospf_nssa__X)
#define ospf_distribute_list_out_cmd__VAR  (__activeVars_ospfd->ospf_distribute_list_out_cmd__X)
#define no_ospf_distance_source_access_list_cmd__VAR  (__activeVars_ospfd->no_ospf_distance_source_access_list_cmd__X)
#define ospf_refresh_timer_cmd__VAR  (__activeVars_ospfd->ospf_refresh_timer_cmd__X)
#define ospf_area_vlink_authtype_args_cmd__VAR  (__activeVars_ospfd->ospf_area_vlink_authtype_args_cmd__X)
#define show_ip_ospf_database_type_adv_router_cmd__VAR  (__activeVars_ospfd->show_ip_ospf_database_type_adv_router_cmd__X)
#define no_ip_ospf_authentication_addr_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_authentication_addr_cmd__X)
#define no_ospf_area_shortcut_cmd__VAR  (__activeVars_ospfd->no_ospf_area_shortcut_cmd__X)
#define no_ip_ospf_transmit_delay_addr_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_transmit_delay_addr_cmd__X)
#define ospf_area_range_advertise_cmd__VAR  (__activeVars_ospfd->ospf_area_range_advertise_cmd__X)
#define no_ip_ospf_transmit_delay_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_transmit_delay_cmd__X)
#define ospf_default_information_originate_type_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_type_cmd__X)
#define ospf_distance_ospf_intra_external_cmd__VAR  (__activeVars_ospfd->ospf_distance_ospf_intra_external_cmd__X)
#define ip_ospf_dead_interval_addr_cmd__VAR  (__activeVars_ospfd->ip_ospf_dead_interval_addr_cmd__X)
#define ospf_default_information_originate_type_routemap_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_type_routemap_cmd__X)
#define no_ip_ospf_priority_addr_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_priority_addr_cmd__X)
#define no_debug_ospf_ism_cmd__VAR  (__activeVars_ospfd->no_debug_ospf_ism_cmd__X)
#define no_ospf_neighbor_poll_interval_cmd__VAR  (__activeVars_ospfd->no_ospf_neighbor_poll_interval_cmd__X)
#define no_ospf_distance_source_cmd__VAR  (__activeVars_ospfd->no_ospf_distance_source_cmd__X)
#define ospf_area_default_cost_cmd__VAR  (__activeVars_ospfd->ospf_area_default_cost_cmd__X)
#define no_ospf_area_nssa_cmd__VAR  (__activeVars_ospfd->no_ospf_area_nssa_cmd__X)
#define no_ospf_hello_interval_cmd__VAR  (__activeVars_ospfd->no_ospf_hello_interval_cmd__X)
#define ospf_router_id_cmd__VAR  (__activeVars_ospfd->ospf_router_id_cmd__X)
#define ospf_area_authentication_message_digest_cmd__VAR  (__activeVars_ospfd->ospf_area_authentication_message_digest_cmd__X)
#define ospf_distance_ospf_inter_external_intra_cmd__VAR  (__activeVars_ospfd->ospf_distance_ospf_inter_external_intra_cmd__X)
#define no_ospf_transmit_delay_cmd__VAR  (__activeVars_ospfd->no_ospf_transmit_delay_cmd__X)
#define no_ospf_message_digest_key_cmd__VAR  (__activeVars_ospfd->no_ospf_message_digest_key_cmd__X)
#define ospf_message_digest_key_cmd__VAR  (__activeVars_ospfd->ospf_message_digest_key_cmd__X)
#define ip_ospf_authentication_cmd__VAR  (__activeVars_ospfd->ip_ospf_authentication_cmd__X)
#define no_ospf_abr_type_cmd__VAR  (__activeVars_ospfd->no_ospf_abr_type_cmd__X)
#define show_ip_ospf_database_type_self_cmd__VAR  (__activeVars_ospfd->show_ip_ospf_database_type_self_cmd__X)
#define show_ip_ospf_database_type_cmd__VAR  (__activeVars_ospfd->show_ip_ospf_database_type_cmd__X)
#define conf_debug_ospf_nsm__VAR  (__activeVars_ospfd->conf_debug_ospf_nsm__X)
#define no_ospf_neighbor_priority_cmd__VAR  (__activeVars_ospfd->no_ospf_neighbor_priority_cmd__X)
#define no_ospf_area_vlink_authtype_cmd__VAR  (__activeVars_ospfd->no_ospf_area_vlink_authtype_cmd__X)
#define ip_ospf_cost_addr_cmd__VAR  (__activeVars_ospfd->ip_ospf_cost_addr_cmd__X)
#define ospf_distance_ospf_intra_cmd__VAR  (__activeVars_ospfd->ospf_distance_ospf_intra_cmd__X)
#define ospf_network_area_cmd__VAR  (__activeVars_ospfd->ospf_network_area_cmd__X)
#define no_debug_ospf_lsa_sub_cmd__VAR  (__activeVars_ospfd->no_debug_ospf_lsa_sub_cmd__X)
#define ip_ospf_message_digest_key_cmd__VAR  (__activeVars_ospfd->ip_ospf_message_digest_key_cmd__X)
#define ospf_compatible_rfc1583_cmd__VAR  (__activeVars_ospfd->ospf_compatible_rfc1583_cmd__X)
#define ospf_area_vlink_authkey_cmd__VAR  (__activeVars_ospfd->ospf_area_vlink_authkey_cmd__X)
#define ip_ospf_authentication_key_addr_cmd__VAR  (__activeVars_ospfd->ip_ospf_authentication_key_addr_cmd__X)
#define ip_ospf_dead_interval_cmd__VAR  (__activeVars_ospfd->ip_ospf_dead_interval_cmd__X)
#define ospf_area_vlink_cmd__VAR  (__activeVars_ospfd->ospf_area_vlink_cmd__X)
#define ospf_neighbor_priority_poll_interval_cmd__VAR  (__activeVars_ospfd->ospf_neighbor_priority_poll_interval_cmd__X)
#define ospf_distance_ospf_external_intra_cmd__VAR  (__activeVars_ospfd->ospf_distance_ospf_external_intra_cmd__X)
#define no_debug_ospf_lsa_cmd__VAR  (__activeVars_ospfd->no_debug_ospf_lsa_cmd__X)
#define no_ospf_area_vlink_authkey_cmd__VAR  (__activeVars_ospfd->no_ospf_area_vlink_authkey_cmd__X)
#define term_debug_ospf_event__VAR  (__activeVars_ospfd->term_debug_ospf_event__X)
#define no_ip_ospf_dead_interval_addr_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_dead_interval_addr_cmd__X)
#define no_ip_ospf_hello_interval_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_hello_interval_cmd__X)
#define no_ospf_area_nssa_no_summary_cmd__VAR  (__activeVars_ospfd->no_ospf_area_nssa_no_summary_cmd__X)
#define ospf_area_range_cost_cmd__VAR  (__activeVars_ospfd->ospf_area_range_cost_cmd__X)
#define term_debug_ospf_nssa__VAR  (__activeVars_ospfd->term_debug_ospf_nssa__X)
#define no_ospf_area_vlink_param2_cmd__VAR  (__activeVars_ospfd->no_ospf_area_vlink_param2_cmd__X)
#define no_ospf_distribute_list_out_cmd__VAR  (__activeVars_ospfd->no_ospf_distribute_list_out_cmd__X)
#define no_ip_ospf_retransmit_interval_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_retransmit_interval_cmd__X)
#define debug_ospf_packet_all_cmd__VAR  (__activeVars_ospfd->debug_ospf_packet_all_cmd__X)
#define no_ospf_timers_spf_cmd__VAR  (__activeVars_ospfd->no_ospf_timers_spf_cmd__X)
#define ospf_default_information_originate_type_metric_routemap_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_type_metric_routemap_cmd__X)
#define ospf_area_nssa_translate_cmd__VAR  (__activeVars_ospfd->ospf_area_nssa_translate_cmd__X)
#define ospf_dead_interval_cmd__VAR  (__activeVars_ospfd->ospf_dead_interval_cmd__X)
#define ospf_area_stub_cmd__VAR  (__activeVars_ospfd->ospf_area_stub_cmd__X)
#define ospf_area_range_advertise_cost_cmd__VAR  (__activeVars_ospfd->ospf_area_range_advertise_cost_cmd__X)
#define ospf_area_vlink_param3_cmd__VAR  (__activeVars_ospfd->ospf_area_vlink_param3_cmd__X)
#define ospf_default_information_originate_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_cmd__X)
#define ospf_area_vlink_md5_cmd__VAR  (__activeVars_ospfd->ospf_area_vlink_md5_cmd__X)
#define term_debug_ospf_nsm__VAR  (__activeVars_ospfd->term_debug_ospf_nsm__X)
#define ospf_redistribute_source_routemap_cmd__VAR  (__activeVars_ospfd->ospf_redistribute_source_routemap_cmd__X)
#define ospf_master__VAR  (__activeVars_ospfd->ospf_master__X)
#define ospf_redistribute_source_type_metric_routemap_cmd__VAR  (__activeVars_ospfd->ospf_redistribute_source_type_metric_routemap_cmd__X)
#define ip_ospf_authentication_args_addr_cmd__VAR  (__activeVars_ospfd->ip_ospf_authentication_args_addr_cmd__X)
#define no_ospf_area_stub_no_summary_cmd__VAR  (__activeVars_ospfd->no_ospf_area_stub_no_summary_cmd__X)
#define ospf_default_information_originate_always_metric_routemap_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_always_metric_routemap_cmd__X)
#define show_ip_ospf_database_type_id_cmd__VAR  (__activeVars_ospfd->show_ip_ospf_database_type_id_cmd__X)
#define no_ospf_area_vlink_authtype_authkey_cmd__VAR  (__activeVars_ospfd->no_ospf_area_vlink_authtype_authkey_cmd__X)
#define term_debug_ospf_lsa__VAR  (__activeVars_ospfd->term_debug_ospf_lsa__X)
#define no_ip_ospf_retransmit_interval_addr_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_retransmit_interval_addr_cmd__X)
#define router_ospf_id_cmd__VAR  (__activeVars_ospfd->router_ospf_id_cmd__X)
#define no_ospf_area_vlink_param4_cmd__VAR  (__activeVars_ospfd->no_ospf_area_vlink_param4_cmd__X)
#define ospf_default_information_originate_metric_type_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_metric_type_cmd__X)
#define ospf_default_information_originate_type_metric_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_type_metric_cmd__X)
#define no_ospf_area_default_cost_cmd__VAR  (__activeVars_ospfd->no_ospf_area_default_cost_cmd__X)
#define term_debug_ospf_packet__VAR  (__activeVars_ospfd->term_debug_ospf_packet__X)
#define ospf_authentication_key_cmd__VAR  (__activeVars_ospfd->ospf_authentication_key_cmd__X)
#define no_debug_ospf_packet_all_cmd__VAR  (__activeVars_ospfd->no_debug_ospf_packet_all_cmd__X)
#define ip_ospf_network_cmd__VAR  (__activeVars_ospfd->ip_ospf_network_cmd__X)
#define no_ospf_area_vlink_cmd__VAR  (__activeVars_ospfd->no_ospf_area_vlink_cmd__X)
#define no_ospf_area_range_advertise_cost_cmd__VAR  (__activeVars_ospfd->no_ospf_area_range_advertise_cost_cmd__X)
#define ospf_area_type_msg_max__VAR  (__activeVars_ospfd->ospf_area_type_msg_max__X)
#define ip_ospf_retransmit_interval_addr_cmd__VAR  (__activeVars_ospfd->ip_ospf_retransmit_interval_addr_cmd__X)
#define show_ip_ospf_neighbor_detail_cmd__VAR  (__activeVars_ospfd->show_ip_ospf_neighbor_detail_cmd__X)
#define no_ospf_area_vlink_authtype_md5_cmd__VAR  (__activeVars_ospfd->no_ospf_area_vlink_authtype_md5_cmd__X)
#define no_ospf_cost_cmd__VAR  (__activeVars_ospfd->no_ospf_cost_cmd__X)
#define debug_ospf_nssa_cmd__VAR  (__activeVars_ospfd->debug_ospf_nssa_cmd__X)
#define debug_ospf_event_cmd__VAR  (__activeVars_ospfd->debug_ospf_event_cmd__X)
#define no_ip_ospf_hello_interval_addr_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_hello_interval_addr_cmd__X)
#define no_debug_ospf_packet_send_recv_detail_cmd__VAR  (__activeVars_ospfd->no_debug_ospf_packet_send_recv_detail_cmd__X)
#define debug_ospf_ism_sub_cmd__VAR  (__activeVars_ospfd->debug_ospf_ism_sub_cmd__X)
#define ospf_area_range_cmd__VAR  (__activeVars_ospfd->ospf_area_range_cmd__X)
#define ip_ospf_retransmit_interval_cmd__VAR  (__activeVars_ospfd->ip_ospf_retransmit_interval_cmd__X)
#define ospf_area_nssa_no_summary_cmd__VAR  (__activeVars_ospfd->ospf_area_nssa_no_summary_cmd__X)
#define ip_ospf_authentication_key_cmd__VAR  (__activeVars_ospfd->ip_ospf_authentication_key_cmd__X)
#define no_ospf_dead_interval_cmd__VAR  (__activeVars_ospfd->no_ospf_dead_interval_cmd__X)
#define ospf_default_information_originate_always_metric_type_routemap_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_always_metric_type_routemap_cmd__X)
#define ospf_area_vlink_param2_cmd__VAR  (__activeVars_ospfd->ospf_area_vlink_param2_cmd__X)
#define no_debug_ospf_ism_sub_cmd__VAR  (__activeVars_ospfd->no_debug_ospf_ism_sub_cmd__X)
#define debug_ospf_nsm_cmd__VAR  (__activeVars_ospfd->debug_ospf_nsm_cmd__X)
#define show_ip_ospf_neighbor_id_cmd__VAR  (__activeVars_ospfd->show_ip_ospf_neighbor_id_cmd__X)
#define ospf_distance_ospf_external_inter_cmd__VAR  (__activeVars_ospfd->ospf_distance_ospf_external_inter_cmd__X)
#define conf_debug_ospf_lsa__VAR  (__activeVars_ospfd->conf_debug_ospf_lsa__X)
#define no_ospf_compatible_rfc1583_cmd__VAR  (__activeVars_ospfd->no_ospf_compatible_rfc1583_cmd__X)
#define ospf_default_information_originate_always_metric_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_always_metric_cmd__X)
#define ip_ospf_authentication_addr_cmd__VAR  (__activeVars_ospfd->ip_ospf_authentication_addr_cmd__X)
#define ip_ospf_authentication_args_cmd__VAR  (__activeVars_ospfd->ip_ospf_authentication_args_cmd__X)
#define no_debug_ospf_nssa_cmd__VAR  (__activeVars_ospfd->no_debug_ospf_nssa_cmd__X)
#define no_ip_ospf_network_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_network_cmd__X)
#define ospf_neighbor_cmd__VAR  (__activeVars_ospfd->ospf_neighbor_cmd__X)
#define no_ospf_area_vlink_param3_cmd__VAR  (__activeVars_ospfd->no_ospf_area_vlink_param3_cmd__X)
#define no_ospf_default_metric_cmd__VAR  (__activeVars_ospfd->no_ospf_default_metric_cmd__X)
#define ospf_distance_ospf_inter_external_cmd__VAR  (__activeVars_ospfd->ospf_distance_ospf_inter_external_cmd__X)
#define no_ospf_priority_cmd__VAR  (__activeVars_ospfd->no_ospf_priority_cmd__X)
#define no_debug_ospf_nsm_sub_cmd__VAR  (__activeVars_ospfd->no_debug_ospf_nsm_sub_cmd__X)
#define ospf_redistribute_source_cmd__VAR  (__activeVars_ospfd->ospf_redistribute_source_cmd__X)
#define ospf_default_information_originate_always_type_metric_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_always_type_metric_cmd__X)
#define ip_ospf_priority_addr_cmd__VAR  (__activeVars_ospfd->ip_ospf_priority_addr_cmd__X)
#define no_debug_ospf_zebra_cmd__VAR  (__activeVars_ospfd->no_debug_ospf_zebra_cmd__X)
#define ospf_distance_ospf_inter_intra_cmd__VAR  (__activeVars_ospfd->ospf_distance_ospf_inter_intra_cmd__X)
#define ospf_timers_spf_cmd__VAR  (__activeVars_ospfd->ospf_timers_spf_cmd__X)
#define no_ip_ospf_authentication_key_addr_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_authentication_key_addr_cmd__X)
#define no_ip_ospf_authentication_key_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_authentication_key_cmd__X)
#define no_ospf_retransmit_interval_cmd__VAR  (__activeVars_ospfd->no_ospf_retransmit_interval_cmd__X)
#define no_ip_ospf_message_digest_key_addr_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_message_digest_key_addr_cmd__X)
#define ospf_area_stub_no_summary_cmd__VAR  (__activeVars_ospfd->ospf_area_stub_no_summary_cmd__X)
#define debug_ospf_packet_send_recv_cmd__VAR  (__activeVars_ospfd->debug_ospf_packet_send_recv_cmd__X)
#define no_ip_ospf_cost_addr_cmd__VAR  (__activeVars_ospfd->no_ip_ospf_cost_addr_cmd__X)
#define no_debug_ospf_event_cmd__VAR  (__activeVars_ospfd->no_debug_ospf_event_cmd__X)
#define ospf_default_information_originate_metric_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_metric_cmd__X)
#define ospf_default_information_originate_metric_routemap_cmd__VAR  (__activeVars_ospfd->ospf_default_information_originate_metric_routemap_cmd__X)
#define no_ospf_area_import_list_cmd__VAR  (__activeVars_ospfd->no_ospf_area_import_list_cmd__X)
#define ip_ospf_message_digest_key_addr_cmd__VAR  (__activeVars_ospfd->ip_ospf_message_digest_key_addr_cmd__X)

#endif