
#include "globalvars_ospfd.h"

struct Globalvars_ospfd * activeVars_ospfd;

struct GlobalVars_ospfd * GlobalVars_createActiveSet_ospfd()
{
    struct GlobalVars_ospfd * ptr = (struct GlobalVars_ospfd *)malloc(sizeof(struct GlobalVars_ospfd));
    memset(ptr, 0, sizeof(struct GlobalVars_ospfd));
    return ptr;
}

extern struct cmd_element show_ip_ospf_route_cmd_ospfd;
extern struct cmd_element ospf_area_vlink_param1_cmd_ospfd;
extern struct cmd_element no_ospf_area_vlink_param1_cmd_ospfd;
extern struct cmd_element ospf_area_export_list_cmd_ospfd;
extern struct cmd_element no_debug_ospf_zebra_sub_cmd_ospfd;
extern struct cmd_element ospf_area_authentication_cmd_ospfd;
extern struct cmd_element no_capability_opaque_cmd_ospfd;
extern struct cmd_element mpls_te_link_max_rsv_bw_cmd_ospfd;
extern struct cmd_element ospf_passive_interface_addr_cmd_ospfd;
extern struct cmd_element no_ip_ospf_retransmit_interval_addr_cmd_ospfd;
extern struct cmd_element show_ip_ospf_neighbor_int_cmd_ospfd;
extern struct cmd_element ospf_distance_ospf_external_inter_intra_cmd_ospfd;
extern struct cmd_element router_ospf_id_cmd_ospfd;
extern struct cmd_element ip_ospf_hello_interval_addr_cmd_ospfd;
extern struct cmd_element no_ospf_area_vlink_param4_cmd_ospfd;
extern struct cmd_element ospf_area_range_advertise_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_metric_type_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_type_metric_cmd_ospfd;
extern struct cmd_element router_ospf_cmd_ospfd;
extern struct cmd_element ospf_transmit_delay_cmd_ospfd;
extern struct cmd_element no_ospf_area_default_cost_cmd_ospfd;
extern struct cmd_element ospf_area_range_substitute_cmd_ospfd;
extern struct cmd_element set_metric_type_cmd_ospfd;
extern struct cmd_element no_mpls_te_cmd_ospfd;
extern struct cmd_element no_match_ip_address_prefix_list_val_cmd_ospfd;
extern struct cmd_element capability_opaque_cmd_ospfd;
extern struct cmd_element no_ip_ospf_transmit_delay_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_type_cmd_ospfd;
extern struct cmd_element ospf_authentication_key_cmd_ospfd;
extern struct cmd_element ospf_distance_ospf_intra_inter_cmd_ospfd;
extern struct cmd_element no_debug_ospf_packet_all_cmd_ospfd;
extern struct cmd_element ospf_distance_ospf_intra_external_cmd_ospfd;
extern struct cmd_element set_metric_cmd_ospfd;
extern struct cmd_element debug_ospf_nsm_sub_cmd_ospfd;
extern struct cmd_element ip_ospf_dead_interval_addr_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_type_routemap_cmd_ospfd;
extern struct cmd_element ip_ospf_network_cmd_ospfd;
extern struct cmd_element ospf_area_filter_list_cmd_ospfd;
extern struct route_map_rule_cmd route_set_metric_cmd_ospfd;
extern struct cmd_element ospf_area_vlink_authtype_md5_cmd_ospfd;
extern struct cmd_element ospf_area_nssa_translate_no_summary_cmd_ospfd;
extern struct cmd_element no_ip_ospf_priority_addr_cmd_ospfd;
extern struct cmd_element no_ospf_network_area_cmd_ospfd;
extern struct cmd_element ospf_default_metric_cmd_ospfd;
extern struct cmd_element ospf_distance_ospf_intra_external_inter_cmd_ospfd;
extern struct cmd_element no_debug_ospf_ism_cmd_ospfd;
extern struct cmd_element no_ospf_neighbor_poll_interval_cmd_ospfd;
extern struct cmd_element no_ospf_area_vlink_cmd_ospfd;
extern struct route_map_rule_cmd route_match_interface_cmd_ospfd;
extern struct cmd_element no_ospf_area_authentication_cmd_ospfd;
extern struct cmd_element no_ospf_area_range_advertise_cost_cmd_ospfd;
extern struct cmd_element no_ospf_redistribute_source_cmd_ospfd;
extern struct cmd_element ospf_network_cmd_ospfd;
extern struct cmd_element ospf_redistribute_source_type_routemap_cmd_ospfd;
extern struct cmd_element no_ospf_refresh_timer_val_cmd_ospfd;
extern struct cmd_element no_match_ip_address_val_cmd_ospfd;
extern struct cmd_element debug_ospf_zebra_cmd_ospfd;
extern struct cmd_element no_ospf_distance_source_cmd_ospfd;
extern struct cmd_element no_ospf_passive_interface_cmd_ospfd;
extern struct cmd_element ospf_area_default_cost_cmd_ospfd;
extern struct cmd_element no_ospf_distance_cmd_ospfd;
extern struct cmd_element ip_ospf_retransmit_interval_addr_cmd_ospfd;
extern struct cmd_element show_ip_ospf_neighbor_detail_cmd_ospfd;
extern struct cmd_element mpls_te_cmd_ospfd;
extern struct cmd_element no_ip_ospf_message_digest_key_cmd_ospfd;
extern struct cmd_element no_ospf_area_nssa_cmd_ospfd;
extern struct cmd_element no_ospf_area_vlink_authtype_md5_cmd_ospfd;
extern struct cmd_element no_router_ospf_cmd_ospfd;
extern struct cmd_element ip_ospf_transmit_delay_cmd_ospfd;
extern struct cmd_element show_mpls_te_router_cmd_ospfd;
extern struct cmd_element no_ospf_cost_cmd_ospfd;
extern struct cmd_element debug_ospf_nssa_cmd_ospfd;
extern struct cmd_element no_match_interface_val_cmd_ospfd;
extern struct route_map_rule_cmd route_match_ip_address_prefix_list_cmd_ospfd;
extern struct cmd_element debug_ospf_event_cmd_ospfd;
extern struct cmd_element no_ip_ospf_hello_interval_addr_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_metric_type_routemap_cmd_ospfd;
extern struct cmd_element ospf_distance_source_access_list_cmd_ospfd;
extern struct cmd_element show_ip_ospf_database_cmd_ospfd;
extern struct cmd_element no_ospf_hello_interval_cmd_ospfd;
extern struct cmd_element ospf_distance_ospf_inter_cmd_ospfd;
extern struct cmd_element ospf_redistribute_source_metric_routemap_cmd_ospfd;
extern struct cmd_element ospf_router_id_cmd_ospfd;
extern struct cmd_element ospf_area_authentication_message_digest_cmd_ospfd;
extern struct cmd_element no_set_metric_cmd_ospfd;
extern struct cmd_element ip_ospf_cost_cmd_ospfd;
extern struct cmd_element no_match_interface_cmd_ospfd;
extern struct cmd_element no_debug_ospf_packet_send_recv_detail_cmd_ospfd;
extern struct cmd_element no_set_metric_type_val_cmd_ospfd;
extern struct cmd_element debug_ospf_ism_sub_cmd_ospfd;
extern struct cmd_element ospf_distance_ospf_inter_external_intra_cmd_ospfd;
extern struct cmd_element ospf_opaque_capable_cmd_ospfd;
extern struct cmd_element ospf_area_range_cmd_ospfd;
extern struct cmd_element no_ospf_transmit_delay_cmd_ospfd;
extern struct cmd_element ip_ospf_retransmit_interval_cmd_ospfd;
extern struct cmd_element show_ip_ospf_database_type_id_self_cmd_ospfd;
extern struct cmd_element no_ospf_auto_cost_reference_bandwidth_cmd_ospfd;
extern struct cmd_element ospf_area_nssa_no_summary_cmd_ospfd;
extern struct cmd_element mpls_te_link_unrsv_bw_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_routemap_cmd_ospfd;
extern struct cmd_element ospf_redistribute_source_type_metric_cmd_ospfd;
extern struct cmd_element ospf_distance_ospf_external_cmd_ospfd;
extern struct cmd_element no_ospf_message_digest_key_cmd_ospfd;
extern struct cmd_element mpls_te_link_rsc_clsclr_cmd_ospfd;
extern struct cmd_element ospf_message_digest_key_cmd_ospfd;
extern struct cmd_element ospf_redistribute_source_metric_cmd_ospfd;
extern struct cmd_element ip_ospf_authentication_key_cmd_ospfd;
extern struct cmd_element no_ospf_neighbor_priority_pollinterval_cmd_ospfd;
extern struct route_map_rule_cmd route_set_metric_type_cmd_ospfd;
extern struct cmd_element no_ospf_dead_interval_cmd_ospfd;
extern struct cmd_element mpls_te_link_maxbw_cmd_ospfd;
extern struct cmd_element ip_ospf_authentication_cmd_ospfd;
extern struct cmd_element ospf_neighbor_priority_cmd_ospfd;
extern struct cmd_element no_ospf_abr_type_cmd_ospfd;
extern struct cmd_element show_ip_ospf_database_type_self_cmd_ospfd;
extern struct cmd_element show_ip_ospf_database_type_cmd_ospfd;
extern struct cmd_element no_match_ip_next_hop_prefix_list_val_cmd_ospfd;
extern struct cmd_element ospf_area_vlink_authtype_args_authkey_cmd_ospfd;
extern struct cmd_element no_ospf_default_metric_val_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_always_metric_type_routemap_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_always_routemap_cmd_ospfd;
extern struct cmd_element ospf_area_vlink_param2_cmd_ospfd;
extern struct cmd_element no_ospf_neighbor_priority_cmd_ospfd;
extern struct cmd_element no_match_ip_nexthop_val_cmd_ospfd;
extern struct cmd_element show_debugging_ospf_cmd_ospfd;
extern struct cmd_element ospf_area_nssa_cmd_ospfd;
extern struct cmd_element no_debug_ospf_ism_sub_cmd_ospfd;
extern struct cmd_element show_ip_ospf_neighbor_int_detail_cmd_ospfd;
extern struct cmd_element debug_ospf_nsm_cmd_ospfd;
extern struct cmd_element ospf_area_vlink_authtype_cmd_ospfd;
extern struct cmd_element no_ospf_area_filter_list_cmd_ospfd;
extern struct cmd_element show_ip_ospf_neighbor_id_cmd_ospfd;
extern struct cmd_element mpls_te_link_metric_cmd_ospfd;
extern struct cmd_element ospf_passive_interface_cmd_ospfd;
extern struct cmd_element ospf_neighbor_poll_interval_priority_cmd_ospfd;
extern struct cmd_element ospf_distance_ospf_external_inter_cmd_ospfd;
extern struct cmd_element ospf_area_vlink_authtype_args_md5_cmd_ospfd;
extern struct cmd_element no_ospf_area_vlink_authtype_cmd_ospfd;
extern struct cmd_element ip_ospf_cost_addr_cmd_ospfd;
extern struct cmd_element no_ospf_compatible_rfc1583_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_always_metric_type_cmd_ospfd;
extern struct cmd_element no_ospf_area_range_cmd_ospfd;
extern struct cmd_element no_ospf_network_cmd_ospfd;
extern struct cmd_element ospf_cost_cmd_ospfd;
extern struct cmd_element ospf_distance_ospf_intra_cmd_ospfd;
extern struct cmd_element no_ospf_area_stub_cmd_ospfd;
extern struct cmd_element ospf_network_area_cmd_ospfd;
extern struct cmd_element match_ip_address_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_always_metric_cmd_ospfd;
extern struct cmd_element ospf_distance_ospf_intra_inter_external_cmd_ospfd;
extern struct cmd_element no_ospf_area_export_list_cmd_ospfd;
extern struct cmd_element no_debug_ospf_lsa_sub_cmd_ospfd;
extern struct cmd_element ip_ospf_message_digest_key_cmd_ospfd;
extern struct cmd_element ospf_area_shortcut_cmd_ospfd;
extern struct cmd_element no_set_metric_val_cmd_ospfd;
extern struct cmd_element ospf_area_import_list_cmd_ospfd;
extern struct cmd_element debug_ospf_lsa_sub_cmd_ospfd;
extern struct cmd_element ospf_area_vlink_authkey_cmd_ospfd;
extern struct cmd_element ospf_compatible_rfc1583_cmd_ospfd;
extern struct cmd_element ospf_distance_ospf_inter_intra_external_cmd_ospfd;
extern struct cmd_element ip_ospf_authentication_addr_cmd_ospfd;
extern struct cmd_element ospf_distance_source_cmd_ospfd;
extern struct cmd_element no_ospf_authentication_key_cmd_ospfd;
extern struct cmd_element ospf_area_range_not_advertise_cmd_ospfd;
extern struct cmd_element ip_ospf_hello_interval_cmd_ospfd;
extern struct cmd_element ospf_redistribute_source_metric_type_cmd_ospfd;
extern struct cmd_element ip_ospf_authentication_key_addr_cmd_ospfd;
extern struct cmd_element ip_ospf_dead_interval_cmd_ospfd;
extern struct cmd_element ip_ospf_authentication_args_cmd_ospfd;
extern struct cmd_element debug_ospf_ism_cmd_ospfd;
extern struct cmd_element ospf_area_vlink_cmd_ospfd;
extern struct cmd_element no_match_ip_address_cmd_ospfd;
extern struct cmd_element no_ip_ospf_priority_cmd_ospfd;
extern struct cmd_element no_ip_ospf_dead_interval_cmd_ospfd;
extern struct cmd_element ospf_neighbor_priority_poll_interval_cmd_ospfd;
extern struct cmd_element show_ip_ospf_neighbor_all_cmd_ospfd;
extern struct cmd_element no_debug_ospf_nssa_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_always_type_metric_routemap_cmd_ospfd;
extern struct cmd_element no_ospf_distance_ospf_cmd_ospfd;
extern struct cmd_element ospf_abr_type_cmd_ospfd;
extern struct cmd_element mpls_te_router_addr_cmd_ospfd;
extern struct cmd_element ospf_neighbor_cmd_ospfd;
extern struct cmd_element no_ip_ospf_network_cmd_ospfd;
extern struct cmd_element ospf_distance_ospf_external_intra_cmd_ospfd;
extern struct cmd_element no_ospf_area_vlink_param3_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_always_type_routemap_cmd_ospfd;
extern struct route_map_rule_cmd route_match_ip_address_cmd_ospfd;
extern struct cmd_element no_debug_ospf_lsa_cmd_ospfd;
extern struct cmd_element no_match_ip_nexthop_cmd_ospfd;
extern struct cmd_element no_ospf_area_range_cost_cmd_ospfd;
extern struct cmd_element ospf_redistribute_source_metric_type_routemap_cmd_ospfd;
extern struct cmd_element no_ospf_area_vlink_authkey_cmd_ospfd;
extern struct route_map_rule_cmd route_match_ip_next_hop_prefix_list_cmd_ospfd;
extern struct cmd_element no_debug_ospf_nsm_cmd_ospfd;
extern struct cmd_element ospf_redistribute_source_type_cmd_ospfd;
extern struct cmd_element ospf_distance_ospf_external_intra_inter_cmd_ospfd;
extern struct cmd_element no_ip_ospf_dead_interval_addr_cmd_ospfd;
extern struct cmd_element no_ip_ospf_hello_interval_cmd_ospfd;
extern struct cmd_element no_ospf_default_metric_cmd_ospfd;
extern struct cmd_element no_ospf_area_nssa_no_summary_cmd_ospfd;
extern struct cmd_element ospf_neighbor_poll_interval_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_always_cmd_ospfd;
extern struct cmd_element ospf_area_range_cost_cmd_ospfd;
extern struct cmd_element ospf_auto_cost_reference_bandwidth_cmd_ospfd;
extern struct cmd_element ospf_distance_ospf_inter_external_cmd_ospfd;
extern struct cmd_element no_debug_ospf_nsm_sub_cmd_ospfd;
extern struct cmd_element no_ospf_priority_cmd_ospfd;
extern struct cmd_element ospf_redistribute_source_cmd_ospfd;
extern struct cmd_element match_ip_next_hop_prefix_list_cmd_ospfd;
extern struct cmd_element show_mpls_te_link_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_always_type_metric_cmd_ospfd;
extern struct cmd_element ip_ospf_priority_addr_cmd_ospfd;
extern struct cmd_element match_ip_address_prefix_list_cmd_ospfd;
extern struct cmd_element no_ospf_area_vlink_md5_cmd_ospfd;
extern struct cmd_element no_ospf_area_range_substitute_cmd_ospfd;
extern struct cmd_element no_ospf_neighbor_cmd_ospfd;
extern struct cmd_element no_debug_ospf_zebra_cmd_ospfd;
extern struct cmd_element ospf_distance_ospf_inter_intra_cmd_ospfd;
extern struct cmd_element no_ospf_area_vlink_param2_cmd_ospfd;
extern struct cmd_element no_ospf_opaque_capable_cmd_ospfd;
extern struct cmd_element ospf_priority_cmd_ospfd;
extern struct cmd_element ospf_hello_interval_cmd_ospfd;
extern struct cmd_element debug_ospf_zebra_sub_cmd_ospfd;
extern struct cmd_element ospf_timers_spf_cmd_ospfd;
extern struct cmd_element no_ospf_distribute_list_out_cmd_ospfd;
extern struct cmd_element no_ospf_area_range_advertise_cmd_ospfd;
extern struct cmd_element no_ip_ospf_retransmit_interval_cmd_ospfd;
extern struct cmd_element debug_ospf_packet_all_cmd_ospfd;
extern struct cmd_element no_ospf_timers_spf_cmd_ospfd;
extern struct cmd_element show_ip_ospf_neighbor_cmd_ospfd;
extern struct cmd_element show_ip_ospf_database_type_id_adv_router_cmd_ospfd;
extern struct cmd_element no_ip_ospf_authentication_key_addr_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_type_metric_routemap_cmd_ospfd;
extern struct cmd_element match_interface_cmd_ospfd;
extern struct cmd_element ospf_area_nssa_translate_cmd_ospfd;
extern struct route_map_rule_cmd route_match_ip_nexthop_cmd_ospfd;
extern struct cmd_element ospf_area_stub_cmd_ospfd;
extern struct cmd_element ospf_dead_interval_cmd_ospfd;
extern struct cmd_element no_ip_ospf_authentication_cmd_ospfd;
extern struct cmd_element ospf_area_range_advertise_cost_cmd_ospfd;
extern struct cmd_element mpls_te_on_cmd_ospfd;
extern struct cmd_element ospf_rfc1583_flag_cmd_ospfd;
extern struct cmd_element no_ip_ospf_authentication_key_cmd_ospfd;
extern struct cmd_element ospf_area_vlink_authtype_authkey_cmd_ospfd;
extern struct cmd_element no_ospf_rfc1583_flag_cmd_ospfd;
extern struct cmd_element ospf_area_vlink_param3_cmd_ospfd;
extern struct cmd_element ip_ospf_transmit_delay_addr_cmd_ospfd;
extern struct cmd_element ospf_area_vlink_param4_cmd_ospfd;
extern struct cmd_element ip_ospf_priority_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_always_type_cmd_ospfd;
extern struct cmd_element no_ospf_retransmit_interval_cmd_ospfd;
extern struct cmd_element debug_ospf_lsa_cmd_ospfd;
extern struct cmd_element no_ospf_passive_interface_addr_cmd_ospfd;
extern struct cmd_element no_debug_ospf_packet_send_recv_cmd_ospfd;
extern struct cmd_element no_ospf_refresh_timer_cmd_ospfd;
extern struct cmd_element no_ip_ospf_message_digest_key_addr_cmd_ospfd;
extern struct cmd_element no_ospf_router_id_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_cmd_ospfd;
extern struct cmd_element ospf_distribute_list_out_cmd_ospfd;
extern struct cmd_element show_ip_ospf_cmd_ospfd;
extern struct cmd_element no_ospf_distance_source_access_list_cmd_ospfd;
extern struct cmd_element ospf_refresh_timer_cmd_ospfd;
extern struct cmd_element ospf_area_stub_no_summary_cmd_ospfd;
extern struct cmd_element ospf_retransmit_interval_cmd_ospfd;
extern struct cmd_element no_match_ip_next_hop_prefix_list_cmd_ospfd;
extern struct cmd_element ospf_area_vlink_md5_cmd_ospfd;
extern struct cmd_element ospf_redistribute_source_routemap_cmd_ospfd;
extern struct cmd_element ospf_area_vlink_authtype_args_cmd_ospfd;
extern struct cmd_element debug_ospf_packet_send_recv_cmd_ospfd;
extern struct cmd_element show_ip_ospf_interface_cmd_ospfd;
extern struct cmd_element no_ip_ospf_cost_addr_cmd_ospfd;
extern struct cmd_element no_match_ip_address_prefix_list_cmd_ospfd;
extern struct cmd_element ospf_redistribute_source_type_metric_routemap_cmd_ospfd;
extern struct cmd_element no_debug_ospf_event_cmd_ospfd;
extern struct cmd_element ip_ospf_authentication_args_addr_cmd_ospfd;
extern struct cmd_element show_ip_ospf_database_type_adv_router_cmd_ospfd;
extern struct cmd_element no_ospf_default_information_originate_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_metric_cmd_ospfd;
extern struct cmd_element no_ip_ospf_authentication_addr_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_metric_routemap_cmd_ospfd;
extern struct cmd_element show_ip_ospf_border_routers_cmd_ospfd;
extern struct cmd_element ospf_distance_cmd_ospfd;
extern struct cmd_element no_ospf_area_stub_no_summary_cmd_ospfd;
extern struct cmd_element no_ospf_area_shortcut_cmd_ospfd;
extern struct cmd_element no_ospf_area_import_list_cmd_ospfd;
extern struct cmd_element ospf_default_information_originate_always_metric_routemap_cmd_ospfd;
extern struct cmd_element no_set_metric_type_cmd_ospfd;
extern struct cmd_element no_ospf_area_vlink_authtype_authkey_cmd_ospfd;
extern struct cmd_element show_ip_ospf_database_type_id_cmd_ospfd;
extern struct cmd_element no_router_ospf_id_cmd_ospfd;
extern struct cmd_element ip_ospf_message_digest_key_addr_cmd_ospfd;
extern struct cmd_element no_ip_ospf_cost_cmd_ospfd;
extern struct cmd_element match_ip_nexthop_cmd_ospfd;
extern struct cmd_element show_ip_ospf_neighbor_detail_all_cmd_ospfd;
extern struct cmd_element debug_ospf_packet_send_recv_detail_cmd_ospfd;
extern struct cmd_element no_ip_ospf_transmit_delay_addr_cmd_ospfd;

void GlobalVars_initializeActiveSet_ospfd()
{
    unsigned long term_debug_ospf_packet__T[5] =  {0, 0, 0, 0, 0};
    struct cmd_node zebra_node__T = 
    {
        ZEBRA_NODE,
        "%s(config-router)#",
    };
    struct cmd_node debug_node__T = 
    {
        DEBUG_NODE,
        "",
        1 
    };
    struct cmd_node interface_node__T = 
    {
        INTERFACE_NODE,
        "%s(config-if)# ",
        1
    };
    struct cmd_node ospf_node__T = 
    {
        OSPF_NODE,
        "%s(config-router)# ",
        1
     };
    unsigned long conf_debug_ospf_packet__T[5] =  {0, 0, 0, 0, 0};
    memcpy(&__activeVars_ospfd->show_ip_ospf_route_cmd__X, &show_ip_ospf_route_cmd_ospfd, sizeof(show_ip_ospf_route_cmd_ospfd));
    __activeVars_lib->pid_file__X =  PATH_OSPFD_PID;
    memcpy(&__activeVars_ospfd->ospf_area_vlink_param1_cmd__X, &ospf_area_vlink_param1_cmd_ospfd, sizeof(ospf_area_vlink_param1_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_vlink_param1_cmd__X, &no_ospf_area_vlink_param1_cmd_ospfd, sizeof(no_ospf_area_vlink_param1_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_export_list_cmd__X, &ospf_area_export_list_cmd_ospfd, sizeof(ospf_area_export_list_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_debug_ospf_zebra_sub_cmd__X, &no_debug_ospf_zebra_sub_cmd_ospfd, sizeof(no_debug_ospf_zebra_sub_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_authentication_cmd__X, &ospf_area_authentication_cmd_ospfd, sizeof(ospf_area_authentication_cmd_ospfd));
    memcpy(&__activeVars_lib->no_capability_opaque_cmd__X, &no_capability_opaque_cmd_ospfd, sizeof(no_capability_opaque_cmd_ospfd));
    memcpy(&__activeVars_lib->mpls_te_link_max_rsv_bw_cmd__X, &mpls_te_link_max_rsv_bw_cmd_ospfd, sizeof(mpls_te_link_max_rsv_bw_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_passive_interface_addr_cmd__X, &ospf_passive_interface_addr_cmd_ospfd, sizeof(ospf_passive_interface_addr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_retransmit_interval_addr_cmd__X, &no_ip_ospf_retransmit_interval_addr_cmd_ospfd, sizeof(no_ip_ospf_retransmit_interval_addr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->show_ip_ospf_neighbor_int_cmd__X, &show_ip_ospf_neighbor_int_cmd_ospfd, sizeof(show_ip_ospf_neighbor_int_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distance_ospf_external_inter_intra_cmd__X, &ospf_distance_ospf_external_inter_intra_cmd_ospfd, sizeof(ospf_distance_ospf_external_inter_intra_cmd_ospfd));
    memcpy(&__activeVars_ospfd->router_ospf_id_cmd__X, &router_ospf_id_cmd_ospfd, sizeof(router_ospf_id_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_hello_interval_addr_cmd__X, &ip_ospf_hello_interval_addr_cmd_ospfd, sizeof(ip_ospf_hello_interval_addr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_vlink_param4_cmd__X, &no_ospf_area_vlink_param4_cmd_ospfd, sizeof(no_ospf_area_vlink_param4_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_range_advertise_cmd__X, &ospf_area_range_advertise_cmd_ospfd, sizeof(ospf_area_range_advertise_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_metric_type_cmd__X, &ospf_default_information_originate_metric_type_cmd_ospfd, sizeof(ospf_default_information_originate_metric_type_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_type_metric_cmd__X, &ospf_default_information_originate_type_metric_cmd_ospfd, sizeof(ospf_default_information_originate_type_metric_cmd_ospfd));
    memcpy(&__activeVars_ospfd->router_ospf_cmd__X, &router_ospf_cmd_ospfd, sizeof(router_ospf_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_transmit_delay_cmd__X, &ospf_transmit_delay_cmd_ospfd, sizeof(ospf_transmit_delay_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_default_cost_cmd__X, &no_ospf_area_default_cost_cmd_ospfd, sizeof(no_ospf_area_default_cost_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_range_substitute_cmd__X, &ospf_area_range_substitute_cmd_ospfd, sizeof(ospf_area_range_substitute_cmd_ospfd));
    memcpy(&__activeVars_lib->set_metric_type_cmd__X, &set_metric_type_cmd_ospfd, sizeof(set_metric_type_cmd_ospfd));
    memcpy(&__activeVars_ospfd->term_debug_ospf_packet__X, &term_debug_ospf_packet__T, sizeof(term_debug_ospf_packet__T));
    memcpy(&__activeVars_lib->no_mpls_te_cmd__X, &no_mpls_te_cmd_ospfd, sizeof(no_mpls_te_cmd_ospfd));
    memcpy(&__activeVars_lib->no_match_ip_address_prefix_list_val_cmd__X, &no_match_ip_address_prefix_list_val_cmd_ospfd, sizeof(no_match_ip_address_prefix_list_val_cmd_ospfd));
    memcpy(&__activeVars_lib->capability_opaque_cmd__X, &capability_opaque_cmd_ospfd, sizeof(capability_opaque_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_transmit_delay_cmd__X, &no_ip_ospf_transmit_delay_cmd_ospfd, sizeof(no_ip_ospf_transmit_delay_cmd_ospfd));
    memcpy(&__activeVars_lib->zebra_node__X, &zebra_node__T, sizeof(zebra_node__T));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_type_cmd__X, &ospf_default_information_originate_type_cmd_ospfd, sizeof(ospf_default_information_originate_type_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_authentication_key_cmd__X, &ospf_authentication_key_cmd_ospfd, sizeof(ospf_authentication_key_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distance_ospf_intra_inter_cmd__X, &ospf_distance_ospf_intra_inter_cmd_ospfd, sizeof(ospf_distance_ospf_intra_inter_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_debug_ospf_packet_all_cmd__X, &no_debug_ospf_packet_all_cmd_ospfd, sizeof(no_debug_ospf_packet_all_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distance_ospf_intra_external_cmd__X, &ospf_distance_ospf_intra_external_cmd_ospfd, sizeof(ospf_distance_ospf_intra_external_cmd_ospfd));
    memcpy(&__activeVars_lib->set_metric_cmd__X, &set_metric_cmd_ospfd, sizeof(set_metric_cmd_ospfd));
    memcpy(&__activeVars_ospfd->debug_ospf_nsm_sub_cmd__X, &debug_ospf_nsm_sub_cmd_ospfd, sizeof(debug_ospf_nsm_sub_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_dead_interval_addr_cmd__X, &ip_ospf_dead_interval_addr_cmd_ospfd, sizeof(ip_ospf_dead_interval_addr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_type_routemap_cmd__X, &ospf_default_information_originate_type_routemap_cmd_ospfd, sizeof(ospf_default_information_originate_type_routemap_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_network_cmd__X, &ip_ospf_network_cmd_ospfd, sizeof(ip_ospf_network_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_filter_list_cmd__X, &ospf_area_filter_list_cmd_ospfd, sizeof(ospf_area_filter_list_cmd_ospfd));
    memcpy(&__activeVars_lib->route_set_metric_cmd__X, &route_set_metric_cmd_ospfd, sizeof(route_set_metric_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_vlink_authtype_md5_cmd__X, &ospf_area_vlink_authtype_md5_cmd_ospfd, sizeof(ospf_area_vlink_authtype_md5_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_nssa_translate_no_summary_cmd__X, &ospf_area_nssa_translate_no_summary_cmd_ospfd, sizeof(ospf_area_nssa_translate_no_summary_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_priority_addr_cmd__X, &no_ip_ospf_priority_addr_cmd_ospfd, sizeof(no_ip_ospf_priority_addr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_network_area_cmd__X, &no_ospf_network_area_cmd_ospfd, sizeof(no_ospf_network_area_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_metric_cmd__X, &ospf_default_metric_cmd_ospfd, sizeof(ospf_default_metric_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distance_ospf_intra_external_inter_cmd__X, &ospf_distance_ospf_intra_external_inter_cmd_ospfd, sizeof(ospf_distance_ospf_intra_external_inter_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_debug_ospf_ism_cmd__X, &no_debug_ospf_ism_cmd_ospfd, sizeof(no_debug_ospf_ism_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_neighbor_poll_interval_cmd__X, &no_ospf_neighbor_poll_interval_cmd_ospfd, sizeof(no_ospf_neighbor_poll_interval_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_vlink_cmd__X, &no_ospf_area_vlink_cmd_ospfd, sizeof(no_ospf_area_vlink_cmd_ospfd));
    __activeVars_ospfd->term_debug_ospf_ism__X =  0;
    memcpy(&__activeVars_lib->route_match_interface_cmd__X, &route_match_interface_cmd_ospfd, sizeof(route_match_interface_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_authentication_cmd__X, &no_ospf_area_authentication_cmd_ospfd, sizeof(no_ospf_area_authentication_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_range_advertise_cost_cmd__X, &no_ospf_area_range_advertise_cost_cmd_ospfd, sizeof(no_ospf_area_range_advertise_cost_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_redistribute_source_cmd__X, &no_ospf_redistribute_source_cmd_ospfd, sizeof(no_ospf_redistribute_source_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_network_cmd__X, &ospf_network_cmd_ospfd, sizeof(ospf_network_cmd_ospfd));
    __activeVars_ospfd->conf_debug_ospf_ism__X =  0;
    memcpy(&__activeVars_ospfd->ospf_redistribute_source_type_routemap_cmd__X, &ospf_redistribute_source_type_routemap_cmd_ospfd, sizeof(ospf_redistribute_source_type_routemap_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_refresh_timer_val_cmd__X, &no_ospf_refresh_timer_val_cmd_ospfd, sizeof(no_ospf_refresh_timer_val_cmd_ospfd));
    memcpy(&__activeVars_lib->no_match_ip_address_val_cmd__X, &no_match_ip_address_val_cmd_ospfd, sizeof(no_match_ip_address_val_cmd_ospfd));
    memcpy(&__activeVars_ospfd->debug_ospf_zebra_cmd__X, &debug_ospf_zebra_cmd_ospfd, sizeof(debug_ospf_zebra_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_distance_source_cmd__X, &no_ospf_distance_source_cmd_ospfd, sizeof(no_ospf_distance_source_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_passive_interface_cmd__X, &no_ospf_passive_interface_cmd_ospfd, sizeof(no_ospf_passive_interface_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_default_cost_cmd__X, &ospf_area_default_cost_cmd_ospfd, sizeof(ospf_area_default_cost_cmd_ospfd));
    __activeVars_ospfd->ospf_area_type_msg_max__X =  OSPF_AREA_TYPE_MAX;
    memcpy(&__activeVars_ospfd->no_ospf_distance_cmd__X, &no_ospf_distance_cmd_ospfd, sizeof(no_ospf_distance_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_retransmit_interval_addr_cmd__X, &ip_ospf_retransmit_interval_addr_cmd_ospfd, sizeof(ip_ospf_retransmit_interval_addr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->show_ip_ospf_neighbor_detail_cmd__X, &show_ip_ospf_neighbor_detail_cmd_ospfd, sizeof(show_ip_ospf_neighbor_detail_cmd_ospfd));
    memcpy(&__activeVars_lib->mpls_te_cmd__X, &mpls_te_cmd_ospfd, sizeof(mpls_te_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_message_digest_key_cmd__X, &no_ip_ospf_message_digest_key_cmd_ospfd, sizeof(no_ip_ospf_message_digest_key_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_nssa_cmd__X, &no_ospf_area_nssa_cmd_ospfd, sizeof(no_ospf_area_nssa_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_vlink_authtype_md5_cmd__X, &no_ospf_area_vlink_authtype_md5_cmd_ospfd, sizeof(no_ospf_area_vlink_authtype_md5_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_router_ospf_cmd__X, &no_router_ospf_cmd_ospfd, sizeof(no_router_ospf_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_transmit_delay_cmd__X, &ip_ospf_transmit_delay_cmd_ospfd, sizeof(ip_ospf_transmit_delay_cmd_ospfd));
    memcpy(&__activeVars_lib->show_mpls_te_router_cmd__X, &show_mpls_te_router_cmd_ospfd, sizeof(show_mpls_te_router_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_cost_cmd__X, &no_ospf_cost_cmd_ospfd, sizeof(no_ospf_cost_cmd_ospfd));
    memcpy(&__activeVars_ospfd->debug_ospf_nssa_cmd__X, &debug_ospf_nssa_cmd_ospfd, sizeof(debug_ospf_nssa_cmd_ospfd));
    memcpy(&__activeVars_lib->no_match_interface_val_cmd__X, &no_match_interface_val_cmd_ospfd, sizeof(no_match_interface_val_cmd_ospfd));
    memcpy(&__activeVars_lib->route_match_ip_address_prefix_list_cmd__X, &route_match_ip_address_prefix_list_cmd_ospfd, sizeof(route_match_ip_address_prefix_list_cmd_ospfd));
    memcpy(&__activeVars_ospfd->debug_ospf_event_cmd__X, &debug_ospf_event_cmd_ospfd, sizeof(debug_ospf_event_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_hello_interval_addr_cmd__X, &no_ip_ospf_hello_interval_addr_cmd_ospfd, sizeof(no_ip_ospf_hello_interval_addr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_metric_type_routemap_cmd__X, &ospf_default_information_originate_metric_type_routemap_cmd_ospfd, sizeof(ospf_default_information_originate_metric_type_routemap_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distance_source_access_list_cmd__X, &ospf_distance_source_access_list_cmd_ospfd, sizeof(ospf_distance_source_access_list_cmd_ospfd));
    memcpy(&__activeVars_ospfd->show_ip_ospf_database_cmd__X, &show_ip_ospf_database_cmd_ospfd, sizeof(show_ip_ospf_database_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_hello_interval_cmd__X, &no_ospf_hello_interval_cmd_ospfd, sizeof(no_ospf_hello_interval_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distance_ospf_inter_cmd__X, &ospf_distance_ospf_inter_cmd_ospfd, sizeof(ospf_distance_ospf_inter_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_redistribute_source_metric_routemap_cmd__X, &ospf_redistribute_source_metric_routemap_cmd_ospfd, sizeof(ospf_redistribute_source_metric_routemap_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_router_id_cmd__X, &ospf_router_id_cmd_ospfd, sizeof(ospf_router_id_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_authentication_message_digest_cmd__X, &ospf_area_authentication_message_digest_cmd_ospfd, sizeof(ospf_area_authentication_message_digest_cmd_ospfd));
    memcpy(&__activeVars_lib->no_set_metric_cmd__X, &no_set_metric_cmd_ospfd, sizeof(no_set_metric_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_cost_cmd__X, &ip_ospf_cost_cmd_ospfd, sizeof(ip_ospf_cost_cmd_ospfd));
    memcpy(&__activeVars_lib->no_match_interface_cmd__X, &no_match_interface_cmd_ospfd, sizeof(no_match_interface_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_debug_ospf_packet_send_recv_detail_cmd__X, &no_debug_ospf_packet_send_recv_detail_cmd_ospfd, sizeof(no_debug_ospf_packet_send_recv_detail_cmd_ospfd));
    memcpy(&__activeVars_lib->no_set_metric_type_val_cmd__X, &no_set_metric_type_val_cmd_ospfd, sizeof(no_set_metric_type_val_cmd_ospfd));
    memcpy(&__activeVars_ospfd->debug_ospf_ism_sub_cmd__X, &debug_ospf_ism_sub_cmd_ospfd, sizeof(debug_ospf_ism_sub_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distance_ospf_inter_external_intra_cmd__X, &ospf_distance_ospf_inter_external_intra_cmd_ospfd, sizeof(ospf_distance_ospf_inter_external_intra_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_opaque_capable_cmd__X, &ospf_opaque_capable_cmd_ospfd, sizeof(ospf_opaque_capable_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_range_cmd__X, &ospf_area_range_cmd_ospfd, sizeof(ospf_area_range_cmd_ospfd));
    __activeVars_lib->zclient__X =  NULL;
    memcpy(&__activeVars_ospfd->no_ospf_transmit_delay_cmd__X, &no_ospf_transmit_delay_cmd_ospfd, sizeof(no_ospf_transmit_delay_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_retransmit_interval_cmd__X, &ip_ospf_retransmit_interval_cmd_ospfd, sizeof(ip_ospf_retransmit_interval_cmd_ospfd));
    memcpy(&__activeVars_ospfd->show_ip_ospf_database_type_id_self_cmd__X, &show_ip_ospf_database_type_id_self_cmd_ospfd, sizeof(show_ip_ospf_database_type_id_self_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_auto_cost_reference_bandwidth_cmd__X, &no_ospf_auto_cost_reference_bandwidth_cmd_ospfd, sizeof(no_ospf_auto_cost_reference_bandwidth_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_nssa_no_summary_cmd__X, &ospf_area_nssa_no_summary_cmd_ospfd, sizeof(ospf_area_nssa_no_summary_cmd_ospfd));
    memcpy(&__activeVars_lib->mpls_te_link_unrsv_bw_cmd__X, &mpls_te_link_unrsv_bw_cmd_ospfd, sizeof(mpls_te_link_unrsv_bw_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_routemap_cmd__X, &ospf_default_information_originate_routemap_cmd_ospfd, sizeof(ospf_default_information_originate_routemap_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_redistribute_source_type_metric_cmd__X, &ospf_redistribute_source_type_metric_cmd_ospfd, sizeof(ospf_redistribute_source_type_metric_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distance_ospf_external_cmd__X, &ospf_distance_ospf_external_cmd_ospfd, sizeof(ospf_distance_ospf_external_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_message_digest_key_cmd__X, &no_ospf_message_digest_key_cmd_ospfd, sizeof(no_ospf_message_digest_key_cmd_ospfd));
    memcpy(&__activeVars_lib->mpls_te_link_rsc_clsclr_cmd__X, &mpls_te_link_rsc_clsclr_cmd_ospfd, sizeof(mpls_te_link_rsc_clsclr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_message_digest_key_cmd__X, &ospf_message_digest_key_cmd_ospfd, sizeof(ospf_message_digest_key_cmd_ospfd));
    memcpy(&__activeVars_lib->debug_node__X, &debug_node__T, sizeof(debug_node__T));
    memcpy(&__activeVars_ospfd->ospf_redistribute_source_metric_cmd__X, &ospf_redistribute_source_metric_cmd_ospfd, sizeof(ospf_redistribute_source_metric_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_authentication_key_cmd__X, &ip_ospf_authentication_key_cmd_ospfd, sizeof(ip_ospf_authentication_key_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_neighbor_priority_pollinterval_cmd__X, &no_ospf_neighbor_priority_pollinterval_cmd_ospfd, sizeof(no_ospf_neighbor_priority_pollinterval_cmd_ospfd));
    memcpy(&__activeVars_lib->route_set_metric_type_cmd__X, &route_set_metric_type_cmd_ospfd, sizeof(route_set_metric_type_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_dead_interval_cmd__X, &no_ospf_dead_interval_cmd_ospfd, sizeof(no_ospf_dead_interval_cmd_ospfd));
    memcpy(&__activeVars_lib->mpls_te_link_maxbw_cmd__X, &mpls_te_link_maxbw_cmd_ospfd, sizeof(mpls_te_link_maxbw_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_authentication_cmd__X, &ip_ospf_authentication_cmd_ospfd, sizeof(ip_ospf_authentication_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_neighbor_priority_cmd__X, &ospf_neighbor_priority_cmd_ospfd, sizeof(ospf_neighbor_priority_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_abr_type_cmd__X, &no_ospf_abr_type_cmd_ospfd, sizeof(no_ospf_abr_type_cmd_ospfd));
    memcpy(&__activeVars_ospfd->show_ip_ospf_database_type_self_cmd__X, &show_ip_ospf_database_type_self_cmd_ospfd, sizeof(show_ip_ospf_database_type_self_cmd_ospfd));
    memcpy(&__activeVars_ospfd->show_ip_ospf_database_type_cmd__X, &show_ip_ospf_database_type_cmd_ospfd, sizeof(show_ip_ospf_database_type_cmd_ospfd));
    __activeVars_lib->vlink_count__X =  0;
    memcpy(&__activeVars_lib->no_match_ip_next_hop_prefix_list_val_cmd__X, &no_match_ip_next_hop_prefix_list_val_cmd_ospfd, sizeof(no_match_ip_next_hop_prefix_list_val_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_vlink_authtype_args_authkey_cmd__X, &ospf_area_vlink_authtype_args_authkey_cmd_ospfd, sizeof(ospf_area_vlink_authtype_args_authkey_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_default_metric_val_cmd__X, &no_ospf_default_metric_val_cmd_ospfd, sizeof(no_ospf_default_metric_val_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_always_metric_type_routemap_cmd__X, &ospf_default_information_originate_always_metric_type_routemap_cmd_ospfd, sizeof(ospf_default_information_originate_always_metric_type_routemap_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_always_routemap_cmd__X, &ospf_default_information_originate_always_routemap_cmd_ospfd, sizeof(ospf_default_information_originate_always_routemap_cmd_ospfd));
    __activeVars_ospfd->conf_debug_ospf_nsm__X =  0;
    memcpy(&__activeVars_ospfd->ospf_area_vlink_param2_cmd__X, &ospf_area_vlink_param2_cmd_ospfd, sizeof(ospf_area_vlink_param2_cmd_ospfd));
    memcpy(&__activeVars_lib->interface_node__X, &interface_node__T, sizeof(interface_node__T));
    memcpy(&__activeVars_ospfd->no_ospf_neighbor_priority_cmd__X, &no_ospf_neighbor_priority_cmd_ospfd, sizeof(no_ospf_neighbor_priority_cmd_ospfd));
    memcpy(&__activeVars_lib->no_match_ip_nexthop_val_cmd__X, &no_match_ip_nexthop_val_cmd_ospfd, sizeof(no_match_ip_nexthop_val_cmd_ospfd));
    memcpy(&__activeVars_ospfd->show_debugging_ospf_cmd__X, &show_debugging_ospf_cmd_ospfd, sizeof(show_debugging_ospf_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_nssa_cmd__X, &ospf_area_nssa_cmd_ospfd, sizeof(ospf_area_nssa_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_debug_ospf_ism_sub_cmd__X, &no_debug_ospf_ism_sub_cmd_ospfd, sizeof(no_debug_ospf_ism_sub_cmd_ospfd));
    memcpy(&__activeVars_ospfd->show_ip_ospf_neighbor_int_detail_cmd__X, &show_ip_ospf_neighbor_int_detail_cmd_ospfd, sizeof(show_ip_ospf_neighbor_int_detail_cmd_ospfd));
    memcpy(&__activeVars_ospfd->debug_ospf_nsm_cmd__X, &debug_ospf_nsm_cmd_ospfd, sizeof(debug_ospf_nsm_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_vlink_authtype_cmd__X, &ospf_area_vlink_authtype_cmd_ospfd, sizeof(ospf_area_vlink_authtype_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_filter_list_cmd__X, &no_ospf_area_filter_list_cmd_ospfd, sizeof(no_ospf_area_filter_list_cmd_ospfd));
    memcpy(&__activeVars_ospfd->show_ip_ospf_neighbor_id_cmd__X, &show_ip_ospf_neighbor_id_cmd_ospfd, sizeof(show_ip_ospf_neighbor_id_cmd_ospfd));
    memcpy(&__activeVars_lib->mpls_te_link_metric_cmd__X, &mpls_te_link_metric_cmd_ospfd, sizeof(mpls_te_link_metric_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_node__X, &ospf_node__T, sizeof(ospf_node__T));
    memcpy(&__activeVars_ospfd->ospf_passive_interface_cmd__X, &ospf_passive_interface_cmd_ospfd, sizeof(ospf_passive_interface_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_neighbor_poll_interval_priority_cmd__X, &ospf_neighbor_poll_interval_priority_cmd_ospfd, sizeof(ospf_neighbor_poll_interval_priority_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distance_ospf_external_inter_cmd__X, &ospf_distance_ospf_external_inter_cmd_ospfd, sizeof(ospf_distance_ospf_external_inter_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_vlink_authtype_args_md5_cmd__X, &ospf_area_vlink_authtype_args_md5_cmd_ospfd, sizeof(ospf_area_vlink_authtype_args_md5_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_vlink_authtype_cmd__X, &no_ospf_area_vlink_authtype_cmd_ospfd, sizeof(no_ospf_area_vlink_authtype_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_cost_addr_cmd__X, &ip_ospf_cost_addr_cmd_ospfd, sizeof(ip_ospf_cost_addr_cmd_ospfd));
    __activeVars_ospfd->conf_debug_ospf_lsa__X =  0;
    memcpy(&__activeVars_ospfd->no_ospf_compatible_rfc1583_cmd__X, &no_ospf_compatible_rfc1583_cmd_ospfd, sizeof(no_ospf_compatible_rfc1583_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_always_metric_type_cmd__X, &ospf_default_information_originate_always_metric_type_cmd_ospfd, sizeof(ospf_default_information_originate_always_metric_type_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_range_cmd__X, &no_ospf_area_range_cmd_ospfd, sizeof(no_ospf_area_range_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_network_cmd__X, &no_ospf_network_cmd_ospfd, sizeof(no_ospf_network_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_cost_cmd__X, &ospf_cost_cmd_ospfd, sizeof(ospf_cost_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distance_ospf_intra_cmd__X, &ospf_distance_ospf_intra_cmd_ospfd, sizeof(ospf_distance_ospf_intra_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_stub_cmd__X, &no_ospf_area_stub_cmd_ospfd, sizeof(no_ospf_area_stub_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_network_area_cmd__X, &ospf_network_area_cmd_ospfd, sizeof(ospf_network_area_cmd_ospfd));
    memcpy(&__activeVars_lib->match_ip_address_cmd__X, &match_ip_address_cmd_ospfd, sizeof(match_ip_address_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_always_metric_cmd__X, &ospf_default_information_originate_always_metric_cmd_ospfd, sizeof(ospf_default_information_originate_always_metric_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distance_ospf_intra_inter_external_cmd__X, &ospf_distance_ospf_intra_inter_external_cmd_ospfd, sizeof(ospf_distance_ospf_intra_inter_external_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_export_list_cmd__X, &no_ospf_area_export_list_cmd_ospfd, sizeof(no_ospf_area_export_list_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_debug_ospf_lsa_sub_cmd__X, &no_debug_ospf_lsa_sub_cmd_ospfd, sizeof(no_debug_ospf_lsa_sub_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_message_digest_key_cmd__X, &ip_ospf_message_digest_key_cmd_ospfd, sizeof(ip_ospf_message_digest_key_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_shortcut_cmd__X, &ospf_area_shortcut_cmd_ospfd, sizeof(ospf_area_shortcut_cmd_ospfd));
    memcpy(&__activeVars_lib->no_set_metric_val_cmd__X, &no_set_metric_val_cmd_ospfd, sizeof(no_set_metric_val_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_import_list_cmd__X, &ospf_area_import_list_cmd_ospfd, sizeof(ospf_area_import_list_cmd_ospfd));
    memcpy(&__activeVars_ospfd->debug_ospf_lsa_sub_cmd__X, &debug_ospf_lsa_sub_cmd_ospfd, sizeof(debug_ospf_lsa_sub_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_vlink_authkey_cmd__X, &ospf_area_vlink_authkey_cmd_ospfd, sizeof(ospf_area_vlink_authkey_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_compatible_rfc1583_cmd__X, &ospf_compatible_rfc1583_cmd_ospfd, sizeof(ospf_compatible_rfc1583_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distance_ospf_inter_intra_external_cmd__X, &ospf_distance_ospf_inter_intra_external_cmd_ospfd, sizeof(ospf_distance_ospf_inter_intra_external_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_authentication_addr_cmd__X, &ip_ospf_authentication_addr_cmd_ospfd, sizeof(ip_ospf_authentication_addr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distance_source_cmd__X, &ospf_distance_source_cmd_ospfd, sizeof(ospf_distance_source_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_authentication_key_cmd__X, &no_ospf_authentication_key_cmd_ospfd, sizeof(no_ospf_authentication_key_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_range_not_advertise_cmd__X, &ospf_area_range_not_advertise_cmd_ospfd, sizeof(ospf_area_range_not_advertise_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_hello_interval_cmd__X, &ip_ospf_hello_interval_cmd_ospfd, sizeof(ip_ospf_hello_interval_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_redistribute_source_metric_type_cmd__X, &ospf_redistribute_source_metric_type_cmd_ospfd, sizeof(ospf_redistribute_source_metric_type_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_authentication_key_addr_cmd__X, &ip_ospf_authentication_key_addr_cmd_ospfd, sizeof(ip_ospf_authentication_key_addr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_dead_interval_cmd__X, &ip_ospf_dead_interval_cmd_ospfd, sizeof(ip_ospf_dead_interval_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_authentication_args_cmd__X, &ip_ospf_authentication_args_cmd_ospfd, sizeof(ip_ospf_authentication_args_cmd_ospfd));
    memcpy(&__activeVars_ospfd->debug_ospf_ism_cmd__X, &debug_ospf_ism_cmd_ospfd, sizeof(debug_ospf_ism_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_vlink_cmd__X, &ospf_area_vlink_cmd_ospfd, sizeof(ospf_area_vlink_cmd_ospfd));
    memcpy(&__activeVars_lib->no_match_ip_address_cmd__X, &no_match_ip_address_cmd_ospfd, sizeof(no_match_ip_address_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_priority_cmd__X, &no_ip_ospf_priority_cmd_ospfd, sizeof(no_ip_ospf_priority_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_dead_interval_cmd__X, &no_ip_ospf_dead_interval_cmd_ospfd, sizeof(no_ip_ospf_dead_interval_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_neighbor_priority_poll_interval_cmd__X, &ospf_neighbor_priority_poll_interval_cmd_ospfd, sizeof(ospf_neighbor_priority_poll_interval_cmd_ospfd));
    memcpy(&__activeVars_ospfd->show_ip_ospf_neighbor_all_cmd__X, &show_ip_ospf_neighbor_all_cmd_ospfd, sizeof(show_ip_ospf_neighbor_all_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_debug_ospf_nssa_cmd__X, &no_debug_ospf_nssa_cmd_ospfd, sizeof(no_debug_ospf_nssa_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_always_type_metric_routemap_cmd__X, &ospf_default_information_originate_always_type_metric_routemap_cmd_ospfd, sizeof(ospf_default_information_originate_always_type_metric_routemap_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_distance_ospf_cmd__X, &no_ospf_distance_ospf_cmd_ospfd, sizeof(no_ospf_distance_ospf_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_abr_type_cmd__X, &ospf_abr_type_cmd_ospfd, sizeof(ospf_abr_type_cmd_ospfd));
    memcpy(&__activeVars_lib->mpls_te_router_addr_cmd__X, &mpls_te_router_addr_cmd_ospfd, sizeof(mpls_te_router_addr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_neighbor_cmd__X, &ospf_neighbor_cmd_ospfd, sizeof(ospf_neighbor_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_network_cmd__X, &no_ip_ospf_network_cmd_ospfd, sizeof(no_ip_ospf_network_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distance_ospf_external_intra_cmd__X, &ospf_distance_ospf_external_intra_cmd_ospfd, sizeof(ospf_distance_ospf_external_intra_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_vlink_param3_cmd__X, &no_ospf_area_vlink_param3_cmd_ospfd, sizeof(no_ospf_area_vlink_param3_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_always_type_routemap_cmd__X, &ospf_default_information_originate_always_type_routemap_cmd_ospfd, sizeof(ospf_default_information_originate_always_type_routemap_cmd_ospfd));
    memcpy(&__activeVars_lib->route_match_ip_address_cmd__X, &route_match_ip_address_cmd_ospfd, sizeof(route_match_ip_address_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_debug_ospf_lsa_cmd__X, &no_debug_ospf_lsa_cmd_ospfd, sizeof(no_debug_ospf_lsa_cmd_ospfd));
    memcpy(&__activeVars_lib->no_match_ip_nexthop_cmd__X, &no_match_ip_nexthop_cmd_ospfd, sizeof(no_match_ip_nexthop_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_range_cost_cmd__X, &no_ospf_area_range_cost_cmd_ospfd, sizeof(no_ospf_area_range_cost_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_redistribute_source_metric_type_routemap_cmd__X, &ospf_redistribute_source_metric_type_routemap_cmd_ospfd, sizeof(ospf_redistribute_source_metric_type_routemap_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_vlink_authkey_cmd__X, &no_ospf_area_vlink_authkey_cmd_ospfd, sizeof(no_ospf_area_vlink_authkey_cmd_ospfd));
    __activeVars_ospfd->term_debug_ospf_event__X =  0;
    memcpy(&__activeVars_lib->route_match_ip_next_hop_prefix_list_cmd__X, &route_match_ip_next_hop_prefix_list_cmd_ospfd, sizeof(route_match_ip_next_hop_prefix_list_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_debug_ospf_nsm_cmd__X, &no_debug_ospf_nsm_cmd_ospfd, sizeof(no_debug_ospf_nsm_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_redistribute_source_type_cmd__X, &ospf_redistribute_source_type_cmd_ospfd, sizeof(ospf_redistribute_source_type_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distance_ospf_external_intra_inter_cmd__X, &ospf_distance_ospf_external_intra_inter_cmd_ospfd, sizeof(ospf_distance_ospf_external_intra_inter_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_dead_interval_addr_cmd__X, &no_ip_ospf_dead_interval_addr_cmd_ospfd, sizeof(no_ip_ospf_dead_interval_addr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_hello_interval_cmd__X, &no_ip_ospf_hello_interval_cmd_ospfd, sizeof(no_ip_ospf_hello_interval_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_default_metric_cmd__X, &no_ospf_default_metric_cmd_ospfd, sizeof(no_ospf_default_metric_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_nssa_no_summary_cmd__X, &no_ospf_area_nssa_no_summary_cmd_ospfd, sizeof(no_ospf_area_nssa_no_summary_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_neighbor_poll_interval_cmd__X, &ospf_neighbor_poll_interval_cmd_ospfd, sizeof(ospf_neighbor_poll_interval_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_always_cmd__X, &ospf_default_information_originate_always_cmd_ospfd, sizeof(ospf_default_information_originate_always_cmd_ospfd));
    __activeVars_ospfd->conf_debug_ospf_zebra__X =  0;
    memcpy(&__activeVars_ospfd->ospf_area_range_cost_cmd__X, &ospf_area_range_cost_cmd_ospfd, sizeof(ospf_area_range_cost_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_auto_cost_reference_bandwidth_cmd__X, &ospf_auto_cost_reference_bandwidth_cmd_ospfd, sizeof(ospf_auto_cost_reference_bandwidth_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distance_ospf_inter_external_cmd__X, &ospf_distance_ospf_inter_external_cmd_ospfd, sizeof(ospf_distance_ospf_inter_external_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_debug_ospf_nsm_sub_cmd__X, &no_debug_ospf_nsm_sub_cmd_ospfd, sizeof(no_debug_ospf_nsm_sub_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_priority_cmd__X, &no_ospf_priority_cmd_ospfd, sizeof(no_ospf_priority_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_redistribute_source_cmd__X, &ospf_redistribute_source_cmd_ospfd, sizeof(ospf_redistribute_source_cmd_ospfd));
    memcpy(&__activeVars_lib->match_ip_next_hop_prefix_list_cmd__X, &match_ip_next_hop_prefix_list_cmd_ospfd, sizeof(match_ip_next_hop_prefix_list_cmd_ospfd));
    memcpy(&__activeVars_lib->show_mpls_te_link_cmd__X, &show_mpls_te_link_cmd_ospfd, sizeof(show_mpls_te_link_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_always_type_metric_cmd__X, &ospf_default_information_originate_always_type_metric_cmd_ospfd, sizeof(ospf_default_information_originate_always_type_metric_cmd_ospfd));
    __activeVars_ospfd->term_debug_ospf_nssa__X =  0;
    memcpy(&__activeVars_ospfd->ip_ospf_priority_addr_cmd__X, &ip_ospf_priority_addr_cmd_ospfd, sizeof(ip_ospf_priority_addr_cmd_ospfd));
    memcpy(&__activeVars_lib->match_ip_address_prefix_list_cmd__X, &match_ip_address_prefix_list_cmd_ospfd, sizeof(match_ip_address_prefix_list_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_vlink_md5_cmd__X, &no_ospf_area_vlink_md5_cmd_ospfd, sizeof(no_ospf_area_vlink_md5_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_range_substitute_cmd__X, &no_ospf_area_range_substitute_cmd_ospfd, sizeof(no_ospf_area_range_substitute_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_neighbor_cmd__X, &no_ospf_neighbor_cmd_ospfd, sizeof(no_ospf_neighbor_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_debug_ospf_zebra_cmd__X, &no_debug_ospf_zebra_cmd_ospfd, sizeof(no_debug_ospf_zebra_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distance_ospf_inter_intra_cmd__X, &ospf_distance_ospf_inter_intra_cmd_ospfd, sizeof(ospf_distance_ospf_inter_intra_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_vlink_param2_cmd__X, &no_ospf_area_vlink_param2_cmd_ospfd, sizeof(no_ospf_area_vlink_param2_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_opaque_capable_cmd__X, &no_ospf_opaque_capable_cmd_ospfd, sizeof(no_ospf_opaque_capable_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_priority_cmd__X, &ospf_priority_cmd_ospfd, sizeof(ospf_priority_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_hello_interval_cmd__X, &ospf_hello_interval_cmd_ospfd, sizeof(ospf_hello_interval_cmd_ospfd));
    memcpy(&__activeVars_ospfd->debug_ospf_zebra_sub_cmd__X, &debug_ospf_zebra_sub_cmd_ospfd, sizeof(debug_ospf_zebra_sub_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_timers_spf_cmd__X, &ospf_timers_spf_cmd_ospfd, sizeof(ospf_timers_spf_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_distribute_list_out_cmd__X, &no_ospf_distribute_list_out_cmd_ospfd, sizeof(no_ospf_distribute_list_out_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_range_advertise_cmd__X, &no_ospf_area_range_advertise_cmd_ospfd, sizeof(no_ospf_area_range_advertise_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_retransmit_interval_cmd__X, &no_ip_ospf_retransmit_interval_cmd_ospfd, sizeof(no_ip_ospf_retransmit_interval_cmd_ospfd));
    memcpy(&__activeVars_ospfd->debug_ospf_packet_all_cmd__X, &debug_ospf_packet_all_cmd_ospfd, sizeof(debug_ospf_packet_all_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_timers_spf_cmd__X, &no_ospf_timers_spf_cmd_ospfd, sizeof(no_ospf_timers_spf_cmd_ospfd));
    memcpy(&__activeVars_ospfd->show_ip_ospf_neighbor_cmd__X, &show_ip_ospf_neighbor_cmd_ospfd, sizeof(show_ip_ospf_neighbor_cmd_ospfd));
    __activeVars_ospfd->term_debug_ospf_zebra__X =  0;
    memcpy(&__activeVars_ospfd->show_ip_ospf_database_type_id_adv_router_cmd__X, &show_ip_ospf_database_type_id_adv_router_cmd_ospfd, sizeof(show_ip_ospf_database_type_id_adv_router_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_authentication_key_addr_cmd__X, &no_ip_ospf_authentication_key_addr_cmd_ospfd, sizeof(no_ip_ospf_authentication_key_addr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_type_metric_routemap_cmd__X, &ospf_default_information_originate_type_metric_routemap_cmd_ospfd, sizeof(ospf_default_information_originate_type_metric_routemap_cmd_ospfd));
    memcpy(&__activeVars_lib->match_interface_cmd__X, &match_interface_cmd_ospfd, sizeof(match_interface_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_nssa_translate_cmd__X, &ospf_area_nssa_translate_cmd_ospfd, sizeof(ospf_area_nssa_translate_cmd_ospfd));
    memcpy(&__activeVars_lib->route_match_ip_nexthop_cmd__X, &route_match_ip_nexthop_cmd_ospfd, sizeof(route_match_ip_nexthop_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_stub_cmd__X, &ospf_area_stub_cmd_ospfd, sizeof(ospf_area_stub_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_dead_interval_cmd__X, &ospf_dead_interval_cmd_ospfd, sizeof(ospf_dead_interval_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_authentication_cmd__X, &no_ip_ospf_authentication_cmd_ospfd, sizeof(no_ip_ospf_authentication_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_range_advertise_cost_cmd__X, &ospf_area_range_advertise_cost_cmd_ospfd, sizeof(ospf_area_range_advertise_cost_cmd_ospfd));
    memcpy(&__activeVars_lib->mpls_te_on_cmd__X, &mpls_te_on_cmd_ospfd, sizeof(mpls_te_on_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_rfc1583_flag_cmd__X, &ospf_rfc1583_flag_cmd_ospfd, sizeof(ospf_rfc1583_flag_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_authentication_key_cmd__X, &no_ip_ospf_authentication_key_cmd_ospfd, sizeof(no_ip_ospf_authentication_key_cmd_ospfd));
    __activeVars_ospfd->conf_debug_ospf_event__X =  0;
    memcpy(&__activeVars_ospfd->ospf_area_vlink_authtype_authkey_cmd__X, &ospf_area_vlink_authtype_authkey_cmd_ospfd, sizeof(ospf_area_vlink_authtype_authkey_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_rfc1583_flag_cmd__X, &no_ospf_rfc1583_flag_cmd_ospfd, sizeof(no_ospf_rfc1583_flag_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_vlink_param3_cmd__X, &ospf_area_vlink_param3_cmd_ospfd, sizeof(ospf_area_vlink_param3_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_transmit_delay_addr_cmd__X, &ip_ospf_transmit_delay_addr_cmd_ospfd, sizeof(ip_ospf_transmit_delay_addr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_vlink_param4_cmd__X, &ospf_area_vlink_param4_cmd_ospfd, sizeof(ospf_area_vlink_param4_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_priority_cmd__X, &ip_ospf_priority_cmd_ospfd, sizeof(ip_ospf_priority_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_always_type_cmd__X, &ospf_default_information_originate_always_type_cmd_ospfd, sizeof(ospf_default_information_originate_always_type_cmd_ospfd));
    memcpy(&__activeVars_ospfd->conf_debug_ospf_packet__X, &conf_debug_ospf_packet__T, sizeof(conf_debug_ospf_packet__T));
    memcpy(&__activeVars_ospfd->no_ospf_retransmit_interval_cmd__X, &no_ospf_retransmit_interval_cmd_ospfd, sizeof(no_ospf_retransmit_interval_cmd_ospfd));
    memcpy(&__activeVars_ospfd->debug_ospf_lsa_cmd__X, &debug_ospf_lsa_cmd_ospfd, sizeof(debug_ospf_lsa_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_passive_interface_addr_cmd__X, &no_ospf_passive_interface_addr_cmd_ospfd, sizeof(no_ospf_passive_interface_addr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_debug_ospf_packet_send_recv_cmd__X, &no_debug_ospf_packet_send_recv_cmd_ospfd, sizeof(no_debug_ospf_packet_send_recv_cmd_ospfd));
    __activeVars_ospfd->conf_debug_ospf_nssa__X =  0;
    memcpy(&__activeVars_ospfd->no_ospf_refresh_timer_cmd__X, &no_ospf_refresh_timer_cmd_ospfd, sizeof(no_ospf_refresh_timer_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_message_digest_key_addr_cmd__X, &no_ip_ospf_message_digest_key_addr_cmd_ospfd, sizeof(no_ip_ospf_message_digest_key_addr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_router_id_cmd__X, &no_ospf_router_id_cmd_ospfd, sizeof(no_ospf_router_id_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_cmd__X, &ospf_default_information_originate_cmd_ospfd, sizeof(ospf_default_information_originate_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distribute_list_out_cmd__X, &ospf_distribute_list_out_cmd_ospfd, sizeof(ospf_distribute_list_out_cmd_ospfd));
    memcpy(&__activeVars_ospfd->show_ip_ospf_cmd__X, &show_ip_ospf_cmd_ospfd, sizeof(show_ip_ospf_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_distance_source_access_list_cmd__X, &no_ospf_distance_source_access_list_cmd_ospfd, sizeof(no_ospf_distance_source_access_list_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_refresh_timer_cmd__X, &ospf_refresh_timer_cmd_ospfd, sizeof(ospf_refresh_timer_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_stub_no_summary_cmd__X, &ospf_area_stub_no_summary_cmd_ospfd, sizeof(ospf_area_stub_no_summary_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_retransmit_interval_cmd__X, &ospf_retransmit_interval_cmd_ospfd, sizeof(ospf_retransmit_interval_cmd_ospfd));
    memcpy(&__activeVars_lib->no_match_ip_next_hop_prefix_list_cmd__X, &no_match_ip_next_hop_prefix_list_cmd_ospfd, sizeof(no_match_ip_next_hop_prefix_list_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_vlink_md5_cmd__X, &ospf_area_vlink_md5_cmd_ospfd, sizeof(ospf_area_vlink_md5_cmd_ospfd));
    __activeVars_ospfd->term_debug_ospf_nsm__X =  0;
    memcpy(&__activeVars_ospfd->ospf_redistribute_source_routemap_cmd__X, &ospf_redistribute_source_routemap_cmd_ospfd, sizeof(ospf_redistribute_source_routemap_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_area_vlink_authtype_args_cmd__X, &ospf_area_vlink_authtype_args_cmd_ospfd, sizeof(ospf_area_vlink_authtype_args_cmd_ospfd));
    memcpy(&__activeVars_ospfd->debug_ospf_packet_send_recv_cmd__X, &debug_ospf_packet_send_recv_cmd_ospfd, sizeof(debug_ospf_packet_send_recv_cmd_ospfd));
    memcpy(&__activeVars_ospfd->show_ip_ospf_interface_cmd__X, &show_ip_ospf_interface_cmd_ospfd, sizeof(show_ip_ospf_interface_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_cost_addr_cmd__X, &no_ip_ospf_cost_addr_cmd_ospfd, sizeof(no_ip_ospf_cost_addr_cmd_ospfd));
    memcpy(&__activeVars_lib->no_match_ip_address_prefix_list_cmd__X, &no_match_ip_address_prefix_list_cmd_ospfd, sizeof(no_match_ip_address_prefix_list_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_redistribute_source_type_metric_routemap_cmd__X, &ospf_redistribute_source_type_metric_routemap_cmd_ospfd, sizeof(ospf_redistribute_source_type_metric_routemap_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_debug_ospf_event_cmd__X, &no_debug_ospf_event_cmd_ospfd, sizeof(no_debug_ospf_event_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_authentication_args_addr_cmd__X, &ip_ospf_authentication_args_addr_cmd_ospfd, sizeof(ip_ospf_authentication_args_addr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->show_ip_ospf_database_type_adv_router_cmd__X, &show_ip_ospf_database_type_adv_router_cmd_ospfd, sizeof(show_ip_ospf_database_type_adv_router_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_default_information_originate_cmd__X, &no_ospf_default_information_originate_cmd_ospfd, sizeof(no_ospf_default_information_originate_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_metric_cmd__X, &ospf_default_information_originate_metric_cmd_ospfd, sizeof(ospf_default_information_originate_metric_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_authentication_addr_cmd__X, &no_ip_ospf_authentication_addr_cmd_ospfd, sizeof(no_ip_ospf_authentication_addr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_metric_routemap_cmd__X, &ospf_default_information_originate_metric_routemap_cmd_ospfd, sizeof(ospf_default_information_originate_metric_routemap_cmd_ospfd));
    memcpy(&__activeVars_ospfd->show_ip_ospf_border_routers_cmd__X, &show_ip_ospf_border_routers_cmd_ospfd, sizeof(show_ip_ospf_border_routers_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_distance_cmd__X, &ospf_distance_cmd_ospfd, sizeof(ospf_distance_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_stub_no_summary_cmd__X, &no_ospf_area_stub_no_summary_cmd_ospfd, sizeof(no_ospf_area_stub_no_summary_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_shortcut_cmd__X, &no_ospf_area_shortcut_cmd_ospfd, sizeof(no_ospf_area_shortcut_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_import_list_cmd__X, &no_ospf_area_import_list_cmd_ospfd, sizeof(no_ospf_area_import_list_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ospf_default_information_originate_always_metric_routemap_cmd__X, &ospf_default_information_originate_always_metric_routemap_cmd_ospfd, sizeof(ospf_default_information_originate_always_metric_routemap_cmd_ospfd));
    memcpy(&__activeVars_lib->no_set_metric_type_cmd__X, &no_set_metric_type_cmd_ospfd, sizeof(no_set_metric_type_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ospf_area_vlink_authtype_authkey_cmd__X, &no_ospf_area_vlink_authtype_authkey_cmd_ospfd, sizeof(no_ospf_area_vlink_authtype_authkey_cmd_ospfd));
    memcpy(&__activeVars_ospfd->show_ip_ospf_database_type_id_cmd__X, &show_ip_ospf_database_type_id_cmd_ospfd, sizeof(show_ip_ospf_database_type_id_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_router_ospf_id_cmd__X, &no_router_ospf_id_cmd_ospfd, sizeof(no_router_ospf_id_cmd_ospfd));
    memcpy(&__activeVars_ospfd->ip_ospf_message_digest_key_addr_cmd__X, &ip_ospf_message_digest_key_addr_cmd_ospfd, sizeof(ip_ospf_message_digest_key_addr_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_cost_cmd__X, &no_ip_ospf_cost_cmd_ospfd, sizeof(no_ip_ospf_cost_cmd_ospfd));
    __activeVars_ospfd->term_debug_ospf_lsa__X =  0;
    memcpy(&__activeVars_lib->match_ip_nexthop_cmd__X, &match_ip_nexthop_cmd_ospfd, sizeof(match_ip_nexthop_cmd_ospfd));
    memcpy(&__activeVars_ospfd->show_ip_ospf_neighbor_detail_all_cmd__X, &show_ip_ospf_neighbor_detail_all_cmd_ospfd, sizeof(show_ip_ospf_neighbor_detail_all_cmd_ospfd));
    memcpy(&__activeVars_ospfd->debug_ospf_packet_send_recv_detail_cmd__X, &debug_ospf_packet_send_recv_detail_cmd_ospfd, sizeof(debug_ospf_packet_send_recv_detail_cmd_ospfd));
    memcpy(&__activeVars_ospfd->no_ip_ospf_transmit_delay_addr_cmd__X, &no_ip_ospf_transmit_delay_addr_cmd_ospfd, sizeof(no_ip_ospf_transmit_delay_addr_cmd_ospfd));
}
