#!/bin/bash

# USAGE: docker-make target where target can be 'html', 'pdf', 'server', 'deploy'
# when 'server' is used, the live website is available at http://localhost:8000

GUEST_COMMAND="make $*"
podman run --rm -i -t -p 8000:8000 -v "$HOME:$HOME" -w "$PWD" --userns=keep-id --security-opt label=disable -e PYTHONPATH="$PYTHONPATH" -e GUEST_COMMAND='${GUEST_COMMAND}' ghcr.io/omnetpp/docker-sphinx:251210 /bin/bash -c "${GUEST_COMMAND}"
