//
// Generated file, do not edit! Created by nedtool 5.1 from inet/physicallayer/ieee80211/packetlevel/Ieee80211ControlInfoDescr.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __INET__PHYSICALLAYER_IEEE80211CONTROLINFODESCR_M_H
#define __INET__PHYSICALLAYER_IEEE80211CONTROLINFODESCR_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0501
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
#include "inet/common/Units.h"
#include "inet/physicallayer/ieee80211/packetlevel/Ieee80211ControlInfo_m.h"
#include "inet/physicallayer/contract/packetlevel/RadioControlInfo_m.h"
#include "inet/physicallayer/ieee80211/mode/Ieee80211ModeSet.h"
#include "inet/physicallayer/ieee80211/mode/Ieee80211Channel.h"
// }}


namespace inet {
namespace physicallayer {

} // namespace physicallayer
} // namespace inet

#endif // ifndef __INET__PHYSICALLAYER_IEEE80211CONTROLINFODESCR_M_H

