(cd datarate ; ./run.sh)
(cd endtoenddelay ; ./run.sh)
(cd flow ; ./run.sh)
(cd jitter ; ./run.sh)
(cd propagationtime ; ./run.sh)
(cd queueingtime ; ./run.sh)
(cd residencetime ; ./run.sh)
(cd throughput ; ./run.sh)
(cd transmissiontime; ./run.sh)
(cd utilization ; ./run.sh)
