#! /bin/sh
#
# usage: runtest [<testfile>...]
# without args, runs all *.test files in the current directory
#

MAKE=make

TESTFILES=$*
if [ "x$TESTFILES" = "x" ]; then TESTFILES='*.test'; fi
if [ ! -d work ];  then mkdir work; fi
EXTRA_INCLUDES=`find ../../src/ -type d | sed s!^!-I../!`
opp_test -g $OPT -v $TESTFILES || exit 1
echo
(cd work; opp_makemake -f --deep -linet -L../../../src -P . --no-deep-includes $EXTRA_INCLUDES; $MAKE) || exit 1
echo
opp_test -r $OPT -v $TESTFILES || exit 1
echo
echo Results can be found in ./work
