//
// This module defines a Manager responsible for translate virtual ports and virtual ip address to real physical ports and ip address.
//
// @author Gabriel Gonz&aacute;lez Casta&ntilde;&eacute
// @date 2012-10-23
//

package inet.icancloud.Virtualization.Hypervisor.HypervisorManagers.H_NetworkManager.LocalNetManager;

simple LocalNetManager
{    	   
   @class(icancloud::LocalNetManager); 
}

