//
// Copyright (C) 2013 OpenSim Ltd.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program; if not, see <http://www.gnu.org/licenses/>.
//
// author: Zoltan Bojthe
//


#include "INETDefs.h"


EXECUTE_ON_STARTUP(
        ASSERT(STAGE_DO_LOCAL == 0);

        ASSERT(STAGE_DO_PUBLISH_RADIOSTATE >= STAGE_NODESTATUS_AVAILABLE);
        ASSERT(STAGE_DO_PUBLISH_RADIOSTATE >= STAGE_NOTIFICATIONBOARD_AVAILABLE);

        ASSERT(STAGE_IP_ADDRESS_AVAILABLE > STAGE_DO_CONFIGURE_IP_ADDRESSES);
        ASSERT(STAGE_IP_ADDRESS_AVAILABLE >= STAGE_INTERFACEENTRY_REGISTERED);

        ASSERT(STAGE_DO_COMPUTE_IP_AUTOCONFIGURATION >= STAGE_INTERFACEENTRY_REGISTERED);

        ASSERT(STAGE_DO_ADD_IP_PROTOCOLDATA_TO_INTERFACEENTRY >= STAGE_INTERFACEENTRY_REGISTERED);

        ASSERT(STAGE_DO_CONFIGURE_IP_ADDRESSES > STAGE_DO_COMPUTE_IP_AUTOCONFIGURATION);


        ASSERT(STAGE_DO_SET_INTERFACEENTRY_RTR_ADV_INTERVAL >= STAGE_INTERFACEENTRY_IP_PROTOCOLDATA_AVAILABLE);
        ASSERT(STAGE_DO_SET_INTERFACEENTRY_RTR_ADV_INTERVAL >= STAGE_INTERFACEENTRY_REGISTERED);

        ASSERT(STAGE_DO_ADD_STATIC_ROUTES > STAGE_DO_CONFIGURE_IP_ADDRESSES);

        ASSERT(STAGE_DO_ASSIGN_ROUTERID > STAGE_DO_CONFIGURE_IP_ADDRESSES);

        ASSERT(STAGE_DO_INIT_ROUTING_PROTOCOLS >= STAGE_INTERFACEENTRY_REGISTERED);
        ASSERT(STAGE_DO_INIT_ROUTING_PROTOCOLS >= STAGE_DO_REGISTER_TRANSPORTPROTOCOLID_IN_IP);

        ASSERT(STAGE_DO_INITIALIZE_AND_PUBLISH_LOCATION > STAGE_DO_LOCAL);
        ASSERT(STAGE_DO_REGISTER_RADIO > STAGE_DO_INITIALIZE_AND_PUBLISH_LOCATION);

        ASSERT(STAGE_ROUTINGTABLE_COMPLETED > STAGE_DO_INIT_ROUTING_PROTOCOLS);

        ASSERT(STAGE_DO_CONFIGURE_IP_ADDRESSES > STAGE_DO_COMPUTE_IP_AUTOCONFIGURATION);
        ASSERT(STAGE_DO_INITIALIZE_AND_PUBLISH_LOCATION > STAGE_DO_ASSIGN_MOBILITY_COORDINATOR);

        ASSERT(STAGE_TRANSPORT_LAYER_AVAILABLE > STAGE_DO_REGISTER_TRANSPORTPROTOCOLID_IN_IP);
);

